Targeted update
mzmine/mzmine3 pull request #1013
Opened 2022-11-29 08:52 UTC by SteffenHeu

- update targeted feature detection module
  - uses the csv utils and ImportTypes like the compound db search
  - supports ion mobility files
- add utility methods to CSVParsingUtils to easily extract CompoundDBAnnotations from a csv file
- update compound db search so we use some of the utility methods to avoid duplication

2022-12-06 00:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +        || baseAnnotation.getFormula() != null || baseAnnotation.getSmiles() != null)) {
How about we always calculate the neutral mass if its missing and use a priority of the sources
neutral mass > inchi > smiles > formula

2022-12-06 06:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionModuleTask.java
> +      Float.POSITIVE_INFINITY);
those are not really needed there is Range.all()

2022-12-06 06:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionModuleTask.java
> +      Float.POSITIVE_INFINITY);
empty comment

2022-12-06 06:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionModuleTask.java
> +      }
Thats a good one.
processIMS is true if canceled and processLcms is false...
maybe better not check the return state of these methods and rather check for isCanceled() after calling this methods. Looks redundant but is clear in purpose

2022-12-06 06:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionParameters.java
> +      FileSelectionType.OPEN);
Maybe use the same parameter name as for the file in local database search?

2022-12-06 06:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionParameters.java
> +      "Character(s) used to separate fields in the database file", ",");
Maybe add use \t for tab separated data

2022-12-06 06:36 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionParameters.java
> +  private static final List<ImportType> importTypes = List.of(
Would be great if all the parameters of the local csv library were just a sub parameter set that is used in both the database search and here

2022-12-06 06:39 UTC, robinschmid requested changes
Looks good to me. only a few comments

2022-12-06 06:39 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/CSVParsingUtils.java
> +        }
Best use case for the instanceof pattern matching

2022-12-06 07:29 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionModuleTask.java
> +      }
standard extract method :D

2022-12-06 07:32 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionModuleTask.java
> +      Float.POSITIVE_INFINITY);
no, it is needed because Range.all() is unbound, so it leads to errors later on:
```
      final double upperBreakPoint = doubleToleranceRange.upperEndpoint();
      final double lowerBreakPoint = doubleToleranceRange.upperEndpoint();
```

2022-12-06 07:33 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionParameters.java
> +  private static final List<ImportType> importTypes = List.of(
yeah, would be great....

2022-12-06 08:14 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionParameters.java
> +  private static final List<ImportType> importTypes = List.of(
:D
Yeah can be a later thing

2022-12-07 21:44 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionModuleTask.java
> +      Float.POSITIVE_INFINITY);
What does that mean?
So you cannot get the endpoints?

2022-12-07 23:46 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +    }
Is this only called in a single threaded environment?
I think it should. We load the library and create different ions to generate the final list of possible annotations.
Then this is fine. Otherwise we would need to synchronize?

2022-12-08 00:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/SimpleCompoundDBAnnotation.java
> +  public Float calculateScore(FeatureListRow row, @Nullable MZTolerance mzTolerance,
See #1023 I have changed this method to use the new FeatureListUtils.getAlignmentScore method. I think there are also some weird things here. 
There were checks if the value falls within the range but the matches method should already do this.
If it were still somehow falling outside the tolerance - the value should still be added 0 score and scorers should be incremented otherwise this field (mz,rt,mobility) will not be considered. See my PR

2022-12-08 01:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_ccscalc/CCSUtils.java
> +        new SimpleStringProperty());
What is this simple string property actually doing there?

2022-12-08 01:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_ccscalc/CCSUtils.java
> +        new SimpleStringProperty());
its the error message but why is it set but not used?

2022-12-08 01:26 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/ParameterSet.java
> +  }
This one I dont understand. Its not the value but the embedded parameter so its not really useful

2022-12-08 01:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/RangeUtils.java
> +  }
that was close. was just about to create one of those

2022-12-08 07:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +    }
Why does it have to be single threaded? There was some problem with the cdk right?

2022-12-08 07:40 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_targeted/TargetedFeatureDetectionModuleTask.java
> +      Float.POSITIVE_INFINITY);
exactly, range.all is unbound.

2022-12-08 07:43 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/ParameterSet.java
> +  }
It returns the parameter set of an OptionalModuleParameter. i wanted to keep the name the same as for `getEmbeddedParameterValue(OptionalParameter<T> parameter)` so it's easier to type

2022-12-08 17:56 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/ParameterSet.java
> +  }
why not getEmbeddedParameters instead of value

2022-12-08 17:58 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +    }
at least the data structure behind it is HashMap - so if this is called on multiple threads this will produce a concurrent mod.

2022-12-08 18:07 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +    }
ohh ok you are talking about the annotation itselfm not about the while method. 

Yeah i think this is not going to be used in a multithreaded environment

2022-12-08 18:08 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_ccscalc/CCSUtils.java
> +        new SimpleStringProperty());
Cause it is newly added :D can do later

2022-12-08 18:09 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/ParameterSet.java
> +  }
i wanted to keep the name the same as for other parameter types

2022-12-08 20:58 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +    }
okay

2022-12-08 20:59 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_ccscalc/CCSUtils.java
> +        new SimpleStringProperty());
:D

2022-12-08 20:59 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/ParameterSet.java
> +  }
ok

2022-12-08 20:59 UTC, merged