Biotransformer
mzmine/mzmine3 pull request #1037
Opened 2022-12-13 12:46 UTC by SteffenHeu

- Add Biotransformer integration (must be downloaded from their page, just added it for the test resources)
- Prediction for spectral db and compund db that have smiles codes in them
- Prediction for the whole flist or for a single row

2022-12-16 19:46 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
>    default String getSmiles() {
You removed @Override here but it should be there

2022-12-16 19:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +  default @Nullable CompoundDBAnnotation checkMatchAndGetErrors(FeatureListRow row,
Name is misleading - you do not get errors....
Maybe just matchAndClone()

2022-12-16 20:00 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/annotations/compounddb/EnzymeType.java
> +    return "biotransformer_enzyme_type";
this is not biotransformer specific and we usually do not add the type suffix. so better just do 
enzymes

unless its really more the enzyme type. then also change the header

2022-12-16 20:00 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/annotations/compounddb/EnzymeType.java
> +    return "Enzyme(s)";
just do Enzymes (can be one or more)

2022-12-16 20:01 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/annotations/compounddb/ReactionType.java
> +    return "biotransformer_reaction_type";
same here.
maybe instead of reaction -> transformation?

2022-12-16 20:04 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/annotations/SmilesStructureType.java
> +    }
is that good to have the double click do this here?

2022-12-16 23:29 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureListRow.java
> +        matches = newList;
at least for the other list types we now decided to just use mutable collections from the start

2022-12-16 23:30 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +        <MenuItem text="BioTransformer 3.0"
version number needed?

2022-12-17 00:08 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerFilterParameters.java
> +          MZmineCore.getConfiguration().getIntensityFormat(), 1E4));
default value for Optional should be false? for both thresholds

2022-12-17 00:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +  public static final FileNameParameter bioPath = new FileNameParameter("Bio Transformer Path",
BioTransformer without space

2022-12-17 00:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +          "superbio", "env"), "env");
is there any explanations for those values?
Maybe you could make an enum with meaningful toString - Human (allHuman)

2022-12-17 00:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +      "The number of steps to use for bio transformer.", 1, 1, 10);
i dont know biotransformer... is it iterations or is it the number of different transformations applied?
maybe more meaningful name and description here.

2022-12-17 00:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +  public static final ParameterSetParameter ionLibrary = new ParameterSetParameter("Ion Library",
Ion library lower case library

2022-12-17 00:14 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +      "Smiles source", """
maybe SMILES we also use capital case in SmilesStructureType

2022-12-17 00:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +    }*/
remove

2022-12-17 00:18 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +    final SmilesSource smilesSource = parameters.getValue(BioTransformerParameters.smilesSource);
maybe do in the constructor

2022-12-17 00:18 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +      @Nullable StringProperty compoundName) {
compoundName is not set in the method and also not used outside of the method

2022-12-17 00:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +    }
maybe the SmilesSource could handle this?
Like switch the value and then return the most appropriate smiles. Or use the latest addition that you did to get all the smiles.
But something is wrong here.

spectral library matches only needs to be checked if we are actually asking for that. 
Then String smiles is not used and might be null - if null you would want to return other compound annotations

2022-12-17 00:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +    if (checkProdcutIntensity && row.getBestFeature().getHeight() < minProductIntensity) {
type: checkProductIntensity

2022-12-17 00:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +      final FeatureAnnotation bestAnnotation = getBestAnnotation(row, null);
why are you not just mapping bestAnnotation -> row or just using separate lists with index for smiles, annotation, row. The smiles you get from the annotation so would be easier to keep the annotation in the first place

2022-12-17 00:28 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +      }
if you keep the annotation in the first place - the concurrent mod is not so dangerous anymore

2022-12-17 00:31 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +                .sort(Comparator.comparingDouble(a -> Objects.requireNonNullElse(a.getScore(), 0f)));
this is done only once for each row right? Then its okay. Otherwise you could also just do it outside of the loop and sort all results there

2022-12-17 00:33 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +    var ionLibrary = new IonNetworkLibrary((IonLibraryParameterSet) ionLibraryParam);
Maybe you could overload a method where the ionlibrary is already passed in as argument and then do this in the constructor.
Still okay for real single row to do this in the other method where only the parameters are passed in

2022-12-17 00:36 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +      return List.of();
maybe this exception should be catched outiside... to end the task that is running biotransformer?

2022-12-19 00:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerUtil.java
> +  public static List<String> buildCommandLineArguments(String smiles, ParameterSet param,
maybe you could make the smiles @NotNull and then also the returntype NotNull?

2022-12-19 00:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerUtil.java
> +      @NotNull final AtomicInteger parsedLines) throws IOException {
Can this be replaces with the new method that you made for loading libraries?

2022-12-19 00:36 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerUtil.java
> +  }
This seems like the most general thing that should be somewhere with the CompoundDBAnnotation... Maybe there is a method already?

2022-12-19 00:39 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerUtil.java
> +      process.getOutputStream().close();
Can this be done with a try-with-resources for autoclose?
Same with all the readers that are opened... there are some input and output streams open.... which ones do need to be closed?

2022-12-19 00:39 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerUtil.java
> +  }
This seems like the new DB import

2022-12-19 00:48 UTC, robinschmid requested changes
Great addition. But a few comments. Mostly for harmonizing with recent changes

2022-12-19 00:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/SingleRowPredictionTask.java
> +public class SingleRowPredictionTask extends AbstractTask {
Change name to BioTransformerSingleRowTask

2022-12-19 00:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/LocalCSVDatabaseSearchTask.java
> +  }
is this still the way to do it?
or did we add a general method for this somewhere? Because its used in different places

2022-12-19 00:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
>    }
I guess you added a new method to get the smiles from all from arow now. So maybe we can use it here.

2022-12-19 00:48 UTC, robinschmid commented on src/test/java/BioTransformerTest.java
> +  void testCmdGeneration() {
I guess you have to deactivate all tests?

2022-12-19 08:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/compoundannotations/CompoundDBAnnotation.java
> +  default @Nullable CompoundDBAnnotation checkMatchAndGetErrors(FeatureListRow row,
checkMatchAndCalculateDeviation

2022-12-19 09:23 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +        <MenuItem text="BioTransformer 3.0"
yeah it doesnt work with 2

2022-12-19 09:28 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +          "superbio", "env"), "env");
It's the names of the bio transformer parameters. Its a CLI tool, so users should be familiar with it.

2022-12-19 09:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +      final FeatureAnnotation bestAnnotation = getBestAnnotation(row, null);
the same compound may be found as different adducts, so the annotations will not be equal. the smiles will be however. so its done to avoid over-annotation.

2022-12-19 09:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerTask.java
> +                .sort(Comparator.comparingDouble(a -> Objects.requireNonNullElse(a.getScore(), 0f)));
it's done every time an annotation is added to a row. But that should not be the case too often. i'd rahter have the logic in one place here than move it out of the loop for performance purposes

2022-12-19 11:26 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerUtil.java
> +      process.getOutputStream().close();
dont think so

2022-12-19 11:29 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/LocalCSVDatabaseSearchTask.java
> +  }
checkMatchAndGetErrors is the new method for it. It replaces a lot of code and creates the cloned annotation. Renamed after review.

2022-12-19 11:32 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
>    }
would still have to check which annotation type is the better source.

2022-12-21 08:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +        <MenuItem text="BioTransformer 3.0"
Could also be a disclaimer... But we can also keep it in the title

2022-12-21 08:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_biotransformer/BioTransformerParameters.java
> +          "superbio", "env"), "env");
I thought, we are wrapping it - so we could define a better name in the combobox so that people can more easily know

2022-12-21 10:34 UTC, robinschmid commented
There is a conflict

2023-01-17 08:23 UTC, merged