Metadata import and other refactoring
mzmine/mzmine3 pull request #1040
Opened 2022-12-14 23:27 UTC by robinschmid

Sorry for this big change list. Many small simple changes

Many datsets implemented task instead of AbstractTask and their behavior for status etc was different. Now all use either AbstractTask or AbstractTaskXYDataset.

Also the AllTaskFinishedListener needed to get some callbacks so that we can use it in the ProjectMetadataPaneController.importParameters .

2022-12-15 09:59 UTC, SteffenHeu requested changes
some comments

2022-12-15 09:59 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/impl/spectra/FrameSummedSpectrumProvider.java
> +  private final double finishedPercentage;
remove instead of making final, not used

2022-12-15 09:59 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/main/MZmineCore.java
> +  public static ExitCode setupAndRunModule(final Class<? extends MZmineRunnableModule> moduleClass,
should we check it its headless mode and throw an error then?

2022-12-15 09:59 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataanalysis/clustering/ClusteringTask.java
> +import javax.swing.SwingUtilities;
why is this needed all of the sudden?

2022-12-15 09:59 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/projectmetadata/io/WideTableIOUtils.java
> +public class WideTableIOUtils implements TableIOUtils {
whats the difference between a long and a wide table=

2022-12-15 09:59 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/projectmetadata/io/LongTableIOUtils.java
> +   * DESC  - description of the parameter FILE  - name of the file to which the parameter belong to
format made this worse

2022-12-15 09:59 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/taskcontrol/AllTasksFinishedListener.java
> +  public static void registerCallbacks(final List<Task> tasks, final boolean stopOnError,
did you check if its fine with GC and finished tasks in case a listener was added?

2022-12-15 19:47 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/impl/spectra/FrameSummedSpectrumProvider.java
> +  private final double finishedPercentage;
done

2022-12-15 19:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/main/MZmineCore.java
> +  public static ExitCode setupAndRunModule(final Class<? extends MZmineRunnableModule> moduleClass,
added  an IllegalStateException there

2022-12-15 19:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataanalysis/clustering/ClusteringTask.java
> +import javax.swing.SwingUtilities;
The style format reorganized the imports. The only real difference is the AbstractTaskXYDataset

2022-12-15 19:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/projectmetadata/io/WideTableIOUtils.java
> +public class WideTableIOUtils implements TableIOUtils {
Right now we do not really use the long but the plan was to support both imports and exports.


https://www.statology.org/long-vs-wide-data/#:~:text=A%20wide%20format%20contains%20values,repeat%20in%20the%20first%20column.&text=Notice%20that%20in%20the%20wide,the%20first%20column%20is%20unique.

2022-12-15 21:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/projectmetadata/io/LongTableIOUtils.java
> +   * DESC  - description of the parameter FILE  - name of the file to which the parameter belong to
True. Added linebreaks

2022-12-15 21:17 UTC, robinschmid commented on src/main/java/io/github/mzmine/taskcontrol/AllTasksFinishedListener.java
> +  public static void registerCallbacks(final List<Task> tasks, final boolean stopOnError,
will try

2022-12-15 22:31 UTC, robinschmid commented
I imported 100 times the same metadata sheet from the import dialog - using the AllTaskFinish listener and it seems to work fine - no memory leak. Thats only Javafx stuff here

![image](https://user-images.githubusercontent.com/10366914/207981076-d7724b63-65ef-44c0-a1e3-f4241c936364.png)

2022-12-19 01:17 UTC, robinschmid commented
All done from my side

2022-12-21 10:00 UTC, SteffenHeu approved these changes

2022-12-21 10:12 UTC, merged