Batch wizard 2.0
mzmine/mzmine3 pull request #1059
Opened 2022-12-25 14:22 UTC by robinschmid

Reworked the layout and some internals to make it more modular.

WizardPreset defines the presets for each part of the workflow. In the future we could even have load save of presets - or we could just load save the whole parameter set.

For now I have added some icons to build a scheme, created parameter sets for each individual part of the workflow.

GC-MS workflow is incomplete. I need input on this.

- added smoothing parameter for RT and IMS
- added IMS parameters

2022-12-25 14:28 UTC, robinschmid commented
I like the new layout. And it scales nicely even on small screens.

Comparison to before
![image](https://user-images.githubusercontent.com/10366914/209471872-219dd398-f56d-44af-abb4-9395faee23c6.png)

2023-01-04 15:15 UTC, SteffenHeu requested changes
some comments. 

whats the wizard_icons_hilic_copy for?

2023-01-04 15:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardChromatographyParameters.java
> +  public WizardChromatographyParameters(final ChromatographyDefaults defaults) {
i liked the previous solution with a hardcoded constructor way more. this makes it a lot easier to overlook a paremeter when a new step or so is added to the wizard.

2023-01-04 15:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardChromatographyParameters.java
> +  public WizardChromatographyParameters(final ChromatographyDefaults defaults) {
can you make it like ChromatographyDefaults.LC.applyToParameterSet and put all parameters in the constructor of LC?

2023-01-04 15:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardIonMobilityParameters.java
> +    setParameter(approximateImsFWHM, 0.04);
fwhm was definitely different for DTIMS and TIMS before

2023-01-04 15:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardMassSpectrometerParameters.java
> +  public WizardMassSpectrometerParameters(final MsInstrumentDefaults defaults) {
same as earlier

2023-01-04 15:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/HiddenParameter.java
> +public class HiddenParameter<V> implements Parameter<V> {
i think we had this before

2023-01-04 15:15 UTC, SteffenHeu commented on src/test/resources/spectral_libraries/massbank_eu.txt
> +ACCESSION: MSBNK-RIKEN-PR010001
whats this file?

2023-01-04 15:15 UTC, SteffenHeu commented on src/test/resources/spectral_libraries/massbank_eu_lc.txt
> +ACCESSION: MSBNK-BGC_Munich-RP001402
whats this file?

2023-01-05 10:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/MobilityType.java
> +  OTHER("none", "none", "other IMS"), //
Otherwise need to create figures for all?

2023-01-05 10:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardBatchBuilder.java
> +    // TODO maybe change to inter sample
so I changed this to interSampleRtTol now

2023-01-05 10:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/HiddenParameter.java
> +public class HiddenParameter<V> implements Parameter<V> {
Even the same name... I modified the old hidden parameter to have all the same functionality.

2023-01-05 10:33 UTC, robinschmid commented on src/test/resources/spectral_libraries/massbank_eu.txt
> +ACCESSION: MSBNK-RIKEN-PR010001
Its two example spectra from MassBankEU that I wanted to add as reference for the library export stuff... It slipped in here.

2023-01-05 10:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardMassSpectrometerParameters.java
> +  public WizardMassSpectrometerParameters(final MsInstrumentDefaults defaults) {
What do you mean?

2023-01-05 10:38 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/defaults/DefaultMsParameters.java
> -      1E2, 1E3, new MZTolerance(0.003, 15), new MZTolerance(0.0015, 3), new MZTolerance(0.004, 8));
you mean those parameters?

2023-01-05 10:39 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardIonMobilityParameters.java
> +    setParameter(approximateImsFWHM, 0.04);
There was no FWHM for IMS I added those

2023-01-05 12:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardIonMobilityParameters.java
> +    setParameter(approximateImsFWHM, 0.04);
is now 0.01, this is the constant that was used before

2023-01-05 12:30 UTC, robinschmid commented
I added constructors that follow your advice.
To force that all parameters are set

2023-01-05 14:20 UTC, asmirn1 commented
@robinschmid The new wizard looks great! What help do you need with GC-MS workflow?

2023-01-09 08:21 UTC, robinschmid commented
Yeah that would be great.

2023-01-09 13:53 UTC, asmirn1 commented
@robinschmid That sounds good. We'll wait until it's merged then.

2023-01-11 13:20 UTC, SteffenHeu approved these changes

2023-01-11 13:20 UTC, merged

2023-01-11 20:16 UTC, tnguy271 commented
hi @robinschmid Thank you for the changes. I pull master branch and try to run the wizard but getting an exception: java.lang.IllegalArgumentException: Parameter Workflow does not exist.

2023-01-11 22:04 UTC, robinschmid commented
There is another or that needs to be merged first. Then you will have great opportunity to implement the GC EI workflow. And maybe to provide different parameters for instruments

2023-01-17 16:30 UTC, tnguy271 commented
hi @robinschmid I just made pr #1078 for adding gc workflow to your new wizard.