Add workflows to wizard
mzmine/mzmine3 pull request #1087
Opened 2023-01-20 17:15 UTC by robinschmid

2023-01-20 17:39 UTC, robinschmid commented
@tnguy271 @SteffenHeu 
Everything seems to work from my side...
I already started the `io.github.mzmine.modules.tools.batchwizard.builders.WizardBatchBuilderGcEiDeconvolution` and the imaging alternative.

Lets review the current state first and then you both could implement the workflow itself.

The idea is that the WORKFLOW parameters like `IonInterfaceGcElectronImpactWizardParameters` can hold specific parameters that are more specific to the workflow rather than the GC separation for example.
This could be the deconvolution parameters etc... but you can also add them to the `IonInterfaceGcElectronImpactWizardParameters`

If you have some questions ask me and we can have a zoom call.

![image](https://user-images.githubusercontent.com/10366914/213765835-5c5b695a-133d-4204-96c6-747787629dec.png)

2023-01-23 15:32 UTC, robinschmid commented
Now the workflows are restricted to the specific presets chosen. 
e.g., TIMS will only allow qTOF as instrument.
GC-EI will only allow the EI deconvolution workflow

2023-01-26 13:54 UTC, SteffenHeu requested changes
Wow this got really complicated really fast. I got soem comments and probably more after they are clarified :D

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/ParameterUtils.java
> +  public static boolean equalValues(final ParameterSet a, final ParameterSet b) {
Did you check if this exists in the raw data save utils? i feel like i implemented it there

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/impl/ComposedParameterSet.java
> +public abstract class ComposedParameterSet implements ParameterSet {
Why not extend SimpleParameterSet?

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/BatchWizardTab.java
> +    var ionization = workflowSteps.get(WizardPart.ION_INTERFACE)
This is the interface and not the ionization, or?

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/AbstractIonInterfaceWizardParameters.java
> +  public enum IonInterfaceDefaults implements WizardParameterFactory {
i spent ages looking for this, please move to individual file

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardPart.java
> +  public Object[] getDefaultPresets() {
It says this method is not used anywhere. And returning either an Enum or a string is pretty hard to wrap my head around. Can we remove this?

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/BatchWizardTab.java
> +    List<WizardPreset> filteredWorkflows = ALL_PRESETS.get(WizardPart.WORKFLOW).stream()
This is pretty complecated and kinda hard-coded. Could we let each WizardParameterFactory know which WizardPreset parts it does not like and does not want to be combined with?

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardPreset.java
> +public record WizardPreset(@NotNull String name, @NotNull String uniquePresetId,
So this is a preset for a wizard part? The connection is super hard to spot.
Can we move the functionality of this class into the AbstractWizardParameters? provinding a name and a id in  there does not seem too far off.

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WorkflowWizardParameters.java
> +  public enum WorkflowDefaults implements WizardParameterFactory {
Move into separate file. Also this is the workflow itself, why is this called default?

2023-01-26 13:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/BatchWizardTab.java
> +    final BatchQueue q = WizardBatchBuilder.createBatchBuilderForWorkflow(workflowSteps)
I dont know if the batch WizardBatchBuilder is the correct place for this method. It seems very unintuitive. As far as i understand, the batch is created by the builder and the builder is determined by the workflow that is selected. So why doesn't the workflow supply the correct builder?

2023-01-26 14:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardPresetDefaults.java
> + * Helper factory for presets
Could push it into WizardPreset.createAllPresets
I kept it outside because I thought its not really a function of that. but can do

2023-01-26 14:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardWorkflow.java
> +public class WizardWorkflow extends AbstractList<WizardPreset> {
Added jdoc. The Workflow defines a whole or partial workflow supported by the wizard. 
So WizardPresets for WizardParts - can be saved partially and then applied to the current workflow.

2023-01-26 14:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +    noiseLevelMs1 = get(params, MassSpectrometerWizardParameters.ms1NoiseLevel, 0d);
This was actually wrong from my side, sorry.
Later removed the default values which I did now.
The parameter is always present so providing a default does not make sense

2023-01-26 14:26 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +    param.setParameter(DuplicateFilterParameters.mzDifferenceMax, mzTol);
Duplicate filter can use very narrow tolerances because we are searching for duplicates.
After gap filling, the average values should be super similar

2023-01-26 14:28 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +    param.setParameter(ADAPChromatogramBuilderParameters.minGroupIntensity, noiseLevelMs1);
I think its fair to use the same noise level here. Maybe easier for people to report on? but open to changes

2023-01-26 14:30 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +      }
cannot use the same name because of type erasure. 
But I removed both methods no need for default values, the latest parameters are always present

2023-01-26 14:33 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
>      if (!filter13C && minAlignedSamples < 2) {
People do not necessarily have to select files so far... they could do so later although that is stupid. I think we can just leave it if people type in they want at least 5 samples they shall get them

2023-01-26 14:33 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> -  private MZmineProcessingStep<MZmineProcessingModule> makeRtResolvingStep() {
Yes. LC local min; GC adap

2023-01-26 14:40 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +  protected static void makeDdaExportSteps(final BatchQueue q, final Boolean isExportActive,
Multiple steps are created in this method. 
We use this pattern in multiple places to declutter the workflow creation (push the ifs into the makeStep method)

2023-01-26 14:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +  protected static void makeDdaExportSteps(final BatchQueue q, final Boolean isExportActive,
See   makeMassDetectorSteps(final BatchQueue q)

2023-01-26 14:53 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +  protected MZmineProcessingStep<MZmineProcessingModule> makeMobilityScanMergerStep() {
static is when parameters might change

2023-01-26 14:53 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +  protected void makeSmoothingStep(final BatchQueue q, final boolean rt,
might be null though... and in this case we do not add steps...

2023-01-26 14:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilderImagingDda.java
> +  public WizardBatchBuilderImagingDda(final WizardWorkflow steps) {
For your workflow...
Can also be MS1 only

2023-01-26 14:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardWorkflows.java
> +public enum WizardWorkflows {
Good catch this was not used in the end. I thought we need it to basically decide what workflow we use

2023-01-26 14:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardWorkflows.java
> +public enum WizardWorkflows {
removed

2023-01-26 17:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/io/WizardWorkflowIOUtils.java
> +        moduleElement.setAttribute(PRESET_ATTRIBUTE, step.uniquePresetId());
This version will be automatically available once we merge the parameter version.
WizardStepPreset is now directly a Parameterset

2023-01-26 17:51 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/IonMobilityWizardParameters.java
> +        case NO_IMS -> "";
I thought it looks pretty good at the moment. Then you can read it like expected
HPLC -    - Orbitrap

2023-01-26 17:51 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/IonMobilityWizardParameters.java
> +        case NO_IMS -> "";
but open

2023-01-26 17:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/MassSpectrometerWizardParameters.java
> +    Orbitrap, qTOF, FTICR, LOW_RES;
No preference

2023-01-26 17:57 UTC, robinschmid commented
@SteffenHeu changed all to Factory
ImsDefaults is now `enum IonMobilityWizardParameterFactory` because it produces instances of IonMobilityWizardParameter

You think we should change some of those names to shorten them? 
Maybe IonMobilityPreset and IonMobilityPresetFactory

2023-01-26 18:00 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/AbstractWizardParameters.java
> +public abstract sealed class AbstractWizardParameters<T> extends ComposedParameterSet implements
This is now the WizardStepPreset

2023-01-26 18:04 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/AbstractWizardParameters.java
> +public abstract sealed class AbstractWizardParameters<T> extends ComposedParameterSet implements
added jdoc

2023-01-26 18:08 UTC, SteffenHeu commented
To be honest, since the "presets" are parameter sets we should call them parameter sets. The word preset would be a synonym and we should stick to the actual naming conventiosn we already have imo.

2023-01-26 18:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/MassSpectrometerWizardParameters.java
> +    Orbitrap, qTOF, FTICR, LOW_RES;
Done

2023-01-26 18:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WorkflowDdaWizardParameters.java
> +    setParameter(exportSirius, exportSiriusActive);
Might be though.... I mean maybe someone has a DDA method somewhere or the vendors provide soon...
Or we add your workflow to it...

2023-01-26 18:41 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/BatchWizardTab.java
> +    var ionization = workflowSteps.get(WizardPart.ION_INTERFACE)
ION_INTERFACE is all LC, GC, MALDI, .... 
Not sure how to call it otherwise

2023-01-26 18:41 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/BatchWizardTab.java
> +    List<WizardPreset> filteredWorkflows = ALL_PRESETS.get(WizardPart.WORKFLOW).stream()
Would be nice to do this... but not sure if that's too much honestly. Its not gonna change that often.
Let me think about it.

2023-01-26 18:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/WizardPreset.java
> +public record WizardPreset(@NotNull String name, @NotNull String uniquePresetId,
done

2023-01-26 18:43 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/BatchWizardTab.java
> +    final BatchQueue q = WizardBatchBuilder.createBatchBuilderForWorkflow(workflowSteps)
Its the static factory pattern.
This is the super class delegating the creation of the sub classes

2023-01-26 18:43 UTC, robinschmid commented
Okay

2023-01-26 18:43 UTC, robinschmid commented
Done for now

2023-01-27 15:29 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +      case LIBRARY_GENERATION, MS1_ONLY -> throw new UnsupportedOperationException(
maybe remove them for now then?

2023-01-27 15:29 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardStepPreset.java
> +public abstract sealed class WizardStepPreset extends ComposedParameterSet implements
WizardStepParameters

2023-01-30 08:19 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardStepPreset.java
> +public abstract sealed class WizardStepPreset extends ComposedParameterSet implements
I thought it would be nice to distinguish them. As they extend the parameters to something more but can also rename

2023-01-30 08:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +      case LIBRARY_GENERATION, MS1_ONLY -> throw new UnsupportedOperationException(
Lets keep it for now and decide once we create the new version?
I could implement the library generation workflow.
MS1 only for LC-MS could use the same workflow builder and just not export SIRIUS and GNPS

2023-01-30 09:52 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/WizardBatchBuilder.java
> +      case LIBRARY_GENERATION, MS1_ONLY -> throw new UnsupportedOperationException(
ok

2023-01-30 09:52 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WizardStepPreset.java
> +public abstract sealed class WizardStepPreset extends ComposedParameterSet implements
I'd like the rename. can merge afterwards

2023-01-30 12:29 UTC, merged