featureML export module
mzmine/mzmine3 pull request #1100
Opened 2023-01-25 17:57 UTC by christophuv

Version 1 of an export module for visualizing the results of a feature list. The feature list is exported to the featureML file format, which can be loaded into TOPPView. Each detected feature is illustrated as a box in TOPPView and on highlight different sub-boxes are shown for the features of the different samples. Feature consensus areas can easily be inspected allowing to optimize the feature detection step with MzMine graphically towards a high number of features. Furthermore, users can visually identify regions in there chromatograms with peaks that have not been found with their current settings.

2023-01-26 08:15 UTC, SteffenHeu requested changes
Thanks, i think this is a great addition. I added some comments

2023-01-26 08:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    	minRT = 1000000.;
The indentation is 4 lines, we are using two. you can use the formatter we supply with the project (mzmine-intellij-code-formater.xml). See here how to set it up: https://mzmine.github.io/mzmine_documentation/contribute_intellij.html#code-formatter

2023-01-26 08:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        	if(row.getFeature(rawFile) != null) {
you basically want to use the widest range of all detected features here, right? I think this should be equivalent to the rt range of the row.

I noticed we somehow don't have a convenience method for that, but you can use
`row.get(RTRangeType.class)`

2023-01-26 08:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        int hulNum = 1;
what does hulNum mean? best write out the full name

2023-01-26 08:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        writer.write(String.format("      <feature id='%d'>", row.getID()));
since this is an xml based format, did you intentionally write it with a normal file writer? It's fine with me, but i feel like it would be way easier to maintain if it used an xml writer sich as the `javax.xml.stream.XMLStreamWriter;`.

2023-01-26 08:15 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +      checkConcurrentModification(featureList, numRows, numFeatures, numMS2);
This is a relict from the GNPS export which exports multiple files for the same feature list. i don't think it's needed here.

2023-01-26 08:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularParameters.java
> +  );
Looks like python code. Please setup the code formatter to automatically apply after each save / commit. One of the reasons is that otherwise later those lines are automatically changed in the next edid and clutter the change list in PRs.
https://mzmine.github.io/mzmine_documentation/contribute_intellij.html#code-formatter

2023-01-26 08:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularParameters.java
> +  public static final FeatureListsParameter featureLists = new FeatureListsParameter(1);
You can remove the 1 and allow any number of feature lists. At least in the filename parameter you are allowing the {} pattern to be replaced with the feature list name. In the export you can then write one file per feature list.

2023-01-26 08:26 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +  public static final String DATAFILE_PREFIX = "datafile";
unused?

2023-01-26 08:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +  private final String headerSeparator = ":";
unused

2023-01-26 12:01 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +      checkConcurrentModification(featureList, numRows, numFeatures, numMS2);
can be removed

2023-01-26 12:03 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +  private void checkConcurrentModification(FeatureList featureList, int numRows, long numFeatures,
this method can be deleted

2023-01-26 12:07 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("<?xml version='1.0' encoding='ISO-8859-1'?>"));
can you try if UTF-8 works in TOPPView etc.
UTF-8 is a better standard and more widely used

2023-01-26 12:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("      <software name='MzMine3' version='%s' />", "TODO add version here"));
MZmine 3
MZmineCore.getMZmineVersion().toString()

2023-01-26 12:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("    <featureList count='%d'>", rowTypes.size()));
what does this parameter refer to?
rowTypes is the number of columns

2023-01-26 12:14 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    double minRT = 100000.;
for those things its best to just use Double.MAX_VALUE or POSITIVE_INFINITY, similar for minimum use NEGATIVE_INFITINY
But steffen already mentioned there is a RTRangeType column that gives you this information

2023-01-26 12:39 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        writer.write(String.format("      <feature id='%d'>", row.getID()));
Second option would be something like this:

```java
// Create the doc.
final Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument();
final Element fmap = createElement(doc, "featureMap",// 
    "version", "1.4",// 
    "id", "fm_16311276685788915066", // 
    "xsi:noNamespaceSchemaLocation", "http://open-ms.sourceforge.net/schemas/FeatureXML_1_4.xsd",//
    "xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
    doc.appendChild(fmap);

    Element processing = createElement(doc, "dataProcessing", "completion_time", date);
    fmap.appendChild(processing);

    processing.appendChild(createElement(doc, "software", "name", "MZmine", MZmineCore.getMZmineVersion()))

// Create transformer.
final Transformer transformer = TransformerFactory.newInstance().newTransformer();
    transformer.setOutputProperty(OutputKeys.METHOD, "xml");
    transformer.setOutputProperty(OutputKeys.INDENT, "yes");
    transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
    transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");

    // Write to file and transform.
    transformer.transform(new DOMSource(doc), new StreamResult(new FileOutputStream(file)));
```

And here the method to create the elements with attributes
```java 
private Element createElement(final Document doc, final String id,
      final Object... attributeValuePairs) {
    Element element = doc.createElement(id);
    for (int i = 0; i < attributeValuePairs.length; i += 2) {
      Object key = attributeValuePairs[i];
      Object value = attributeValuePairs[i + 1];
      element.setAttribute(key.toString(), Objects.requireNonNullElse(value.toString(), ""));
    }
    return element;
  }
```

2023-01-26 12:39 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/TableFormat.java
> +public enum TableFormat {
You are not using this class right?
And its just copied

2023-01-26 12:40 UTC, robinschmid reviewed
Looks very good. 
Just a few comments to make it better but it seems that everything is in place so far.

Steffen and I started to look through it at the same time so there were some duplicate comemnts, sorry for that.

2023-01-26 12:45 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        writer.write(String.format("      <feature id='%d'>", row.getID()));
For files that can get really big the DOC based xml readers/writers are not good because they map the whole file into ram when reading writing. The Stream readers/writers are better suited for that.

2023-01-26 12:46 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("    <featureList count='%d'>", rowTypes.size()));
probably featureList.getNumberOfRows()

2023-01-26 19:03 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +public class FeatureMLExportModularTask extends AbstractTask implements ProcessedItemsCounter {
Thank you, did that

2023-01-26 19:03 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    	minRT = 1000000.;
Thank you, did that and reformatted the code in the last commit

2023-01-26 19:03 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        	if(row.getFeature(rawFile) != null) {
Thank you, that was what I was looking for

2023-01-26 19:03 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        int hulNum = 1;
Thank you, renamed the variable

2023-01-26 19:04 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        writer.write(String.format("      <feature id='%d'>", row.getID()));
Thank you, changed to that writer

2023-01-26 19:04 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +      checkConcurrentModification(featureList, numRows, numFeatures, numMS2);
Thank you, did that

2023-01-26 19:04 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularParameters.java
> +  );
Thank you, did that and formatted the code in the last commit

2023-01-26 19:04 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularParameters.java
> +  public static final FeatureListsParameter featureLists = new FeatureListsParameter(1);
Thank you, did that

2023-01-26 19:04 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +  public static final String DATAFILE_PREFIX = "datafile";
Thank you, removed it

2023-01-26 19:05 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +  private final String headerSeparator = ":";
Thank you, removed the separator

2023-01-26 19:05 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +  private void checkConcurrentModification(FeatureList featureList, int numRows, long numFeatures,
Thank you, did that

2023-01-26 19:05 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("<?xml version='1.0' encoding='ISO-8859-1'?>"));
Thank you, good idea

2023-01-26 19:05 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("      <software name='MzMine3' version='%s' />", "TODO add version here"));
Thank you, that was what I was looking for

2023-01-26 19:06 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("    <featureList count='%d'>", rowTypes.size()));
Thank you, that was a bug, replaced by the number of rows

2023-01-26 19:06 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    writer.write(String.format("    <featureList count='%d'>", rowTypes.size()));
sorry, the number of files the feature was detected in

2023-01-26 19:06 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    double minRT = 100000.;
Thank you, it is no longer necessary as the range is now derived from a function

2023-01-26 19:06 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/TableFormat.java
> +public enum TableFormat {
Thank you, did that

2023-01-26 19:08 UTC, christophuv commented
Thanks for your comments and as well for your thorough look into my code. 
I addressed them and updated the code. Please find the new commits here

2023-01-27 08:49 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        writer.write(String.format("      <feature id='%d'>", row.getID()));
True but they are also harder to do right?
I am fine with both.

2023-01-27 08:53 UTC, robinschmid commented
FYI I  activated the GitHub actions that run the builds and tests on all three major platforms Windows, macOS, Ubuntu
An easy way to see if everything runs smoothly

2023-01-27 08:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularParameters.java
> +    public static final ComboParameter<FeatureListRowsFilter> filter = new ComboParameter<>("Filter rows", "Limit the exported rows to those with MS/MS data (or annotated rows)", FeatureListRowsFilte
Did you apply the code formatter to all files?
its in the main directory
mzmine-intellij-code-formater.xml

2023-01-27 08:56 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +// https://github.com/OpenMS/OpenMS/blob/7a2e4a41d4c9f511306afcb8bb4f1b773ace9b9a/share/OpenMS/SCHEMAS/FeatureXML_1_9.xsd
Thats okay like this. You could also use JavaDoc here 
/**
*
*/

2023-01-27 09:06 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +                BufferedWriter writer = Files.newBufferedWriter(curFile.toPath(), StandardCharsets.UTF_8);
Best way is to do a try with resources. BufferedWriter is auto closable and this way you are safe that the locks on the files are released. Previously this was done with a try-catch-finally block where you do writer.close in the finally - thats unsafe and might in some cases not be closed
```java
try(BufferedWriter writer = Files.newBufferedWriter(new File("").toPath(), StandardCharsets.UTF_8)) {
```

2023-01-27 09:07 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +                writer.close();
remove the writer.close() when using try with resources

2023-01-27 09:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        double meanMZ = 0.;
you could inline those values now. 
You are setting them in the for loop. 
Optional

2023-01-27 09:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        this.generateElement(xmlWriter, "featureMap", new String[]{"version", "1.4", "id", "fm_16311276685788915066", "xsi:noNamespaceSchemaLocation", "http://open-ms.sourceforge.net/schemas/FeatureX
apply code formatter

2023-01-27 09:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        this.generateEmptyElement(xmlWriter, "software", new String[]{"name", "MzMine3", "version", MZmineCore.getMZmineVersion().toString()});
Maybe use as tool name MZmine     without 3 and MZ upper   mine lower case

2023-01-27 09:18 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    }
This one can be removed. it seems unused

2023-01-27 09:21 UTC, robinschmid commented
Only a few last comments. Thanks for using the XML stream builder. definitely the best option here. And nice solution. 

Some of the comments are optional. 
But these two are important:

- [ ] try with resources for the BufferedWriter 
- [ ] code formatter applied to all your files - somehow it seems like it did not work

2023-01-27 11:23 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularParameters.java
> +    public static final ComboParameter<FeatureListRowsFilter> filter = new ComboParameter<>("Filter rows", "Limit the exported rows to those with MS/MS data (or annotated rows)", FeatureListRowsFilte
Oh, apologies, something went wrong. I resetted the settings and applied it, now it worked.

2023-01-27 11:23 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +// https://github.com/OpenMS/OpenMS/blob/7a2e4a41d4c9f511306afcb8bb4f1b773ace9b9a/share/OpenMS/SCHEMAS/FeatureXML_1_9.xsd
Thank you, changed it

2023-01-27 11:23 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +                BufferedWriter writer = Files.newBufferedWriter(curFile.toPath(), StandardCharsets.UTF_8);
Thank you, my Java skills are a bit rusty, changed it accordingly

2023-01-27 11:24 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        double meanMZ = 0.;
Thank you, moved it to the loop

2023-01-27 11:24 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        this.generateElement(xmlWriter, "featureMap", new String[]{"version", "1.4", "id", "fm_16311276685788915066", "xsi:noNamespaceSchemaLocation", "http://open-ms.sourceforge.net/schemas/FeatureX
Thank you, did that

2023-01-27 11:24 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +        this.generateEmptyElement(xmlWriter, "software", new String[]{"name", "MzMine3", "version", MZmineCore.getMZmineVersion().toString()});
Thank you, changed it accordingly

2023-01-27 11:24 UTC, christophuv commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +    }
Thank you, indeed, removed it

2023-01-27 11:25 UTC, christophuv commented
Thank you for the feedback, great suggestions, I incorporated them in the code

2023-01-30 08:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_featureML/FeatureMLExportModularTask.java
> +                BufferedWriter writer = Files.newBufferedWriter(curFile.toPath(), StandardCharsets.UTF_8);
No worries you will find this also throughout the codebase... I guess mzmine started with Java 5 or 6 .... so there is a lot of legacy things in here. 
And Java got so much nicer in java 8 and also since then.

2023-01-30 12:24 UTC, christophuv commented
Thanks for code and the multiples files error message

2023-01-30 17:38 UTC, robinschmid approved these changes
All done, can be merged

2023-01-30 17:38 UTC, merged

2023-01-30 17:40 UTC, christophuv commented
Great, thanks for your help!