Change to MinimumSamplesParameter with absolute and relative
mzmine/mzmine3 pull request #1114
Opened 2023-02-01 14:49 UTC by robinschmid

<img width="291" alt="image" src="https://user-images.githubusercontent.com/10366914/216075976-f229b22b-dcf2-4835-a9c0-12138dadd3c4.png">
<img width="335" alt="image" src="https://user-images.githubusercontent.com/10366914/216076065-a09d09da-a134-4ddd-a639-9594c7b20852.png">

2023-02-01 15:41 UTC, SteffenHeu requested changes
Use your own functionality :D

2023-02-01 15:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_rowsfilter/RowsFilterParameters.java
>  public class RowsFilterParameters extends SimpleParameterSet {
increment parameter set version!

2023-02-01 15:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/parametertypes/MinimumFeaturesFilterParameters.java
>  public class MinimumFeaturesFilterParameters extends SimpleParameterSet {
increment version

2023-02-02 14:37 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/parametertypes/MinimumFeaturesFilterParameters.java
>  public class MinimumFeaturesFilterParameters extends SimpleParameterSet {
But then we also need to change the message. Currently old MZMine users will not see that the version  has changed because their batch did not track

2023-02-02 14:37 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/parametertypes/MinimumFeaturesFilterParameters.java
>  public class MinimumFeaturesFilterParameters extends SimpleParameterSet {
will do

2023-02-02 15:06 UTC, robinschmid commented
all done

2023-02-02 15:42 UTC, SteffenHeu approved these changes

2023-02-02 15:42 UTC, merged