New module for CompoundAnnotationsCSVExportTask
mzmine/mzmine3 pull request #1213
Opened 2023-03-05 21:04 UTC by shamlymhd

I hope to commit changes to this branch. The changes will create a new feature for exporting CompoundAnnotations into a CSV (comma-separated values) file.

2023-03-07 15:24 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +public class CompoundAnnotationsCSVExportTask extends AbstractTask implements ProcessedItemsCounter {
we can remove the ProcessedItemsCounter it was quite specific where we used it.

2023-03-07 15:30 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +    public void run() {
need to add logic here see issue for some details on how to get the annotations to export

2023-03-07 15:30 UTC, robinschmid commented
added some comments. The start is correct

2023-03-07 16:52 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +public class CompoundAnnotationsCSVExportTask extends AbstractTask implements ProcessedItemsCounter {
Got it 👍

2023-03-07 17:04 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +    public void run() {
yeah, I thought the same. Thanks 😊

2023-03-09 18:47 UTC, shamlymhd commented
After annotating the compounds, new columns will be added to the feature list table. is this task to export these columns to a CSV file?

2023-03-12 08:20 UTC, robinschmid commented
Exactly. 
The data is already added to the ModularFeatureListRow which is collected in a FeatureList.

2023-03-12 08:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +                    if (object instanceof FeatureAnnotation annotation) {
perfect

2023-03-12 08:25 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +                        Float getScore = annotation.getScore();
this one has a convenience method annotation.getScoreString

2023-03-12 08:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +                        Float getScore = annotation.getScore();
try something like this:
`Stream.of(a,b,c,d).map(o -> ... null should be empty string and otherwise o.toString()  then map with CSVUtils.escape to handle values that contain the separator ,  then use collect join ","` 

this way you do one stream and end up with a joined string where each field is null checked and escaped.
So a value 1,000 would be wraped in "1,000" to escape the ,

2023-03-14 15:38 UTC, robinschmid requested changes

2023-03-15 07:39 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +                        Float getScore = annotation.getScore();
resolved

2023-03-15 07:39 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +                        Float getScore = annotation.getScore();
yeah got it thank you

2023-03-15 17:10 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +            for (FeatureListRow row : featureList.getRows()) {
done thank you

2023-03-15 17:12 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +//        }
I cleaned the comments, and I did what you suggested before. please review

2023-03-19 18:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +            writer.close();
no need to close the writer as its opened in a try with ressoruces block.

2023-03-19 18:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +        return 0;
lets track the progress. 
Add a variable in the totalRows and calculate it by going through the featureLists.stream :: getNumberOfRows . sum
Then just increment another int finishedRows

2023-03-19 18:57 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/io/CSVUtils.java
> +  public static String escape(String value) {
why do you need this? and not just the method above where also the separator is escaped

2023-03-19 18:57 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/TableFormat.java
> +public enum TableFormat {
this class can be deleted its a copy from somewhere

2023-03-19 18:58 UTC, robinschmid approved these changes
Thanks for the commitment. 
We are close to finishing this one. Only a few comments

2023-03-20 03:21 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +            writer.close();
yeah got it thanks.

2023-03-20 07:20 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/CompoundAnnotationsCSVExportTask.java
> +        return 0;
Resolved

2023-03-20 07:44 UTC, shamlymhd commented on src/main/java/io/github/mzmine/util/io/CSVUtils.java
> +  public static String escape(String value) {
compoundName, adductType, scoreType, precursorMZ, mobility, getCCS, and getRT, with any commas within these values properly escaped using CSVUtils.escape() method. it is important, right?

2023-03-20 07:44 UTC, shamlymhd commented on src/main/java/io/github/mzmine/modules/io/export_compoundAnnotations_csv/TableFormat.java
> +public enum TableFormat {
As a second point regarding the issue, you mentioned 'long table format, one row in CSV per annotation.' Therefore, I thought about creating a class and using it (copied from another module). However, it did not turn out to be useful. Thank you so much for your time and guidance.

2023-03-20 12:06 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/io/CSVUtils.java
> +  public static String escape(String value) {
There is a method above that has a similar signature:
CSVUtils.escape(value, separator) it takes care of different separators

2023-03-21 00:50 UTC, shamlymhd commented on src/main/java/io/github/mzmine/util/io/CSVUtils.java
> +  public static String escape(String value) {
Done. thank you.

2023-04-17 19:27 UTC, merged