Add CLI argument to change files easily
mzmine/mzmine3 pull request #1336
Opened 2023-05-11 10:09 UTC by robinschmid

Added arguments i: input to change the input files in batch files easily. It just replaces all the files in the AllSpectralDataImportModule.

Either provide a txt file with paths or use glob patterns
'''
-b D:\Data\batch\test.xml -i D:\Data\input_files.txt
-b D:\Data\batch\test.xml -i D:\Data\*.mzML
'''

2023-05-11 14:07 UTC, SteffenHeu requested changes
looks good, but some comments

2023-05-11 14:07 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/main/MZmineArgumentParser.java
> +          overrideDataFiles = FileAndPathUtil.parseFileInputArgument(sinput);
maybe only do this if it's headless mode?

2023-05-11 14:07 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/main/MZmineArgumentParser.java
> +  public File[] getOverrideDataFiles() {
Nullable

2023-05-11 14:07 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/batchmode/BatchModeModule.java
> +        if (!newQueue.setImportFiles(overrideDataFiles)) {
the method never returns false but throws an exception instead, so the code below is never reached.

2023-05-11 14:07 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/batchmode/BatchQueue.java
> +  public boolean setImportFiles(final File[] allFiles) {
does not return false but throws an exception. Refactor to do one of the two.

2023-05-14 15:17 UTC, robinschmid commented on src/main/java/io/github/mzmine/main/MZmineArgumentParser.java
> +        "input files. Either defined in a .txt text file with one file per line or ");
Changed to
```
 Option input = new Option("i", "input", true,
        """
    input data files. Either defined in a .txt text file with one file per line
    or by glob pattern matching. To match all .mzML files in a path: -i "D:\\Data\\*.mzML"
    """);
```

2023-05-14 15:28 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/batchmode/BatchQueue.java
> +  public boolean setImportFiles(final File[] allFiles) {
returns false now. Logging was improved and jdocs as well

2023-05-14 15:28 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/batchmode/BatchModeModule.java
> +        if (!newQueue.setImportFiles(overrideDataFiles)) {
returns false now. Logging was improved and jdocs as well

2023-05-19 10:53 UTC, SteffenHeu approved these changes

2023-05-19 10:53 UTC, SteffenHeu commented
looks good, thanks

2023-05-19 10:53 UTC, merged