Precursor Purity checker module
mzmine/mzmine3 pull request #1342
Opened 2023-05-20 17:38 UTC by robinschmid

Pushed all code for purity check in module and added a module for this.
Also needed by Daniel

2023-05-22 09:42 UTC, SteffenHeu requested changes

2023-05-22 09:42 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/PrecursorPurityType.java
> +  public boolean getDefaultVisibility() {
i dont think this should be visible by default. The default view should be simple and straightforward and include values that most users know what they are

2023-05-22 09:42 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/SimpleStatisticsType.java
> +public abstract class SimpleStatisticsType extends NumberType<SimpleStatistics> implements
Why is this a number type? Looks more like a listwithsubstype to me. I thought numbers had a simple 1-number representation. Also, i dont see a load + save method for projects here ;)

2023-05-22 09:42 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/PrecursorPurityType.java
> +public class PrecursorPurityType extends SimpleStatisticsType {
Also no load/save method

2023-05-23 10:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/PrecursorPurityType.java
> +  public boolean getDefaultVisibility() {
Special column that is only there if people use the module

2023-05-23 11:47 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataanalysis/spec_chimeric_precursor/ChimericPrecursorChecker.java
> +  public static ChimericPrecursorResults checkMs1(final MassList ms1, final double precursorMz,
Good question. 
Something like this should be added later...

2023-05-23 11:49 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/PrecursorPurityType.java
> +public class PrecursorPurityType extends SimpleStatisticsType {
Added load/save
pushed most of it into SubColumnFactory so that it can be reused.
We load into a SimpleModularDataModel object and can then just use the datatypes to move all data into their final objects.

2023-05-23 11:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/SimpleStatisticsType.java
> +public abstract class SimpleStatisticsType extends NumberType<SimpleStatistics> implements
Did not want to go List type here. I don't want to store one value for each scan here but rather the stats. 
Its a number type because most columns need a numberformat and all need the same.

2023-05-23 11:51 UTC, robinschmid commented
I added 
- tests
- load save

2023-05-23 16:05 UTC, robinschmid commented
All done

2023-05-24 08:10 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataanalysis/spec_chimeric_precursor/HandleChimericMsMsParameters.java
> +    super(mainMassWindow, isolationWindow, minimumPrecursorPurity, option);
update parameter set version

2023-05-25 10:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/ClassificationType.java
> +    return "class";
changed to classification

2023-05-25 10:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureListRow.java
> -  public <T> boolean set(Class<? extends DataType<T>> tclass, T value) {
Its now in the parent class of ModularDataModel. 
the default implementation does exactly this now

2023-05-25 10:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/ClassificationType.java
> +public class ClassificationType extends StringType {
done

2023-05-30 08:25 UTC, merged