Add speclib name
mzmine/mzmine3 pull request #1447
Opened 2023-07-31 15:16 UTC by SteffenHeu

2023-08-01 11:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/spectraldb/entry/SpectralDBEntry.java
> +    MZmineCore.getProjectManager().getCurrentProject().getCurrentSpectralLibraries();
why get without using it as a var

2023-08-01 11:58 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/spectraldb/entry/SpectralDBEntry.java
> +      entry.setLibrary(library);
maybe use the constructor with library. Can library field be final then?

2023-08-01 12:01 UTC, robinschmid requested changes
Just few comments.

2023-08-02 11:30 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/spectraldb/entry/SpectralDBEntry.java
> +      entry.setLibrary(library);
the library is set when library.addEntry is called. Otherwise all library parsers need to be adapted.

2023-08-02 15:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/spectraldb/entry/SpectralDBEntry.java
> +      entry.setLibrary(library);
ok

2023-08-02 15:35 UTC, merged