Pregenerate charts javafx 20
mzmine/mzmine3 pull request #1452
Opened 2023-08-04 15:50 UTC by SteffenHeu

Behold, we may have a solution for the feature table charts and may be able to update to java fx 20!

Changes:
- cell factory only creates a placeholder
- charts are generated off the java fx thread
- set to the feature table all at once

Caution:
- don't merge yet, this is not the ideal solution yet, pregenerating all the charts requires more memory than before.

TODOs:
- only pregenerate charts for visible colums
- add option to only generate charts when visible. use a single thread for that
- stop chart generation when feature table is closed

please test @tomas-pluskal @Annexhc @robinschmid on mac, linux and windows.

2023-08-06 15:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/graphicalnodes/FeatureShapeMobilogramChart.java
> +      System.out.println("Exception for row " + row.getID());
logger, maybe comment when this happens?

2023-08-06 16:03 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/tasks/NodeGenerationThread.java
> +  private int rows = 0;
finishedRows?

2023-08-06 16:41 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/fx/DataTypeCellFactory.java
> +          if(!getTableRow().isVisible()) {
Sometimes on my laptop, windows, some rows are completely empty. But this is fixed once scrolled it seems

2023-08-06 16:41 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/graphicalnodes/FeatureShapeMobilogramChart.java
> +      System.out.println("Exception for row " + row.getID());
Ok found that somehow some listeners in jfreechart trigger some repaint in FX and then fail. 
Not sure why

2023-08-06 16:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/LinkedGraphicalType.java
> +  public abstract Class<? extends Node> getNodeClass();
needed?

2023-08-06 16:52 UTC, robinschmid reviewed
A few things I noted. There are weird exceptions triggered by some listeners in jfreechart that trigger javafx repaint:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.util.NoSuchElementException
	at java.base/java.util.LinkedList.removeFirst(LinkedList.java:274)
	at java.base/java.util.LinkedList.pop(LinkedList.java:805)
	at javafx.scene.canvas.GraphicsContext.restore(GraphicsContext.java:935)
	at org.jfree.chart.fx.ChartCanvas.draw(ChartCanvas.java:510)
	at org.jfree.chart.fx.ChartCanvas.chartChanged(ChartCanvas.java:702)
	at org.jfree.chart.JFreeChart.notifyListeners(JFreeChart.java:1428)
	at org.jfree.chart.JFreeChart.fireChartChanged(JFreeChart.java:1414)
	at io.github.mzmine.gui.chartbasics.gui.javafx.EChartViewer.fireChangeEvent(EChartViewer.java:582)
	at io.github.mzmine.gui.chartbasics.gui.javafx.EChartViewer.lambda$applyWithNotifyChanges$7(EChartViewer.java:616)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1623) 
```

2023-08-06 16:54 UTC, robinschmid reviewed
Also, how about adding an IntegerProperty that hold info on the number of open FeatureTableFx instance of the feature table. 
Then a listener could automatically clean up the buffered charts - or create the task to generate the graphical cells

2023-08-06 16:55 UTC, robinschmid requested changes
Currently the network view deletes the shown charts/rows once it is closed. They are missing then in the original table.

Also if a table is checked and I jump from table to table, the charts are not generated

2023-08-24 13:43 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/annotations/LipidSpectrumType.java
> +    var chart = new LipidSpectrumChart(matchedLipids.get(0), progress, RunOption.THIS_THREAD);
I guess this is safe as we only run it on the generator task?

2023-08-29 07:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/tasks/NodeGenerationThread.java
> +          throw new RuntimeException(e);
maybe just kill the task if its interrupted?
setError... 
setStatus...

2023-08-29 07:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/tasks/NodeGenerationThread.java
> +/*  private boolean generateAllCharts() {
Remove comments

2023-08-29 07:43 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/DetectionType.java
> +  }
We have to make a clear destinction between 
getCellNode and createCellContent. 
Here the second is empty. 

At least for this class one could even think about just creating a different cellFactory. Maybe that could be a method that is usually implemented in DataType, then in GraphicalDataType, and then here differently.
Circles could be reused.

2023-08-29 07:45 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/FeatureShapeType.java
> +    /*StackPane node = (StackPane) row.getBufferedColChart(getHeaderString());
remove comment

2023-08-29 07:46 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/ImageType.java
> +//    StackPane node = (StackPane) row.getBufferedColChart(getHeaderString());
remove comment

2023-08-29 07:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableTab.java
> +    //final NodeGenerationThread nodeGenerationThread = new NodeGenerationThread(null, Instant.now(),
remove comment

2023-08-29 07:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +  private final Map<String, Node> bufferedCharts = new HashMap<>();
Add javadoc to describe the String key and when this is created and cleared

2023-08-29 07:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +    }
What if multiple feature lists are open?
Could have an IntegerProperty to store the number of active tables

2023-08-29 08:05 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +    }
I don'T see the point of that, since the thread is started/ended on demand now.

2023-08-30 07:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +    }
It was about the cache being cleared at the end of this method. So if we open the feature network overview and close it it may remove the cache

2023-08-30 08:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +    }
Hasn't been an issue really, cause the generation is so fast now. I feel like we might introduce more bugs by trying to be super efficient here.

2023-12-20 15:20 UTC, closed without merging