extension of the DatabaseIsotopeRefiner
mzmine/mzmine3 pull request #1507
Opened 2023-09-28 11:02 UTC by Sonja-analytik

with "refineAnnotationsByIsotopesDifferentResolutions" based on the IsotopePatternFinder:

- Calculation of isotope patterns at different resolutions
- comparison of these with the found isotope pattern
- highest isotope pattern score is output

2023-09-28 14:04 UTC, SteffenHeu requested changes

2023-09-28 14:04 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/tools/isotopeprediction/IsotopePatternCalculator.java
> +  public static HashMap <Double, IsotopePattern> calculateIsotopePatternForResolutions(IMolecularFormula cdkFormula,
This looks mostly like a copied method with another loop in it. Replace the copied code with a call to the original method for pattern calculation and just store the resulting pattern in the map. makes it easier to maintain in the end.

2023-10-03 12:46 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/DatabaseIsotopeRefinerScanBased.java
> +    refineAnnotationsByIsotopesDifferentResolutions(row, mzTolerance, minIntensity, minIsotopeScore, new HashMap<>());
seems like here you want to call refineAnnotationByIsotopes not DifferentResolution

2023-10-03 12:51 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/DatabaseIsotopeRefinerScanBased.java
> +          var score = calculateIsotopeScoreDifferentResolutions(annotation, measuredIsotopes, minIntensity,
Maybe we should save this score somehow in the final annotation so that we can reuse it?

2023-10-03 12:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/DatabaseIsotopeRefinerScanBased.java
> +    return new double[]{0.0001,0.001,0.01,0.1};
we can finalize those later but maybe the smallest shoudl be something like 0.00025 or a bit higher?
would be interesting to know what you need to separate N O C S ...

2023-10-03 12:57 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/DatabaseIsotopeRefinerScanBased.java
> +    return new MZTolerance(doubleResolution, tolerancePPM);
maybe we can strip this out and directly have a global final MZTolerance[] with all tolerances just as the absolute values (now found in the getDoubleResolutions method).  
The ppm can just be 0 to only rely on absolute tolerance.

2023-10-03 12:58 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/DatabaseIsotopeRefinerScanBased.java
> +    return new double[]{0.0001,0.001,0.01,0.1};
see comment below. Maybe just creating a global MZtolerance[] might be best

2023-10-03 13:02 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_localcsvsearch/DatabaseIsotopeRefinerScanBased.java
> +            getDoubleResolutions(), adductType.getCharge(), adductType.getPolarity(), false));
This should be done outside of the loop. Is only done once.
Also you can write `var predictedIsotopePatterns = ionIsotopePatterMap.computeIfAbsent(...);`

2024-01-07 11:33 UTC, robinschmid commented
looks good to me

2024-01-07 15:02 UTC, merged