Kendrick plot fix
mzmine/mzmine3 pull request #1516
Opened 2023-10-17 19:47 UTC by kyrasolaris01

Some fixes to the Kendrick plot module. Simplified the code and now works in dark mode.

![image](https://github.com/mzmine/mzmine3/assets/140096361/1be73e94-7e2a-40ff-bc51-547f56549efb)

![image](https://github.com/mzmine/mzmine3/assets/140096361/bc31938c-8e8f-45d7-8b80-787ca63d540d)

2023-10-23 12:31 UTC, SteffenHeu requested changes
The architecture is kind of weird in my opinion. You need the chart and the legend to be created outside the tab. I would like it more if the module created the tab with the parameters and the tab then created a KendrickPane which contains all the information. And ideally the KendrickPane launches tasks to compute the datasets. So you can create a Pane/Tab without manually creating the charts first.

2023-11-10 13:07 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotChart.java
> +    newLegend.setSubdivisionCount(500);
It ensures a nice gradient without any borders. I copy pasted this from SimpleXYZScatterPlot

2023-11-10 13:09 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotChart.java
> +    newLegend.setAxisLocation(AxisLocation.BOTTOM_OR_LEFT);
No, we use BOTTOM_OR_LEFT, but putting the legend on the right side of the plot is not important. I will put it on the right using: newLegend.setPosition(RectangleEdge.RIGHT);

2023-11-11 10:14 UTC, kyrasolaris01 commented
Changed architecture as requested and made small changes as suggested.

2023-12-14 18:13 UTC, ansgarkorf commented
@SteffenHeu can we merge?

2023-12-15 15:58 UTC, SteffenHeu reviewed
I think the dataset is not calculated on another thread, but on the fx thread. 
This might lead to freezers or so, i think calculating the dataset in another thread is a better solution. Then the dataset should be changed when a parameter is changed

2023-12-15 15:58 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotModule.java
> +      MZmineCore.getDesktop().addTab(newTab);
the add tab call does not need to be in runLater, it's done implicitly. Does the creation need to be on the fx thread?

2023-12-15 15:58 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotAnchorPaneController.java
> +        parameters, 1, 1);
The dataset does not create a thread to calculate the data, does it? It calcs the data on change/when it is created. This will lead to calculation on the FX thread, or?

2023-12-16 18:46 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotModule.java
> +      MZmineCore.getDesktop().addTab(newTab);
done

2023-12-16 18:46 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotAnchorPaneController.java
> +        parameters, 1, 1);
now it does create its own thread

2023-12-20 12:32 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotXYZDataset.java
> +    return colorScaleValues[item];
What happens if this is called before the run method is finished? maybe check for the status here and in the other getters?

2023-12-20 12:32 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotAnchorPaneController.java
> +        newDataset.run();
calling the run method here does not run it on a separate thread. you have to add the task to the task controller. probably you need to add a status listener here and update the plot once the calculation is finished (status changed to finished).

2023-12-20 13:47 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotAnchorPaneController.java
> +            KendrickMassPlotParameters.xAxisValues).getValue()
use directly parameters.getValue()

2023-12-20 14:56 UTC, SteffenHeu approved these changes
looks good to me now 👍

2023-12-20 14:59 UTC, merged