Fix imaging batch wizard
mzmine/mzmine3 pull request #1537
Opened 2023-11-18 20:56 UTC by kyrasolaris01

Updated imaging features:
- Settings menu for imaging raw data view
- Added paint scale transformation  
![image](https://github.com/mzmine/mzmine3/assets/140096361/e61917e7-9ad9-41ae-a7c7-aab7b6d61497)

- Added new module to colocate images
- Added visualizer for co-localization results
![Uploading image.png…]()

Updated wizard

2023-12-19 09:02 UTC, robinschmid commented
depends on #1506 to merge first

2023-12-21 08:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  private final List<Double> similarities = new ArrayList<>();
fastutil DoubleList uses primitive doubles and saves memory and may be faster. 
also easier to stream later

2023-12-21 08:17 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  public synchronized void addSimilarity(Double sim) {
really Double? can it be null?
otherwise double primitive.

2023-12-21 08:18 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  private final List<Double> similarities = new ArrayList<>();
maybe add some javadoc what similarities hold - like what values are in here

2023-12-21 08:18 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +    return similarities.stream().mapToDouble(Double::doubleValue).max().orElse(0);
fastutil DoubleList.stream gives you a doubleStream primitive

2023-12-21 08:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +      <MenuItem text="Image co-localization" onAction="#runModule"
Image co-localization grouping (vielleicht um zu sagen dass es was aehnliches ist zu correlation grouping)

2023-12-21 08:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +        }
why only set it true?
If its an imaging dataset FeatureShapeType should be false...

2023-12-21 08:29 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +    }
This could be a method in FeatureListUtils.sortDefault(newFeatureList)
And then just check again if its an imaging feature list. 
Sort by RT only if not imaging AND if it contains RT

2023-12-21 08:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ColocatedImagePane.java
> +  public static Color MIN_COS_COLOR = Color.web("0xE30B0B");
are those supposed to be final? or why uppercase.

why not use the default negative and positive colors from the presets? like in the SpectralLibraryMatch results

2023-12-21 08:36 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ColocatedImagePane.java
> +  public static final double MIN_COS_COLOR_VALUE = 0.7;
better 0.5 which is still correlated

2023-12-21 08:51 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  private final List<Double> similarities = new ArrayList<>();
Shall I also change this in R2RSpectralSimilarityList?

2023-12-21 08:53 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +      <MenuItem text="Image co-localization" onAction="#runModule"
sounds good

2023-12-21 09:40 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  private final List<Double> similarities = new ArrayList<>();
done

2023-12-21 09:40 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  public synchronized void addSimilarity(Double sim) {
done

2023-12-21 09:40 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  private final List<Double> similarities = new ArrayList<>();
done

2023-12-21 09:40 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +    return similarities.stream().mapToDouble(Double::doubleValue).max().orElse(0);
done

2023-12-21 09:41 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +      <MenuItem text="Image co-localization" onAction="#runModule"
done

2023-12-21 09:44 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ColocatedImagePane.java
> +  public static final double MIN_COS_COLOR_VALUE = 0.7;
done

2023-12-21 09:44 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ColocatedImagePane.java
> +  public static Color MIN_COS_COLOR = Color.web("0xE30B0B");
done

2023-12-27 12:02 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +        }
Why should FeatureShapeType be set if it is an imaging dataset? 
newRow.set(FeatureShareType.class, false) would result in an empty plots in the feature table

2023-12-27 12:27 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +    }
Whats the best way to check if the feature list contains RT?

2023-12-29 15:38 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2RImageSimilarityList.java
> +  private final List<Double> similarities = new ArrayList<>();
great

2023-12-29 15:44 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +        }
We typically set it to false to not show the shape. The feature shape may be there if time is set

2023-12-29 15:46 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +    }
hard to say. Time is often set... so maybe checking the raw data files makes sense

2023-12-31 09:57 UTC, ansgarkorf commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +        }
As I set, for me it does not make sense to set the shape type for imaging at all. If you do it like you propose, you end up with a column with "Preparing content..." messages. 
Will keep it as it is

2023-12-31 10:59 UTC, kyrasolaris01 commented
@robinschmid if you are fine with not setting the ShapeType for imaging datasets this can be merged

2024-01-04 16:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ColocatedImagePane.java
> +        if (i > 100) {
even 100 is a lot. We could use FlowLess

https://github.com/FXMisc/Flowless/issues/118

2024-01-04 16:18 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ImageCorrelateGroupingModule.java
> +    ModularFeatureList[] featureLists = parameters.getParameter(
can use parameter.getValue directly

2024-01-04 16:25 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ImageCorrelateGroupingParameters.java
> +  public static final PercentParameter MIN_R = new PercentParameter("Min image correlation",
Min image Pearson r

2024-01-04 16:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ImageCorrelateGroupingTask.java
> +      hotspotRemovalThreshold = parameters.getParameter(
there is the new parameters.getEmbeddedParameterValueIfSelectedOrElse()
You could just pass in a default value -1 and then check it when you apply

2024-01-04 16:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/tools/batchwizard/subparameters/WorkflowImagingWizardParameters.java
> +      """, true);
those options are all used within correlation and only there right?
Maybe reduce the number of param,eters here and just use some good defaults.

2024-01-04 16:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +              && selectedFeature.getRawDataFile() instanceof ImagingRawDataFile);
check this before doing anything to short circuit

2024-01-04 16:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +                correlatedRows.put(row, rowsRelationshipR2RMap.get(selectedRow, row).getScore());
just return true at this point. no need to collect all info

2024-01-04 16:38 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    Collections.reverse(entryList);
This should be reduced to
```java
correlatedRows.entrySet().stream().sorted(Map.Entry.comparingByValue().reversed()).toList()
```

2024-01-04 16:40 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +      if (rowsRelationshipR2RMap != null && row != selectedRow
rowsRelationshipR2RMap != null should be tested before and you should just return exit the method

2024-01-04 16:41 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    R2RMap<RowsRelationship> rowsRelationshipR2RMap = Objects.requireNonNull(
should never be null if the test before was done right and nothiung changed in between...
But maybe you just get the map and test for null and return if null

2024-01-04 16:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +          && rowsRelationshipR2RMap.get(selectedRow, row) != null) {
introduce a variable for this. you are calling get 3 times

2024-01-04 16:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    Map<FeatureListRow, Double> correlatedRows = new HashMap<>();
Just use List<RowsRelationship> as it contains everything you need: score, rowA and rowB ...

You can add a method to RowsRelationship to get the other row:

```java
default FeatureListRow getOtherRow(FeatureListRow row) {
  var rowA = getRowA();
  return Objects.equals(rowA, row)? getRowB() : rowA;
}
```

2024-01-04 17:00 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    SplitPane splitPaneH = new SplitPane();
All below this should be in the visualizer pane class... 
The pane class could also implement the new FeatureRowPane classes

2024-01-04 17:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/image/ImageVisualizerTab.java
> +      }
just do parameterSetupPane.getComponentForParameter(SOME PARAMETER)

2024-01-04 17:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/image/ImageVisualizerTab.java
> +    }
its not clear to me what this does or is supposed to do. 
gridPane.clear?

2024-01-04 17:24 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/image/ImageVisualizerTab.java
> +    setData(features);
change the whole class into an AbstractFeatureListRowsPane

2024-01-04 17:34 UTC, robinschmid requested changes
Got some comments. Overall it looks great. 

The gridpane may be changed later to something with VirualFlow

2024-01-08 12:53 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_imagecorrelate/ImageCorrelateGroupingModule.java
> +    ModularFeatureList[] featureLists = parameters.getParameter(
done

2024-01-11 09:14 UTC, merged