Van krevelen diagram fix
mzmine/mzmine3 pull request #1556
Opened 2023-12-09 18:58 UTC by kyrasolaris01

This fixes the Van Krevelen Diagram visualization.

It now uses annotations from the modular data types instead of the deprecated getPreferredFeatureIdentity() method.

2023-12-19 09:03 UTC, robinschmid commented
Depends on #1516 to be merged first and this to be adapted

2023-12-21 09:53 UTC, kyrasolaris01 commented
done, @robinschmid  @SteffenHeu, ready for review

2024-01-04 13:53 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/chartutils/XYCirclePixelSizeRenderer.java
> +      z = ((XYZBubbleDataset) dataset).getZValue(series, item);
just use instanceof pattern matching   x instanceof MyClass bubble) that defines the var in one line

2024-01-04 14:03 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotXYZDataset.java
> +      if (selectedRows[i].getBestFeature().getFWHM() != null) {
getBestFeature is not for free... 
I would precompute and create an array of features from getBestFeature in the constructor and then use them here in all those methods.

2024-01-04 14:06 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotXYZDataset.java
> +  public Number getBubbleSize(int series, int item) {
why is this a number? just using the other method should suffice right?

2024-01-04 14:06 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotXYZDataset.java
> +  public Number getBubbleSize(int series, int item) {
also in the parent class... maybe remove this

2024-01-04 14:07 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramAnchorPane.fxml
> +                       prefHeight="160.0" prefWidth="100.0">
often its okay to not provide any widths and heights and just rely on the auto scaling

2024-01-04 14:09 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +      case M_OVER_Z -> {
just MZ

2024-01-04 14:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +    switch (bubbleVanKrevelenDiagramDataTypes) {
best is to just do 
return switch...
or var ... = switch.
then you can just inline all the cases. No need for {} and return in each case.

2024-01-04 14:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +    Text valueType = new Text(vanKrevelenDiagramXYZDataset.getBubbleVanKrevelenDataType().getName());
Just a general thing for the VanKrevelenDiagramDataTypes. 
You could just use the DataType classes directly - then you can use the header name that we always use and the data format that is also used in other places. 

See my PR that adds a function for DataTypes.getAll to get a list of datatypes but you can also use them individually.

2024-01-04 14:38 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramDataTypes.java
> +public enum VanKrevelenDiagramDataTypes {
See my comment from above you could just use a list of DataType instead and use their headers etc. 
If you need to extend them you could either have some function to map data type to an abbreviated form but not sure if thats needed.

2024-01-04 14:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +        .filter(featureListRow -> featureListRow.getPreferredAnnotation() != null).toList();
can be one line
featureList.stream().filter...toList

2024-01-04 15:01 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +    for (int i = 0; i < annotations.size(); i++) {
More concise and descriptive
```java
for(var row : filteredRows) {
var annotation = row.getPreferredAnnotation();
IMolecularFormula formula = getFormula(annotation)
```

2024-01-04 15:02 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +          }
redundant. just get the formula and then calculate once.

2024-01-04 15:06 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +      if (filteredRows.get(i).getBestFeature().getFWHM() != null) {
I feel like I have seen this before... 
bestFeature should be precalculated in the constructor or so

2024-01-04 15:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +    }
why would I want to return 0 when the task is done?

2024-01-04 15:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +    }
general comment. better use
```java
return isFinished()? xValues.length : 0;
```

2024-01-04 15:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +class VanKrevelenDiagramXYZDataset extends AbstractXYZDataset implements Task, XYZBubbleDataset {
I guess you copied Task from another dataset?
Maybe it would be easier in the future to just add the task as a variable?

2024-01-04 15:20 UTC, robinschmid requested changes
On a good way. Added sme comments

2024-01-04 19:15 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramAnchorPane.fxml
> +                       prefHeight="160.0" prefWidth="100.0">
true, but setting pref. height and width has no side effects

2024-01-04 19:16 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +      case M_OVER_Z -> {
a question of taste

2024-01-04 19:17 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +    switch (bubbleVanKrevelenDiagramDataTypes) {
I like the old school way, not sure why...

2024-01-04 19:18 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +    Text valueType = new Text(vanKrevelenDiagramXYZDataset.getBubbleVanKrevelenDataType().getName());
good suggestion, lets implement that later in another PR, once your PR is merged

2024-01-04 19:19 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramDataTypes.java
> +public enum VanKrevelenDiagramDataTypes {
good suggestion, lets implement that later in another PR, once your PR is merged

2024-01-05 07:15 UTC, ansgarkorf commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +    Text valueType = new Text(vanKrevelenDiagramXYZDataset.getBubbleVanKrevelenDataType().getName());
I created an issue: #1579

2024-01-05 07:15 UTC, ansgarkorf commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramDataTypes.java
> +public enum VanKrevelenDiagramDataTypes {
see #1579

2024-01-05 08:29 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +      case M_OVER_Z -> {
we always use mz

2024-01-07 08:51 UTC, ansgarkorf commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +        .filter(featureListRow -> featureListRow.getPreferredAnnotation() != null).toList();
done

2024-01-07 09:27 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +          }
done

2024-01-07 09:33 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +      case M_OVER_Z -> {
done

2024-01-07 09:36 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +    switch (vanKrevelenDiagramDataType) {
done

2024-01-07 09:43 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +    }
done

2024-01-07 09:53 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotXYZDataset.java
> +      if (selectedRows[i].getBestFeature().getFWHM() != null) {
refactored, will only loop once through all features now

2024-01-07 09:54 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramXYZDataset.java
> +      if (filteredRows.get(i).getBestFeature().getFWHM() != null) {
refactored, will only loop once through all features now

2024-01-07 10:08 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramTab.java
>  public class VanKrevelenDiagramTab extends MZmineTab {
Good catch, no it shouldnt change when selecting another feature list, because selected parameters may cause weird plots, I removed the binding and switched to SimpleTab. Also, so far the new classes make no sense here, because selected feature rows are not highlighted in any way, however, something nice for the future. I will create an issue.

2024-01-07 10:08 UTC, kyrasolaris01 commented
@robinschmid all done ready for merge

2024-01-07 10:45 UTC, ansgarkorf commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramTab.java
>  public class VanKrevelenDiagramTab extends MZmineTab {
see #1586

2024-01-07 15:33 UTC, kyrasolaris01 commented on src/main/java/io/github/mzmine/modules/visualization/vankrevelendiagram/VanKrevelenDiagramBubbleLegend.java
> +    switch (bubbleVanKrevelenDiagramDataTypes) {
done

2024-01-07 15:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotXYZDataset.java
> +        switch (kendrickPlotDataType) {
remove if and reduce to one switch statement without default branch.

2024-01-07 16:14 UTC, merged