Simplify metacorr data usage
mzmine/mzmine3 pull request #1590
Opened 2024-01-08 15:38 UTC by robinschmid

2024-01-08 19:51 UTC, SteffenHeu requested changes

2024-01-08 19:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/RowGroupFull.java
> +public class RowGroupFull implements RowGroup {
javadoc?

2024-01-08 19:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/RowGroupFull.java
> +  public synchronized boolean add(FeatureListRow e) {
i dont see any sorting oin this method. also no sorting after the row was added

2024-01-08 19:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/RowGroupFull.java
> +  protected final List<RawDataFile> raw;
why not point to the feature list and get the raws from there?

2024-01-08 19:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/correlation/RowGroupSimple.java
> +public class RowGroupSimple implements RowGroup {
SimpleRowGroup? 
Why is it in a different package than RowGroup and RowGroupFull? 
I get that implementations dont have to be in the package where the interface is, but then again, rowgroupfull is there.
move all to the correlation package?

2024-01-08 19:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_metacorrelate/corrgrouping/AdvancedCorrelateGroupingParameters.java
> +      This information is only needed in some visualization modules.""", true);
some visualisation modules doesnt tell the user anything. Which ones? are they frequently used?
I'd turn the parameter around and say "store extended correlation data"

2024-01-08 19:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_metacorrelate/corrgrouping/AdvancedCorrelateGroupingParameters.java
> +      This will skip the feature overlap function """, 250);
I cannot find any parameter that is called 'feature overlap' in the CorrelateGroupingParameters

2024-01-08 19:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_metacorrelate/corrgrouping/AdvancedCorrelateGroupingParameters.java
> +      This will skip the feature overlap function """, 250);
also no word of overlap in the FeatureShapeCorrelationParameters

2024-01-09 10:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/RowGroupFull.java
> +  protected final List<RawDataFile> raw;
THis is only to make sure the order of the raw data files does not change. because all other things depend on it. 
RowGroupFull should not be used as much now. 
In the future it would be great to redo this module. I structured some things way to complex

2024-01-09 10:19 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/RowGroupFull.java
> +public class RowGroupFull implements RowGroup {
added

2024-01-09 10:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/RowGroupSimple.java
> +public class RowGroupSimple implements RowGroup {
moved all into correlation

2024-01-09 10:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_metacorrelate/corrgrouping/AdvancedCorrelateGroupingParameters.java
> +      This information is only needed in some visualization modules.""", true);
True makes sense. Changed the name to Keep extended stats and added more description. 

Those modules are not used much. its nice to have though. Its like showing all correlation values in a histogram etc

2024-01-09 10:36 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_metacorrelate/corrgrouping/AdvancedCorrelateGroupingParameters.java
> +      This will skip the feature overlap function """, 250);
![image](https://github.com/mzmine/mzmine3/assets/10366914/ec35ed5b-137e-4af1-935a-f115d6be8514)

min intensity overlap

2024-01-09 11:02 UTC, robinschmid commented
@SteffenHeu all done

2024-01-11 09:16 UTC, robinschmid commented
merged with @ansgarkorf @SteffenHeu

2024-01-11 09:17 UTC, merged