Add PCA
mzmine/mzmine3 pull request #1705
Opened 2024-03-07 10:14 UTC by SteffenHeu

will add some screenshots later

2024-03-07 16:38 UTC, robinschmid commented on javafx-framework/src/main/java/io/github/mzmine/javafx/components/factories/FxComponentFactory.java
> +  public static <T> HBox createLabelledComboBox(String label, ObservableList<T> values,
labeled with one l in american.
I am always confused which to use but just also looked at the LabeledProgressBar

2024-03-07 16:54 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/FxControllerBinding.java
> +  public static void bindExposedProperties(FxControllerBinding master, FxControllerBinding child) {
is this used somewhere. I like the idea a lot. 
Maybe you could use the same ending for all the classes like the interface:
Binding --> SelectedRowBinding
Or SelectedRowBinder

This would distinguish it from a controller.
Or PropProvider or somthing like that?

2024-03-07 16:58 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/FxControllerBinding.java
> +  public static void bindExposedProperties(FxControllerBinding master, FxControllerBinding child) {
ok, will change that in the stats overview pr

2024-03-07 17:06 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/ZCategoryProvider.java
> +public interface ZCategoryProvider extends XYZValueProvider {
Why Z provider? XYZ already has a Z value - is the category connected to Z?
Maybe add javadoc.

Also do we need extend XYZValueProvider here? This could be standalone embracing composition over inheritance. 

Both implementing classes also implement XYZValueProvider itself

2024-03-07 17:10 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/FxControllerBinding.java
> +  public static void bindExposedProperties(FxControllerBinding master, FxControllerBinding child) {
makes sense

2024-03-07 17:12 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/SelectedFilesController.java
> +public non-sealed interface SelectedFilesController extends FxControllerBinding {
why non-sealed?
Do you think we will extend this? Otherwise just final?

2024-03-07 17:12 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/SelectedFilesController.java
> +public non-sealed interface SelectedFilesController extends FxControllerBinding {
same for the other

2024-03-07 17:15 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +        userData="io.github.mzmine.modules.dataanalysis.pca_new.PCAModule"/>
just looked at the dataanalysis package. Maybe we can use common prefixes for the modules to sort them better? Like in the dataprocessing package.
Maybe mv_ for multivariate and uv univariate or multi / uni_

2024-03-07 17:16 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +public class LoadingsProvider extends SimpleXYProvider implements PlotXYZDataProvider,
PCALoadingsProvider? also for ScoresProvider

2024-03-07 17:19 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +  private final int loadingsX;
maybe pcIndexX or componentIndexX and Y?
also in the constructor.

I was kind of wondering what loadingsX is

2024-03-07 17:28 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +        result.rows(), true, FeatureAnnotationPriority.getDataTypesInOrder());
or you convert the output already to something like
List<RowsByAnnotation> of type
record RowsByAnnotation (List rows, DataType annotationType)

This would make it even easier to grasp than TreeMap but both seems good

2024-03-07 17:34 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +        result.rows(), true, FeatureAnnotationPriority.getDataTypesInOrder());
Okay the code below actually also seems to belong to the same logic. So maybe it would be nice to incorporate the value into the result type

2024-03-07 18:32 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +        result.rows(), true, FeatureAnnotationPriority.getDataTypesInOrder());
Tried something here. 
See incoming PR

2024-03-07 19:23 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +        result.rows(), true, FeatureAnnotationPriority.getDataTypesInOrder());
This PR adds some util methods to avoid indexOf lookups
https://github.com/SteffenHeu/mzmine3/pull/14

2024-03-08 06:57 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +    return zCategories[index];
ok thats why its named ZCategoryProvider.
Still feels like it could just be CategoryProvider and then it might also be a 4 D

2024-03-08 07:02 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAController.java
> +  }
this is the same as selectedFeatureListsProperty
remove?

2024-03-08 07:03 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAController.java
> +    model.flistsProperty().addListener(_ -> update());
flistProperty is twice

2024-03-08 07:17 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAController.java
> +    model.flistsProperty().addListener(_ -> update());
I found a solution to the reoccuring update calls to change it to a single binding. This might be nice. Will finalize the PR. 

Also one _ is the invalidation listener. but here you would want to use the change listener. 
Its bad that they use the same method call... I nearly missed that.

2024-03-08 07:41 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCANotComputedException.java
> +    super("Computation of this PCA has not finished or has not started yet.");
can you add some more description when this happens? as javadoc or here in the exception

2024-03-08 07:44 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAParameters.java
> +    }
maybe a general question how we want to handle those errors. 
We could also just open the window and check there and then display an error message. ControlsFX has different options for this. Like a banner on the top (we use it for users to change the tmp directory) or in their OS message on the right

2024-03-08 07:45 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAResult.java
> +        numComponents - 1);
maybe add just a few comments. Now you remember:
describing what U is and Rows

2024-03-08 07:46 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAResult.java
> +    final RealMatrix subMatrixS = svd.getS()
same here for S in case you know

2024-03-08 07:47 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAResult.java
> +    final RealVector domainVector = pcs.getColumnVector(domainColIndex);
doc for column vector?

2024-03-08 07:47 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/ZCategoryProvider.java
> +public interface ZCategoryProvider extends XYZValueProvider {
This one just provides the category, not the z value. everything else is handled by the XYZValueProvider

2024-03-08 07:52 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAController.java
> +    model.flistsProperty().addListener(_ -> update());
I was about to fix that in the next pr. how does it make a difference if its one or the other listener?

2024-03-08 07:53 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAParameters.java
> +    }
Next pr changes the featurelistsparameter.

2024-03-08 07:55 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAUpdateTask.java
> +    for (int i = 1; i <= pcaRowsResult.pcaResult().principalComponentsMatrix().getRowDimension();
maybe add a method to pcaResult.getComponentsCount

2024-03-08 07:56 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAUpdateTask.java
> +    for (int i = 1; i <= pcaRowsResult.pcaResult().principalComponentsMatrix().getRowDimension();
and maybe directly listComponents

2024-03-08 07:58 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAUpdateTask.java
> +      model.setRangePc(components.getLast() + 1);
why would components.getLast + 1 be the component then?
shouldt it just be domain = 1 and range = 2 as a default?

2024-03-08 07:59 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAUpdateTask.java
> +      model.setRangePc(components.getLast() + 1);
components also seem to be already +1 so not index but component name

2024-03-08 08:02 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAViewBuilder.java
> +
just keep Scores and Loadings without plot?

2024-03-08 08:13 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAViewBuilder.java
> +        newValue.forEach(d -> loadingsPlot.addDataset(d.dataset(), d.renderer()));
it feels like this is doubled? there is a another call to forEach.addDataset.

Will create a PR that extracts a method from this. because both plots behave the same way I think. If not then no need to merge.

2024-03-08 08:16 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAViewBuilder.java
> +
why does that matter?

2024-03-08 09:36 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAViewBuilder.java
> +
thought its nice to keep the title short. but optional

2024-03-08 09:40 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/ScoresProvider.java
> +            : Map.of();
maybe make the function accept null and just return Map.of in that case. Might make it easier in the future.

Do we need to capture the missing metadata exception here or ist it ok to pass through to the caller?

2024-03-08 09:47 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/ScoresProvider.java
> +    return groupNames[category] != null ? groupNames[category] : "unnamed group";
when is the groupNames[] == null? 
is this a safe guard or does the map that initializes groupName contain a null key? 
Otherwise you could set the "unnamed group" before.

2024-03-08 09:48 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowBarDataset.java
> +public class RowBarDataset extends DefaultBoxAndWhiskerCategoryDataset {
better name it RowBoxPlotDataSet or RowBoxWiskersDataset.
easier to find

2024-03-08 11:09 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowsBoxplotController.java
> +    model.setDataset(
onGuiThread 
generally model might changeon different thread so safe guard here

2024-03-08 11:12 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowsBoxplotController.java
> +    model.selectedRowsProperty().addListener((_, _, n) -> updateDataset(n));
instead of giving the list as argument just take it from the model within the updateDataset method. This avoids that you have to do it in every listener.
You could also use the new LastChangeProperty here. If you dont like to put this binding in the model, you could also create this property here locally just for the binding.
This would reduce it to one line of code

2024-03-08 11:14 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowsBoxplotModel.java
> +public class RowsBoxplotModel {
its so nice that I can just read the properties and then jump over the rest as its auto generated :D
So other classes are not so polluted

2024-03-08 11:19 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowsBoxplotViewBuilder.java
> +public class RowsBoxplotViewBuilder extends FxViewBuilder<RowsBoxplotModel> {
In future work it would be great to add teh control panels at the bottom in an accordion to also adjust and control the boxplot in case it is standalone. There could be a property in the model if the accordion should be visible or not.

2024-03-08 11:30 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/significance/StatisticUtils.java
> +        }
this will produce NaN for missing features and null for missing data type.
Maybe enough to just do this and always get null:
```java
// cast of null is allowed and will remain null
double abundance = measure.get(ModularDataModel) feature);
```

2024-03-08 11:56 UTC, robinschmid requested changes
This is amazing. The code reads very well and this can be a blueprint for further development.

I added three isolated PR to your branch. 
https://github.com/SteffenHeu/mzmine3/pulls

2024-03-08 17:11 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/FxControllerBinding.java
> +  public static void bindExposedProperties(FxControllerBinding master, FxControllerBinding child) {
i did not need to cast anything yet, but i can add a second method

2024-03-08 17:15 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/SelectedFilesController.java
> +public non-sealed interface SelectedFilesController extends FxControllerBinding {
because we would have to put all controllers in this package then

2024-03-08 17:16 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +        userData="io.github.mzmine.modules.dataanalysis.pca_new.PCAModule"/>
can do at some point. the thing is that the others will be removed anyway

2024-03-08 17:22 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +    return zCategories[index];
then we would need another dataset for it, because we cannot use the z value for the category anymore. Then we also need a new renderer. 
This is the better solution

2024-03-08 17:23 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCANotComputedException.java
> +    super("Computation of this PCA has not finished or has not started yet.");
not used anymore

2024-03-08 17:43 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAUpdateTask.java
> +      model.setRangePc(components.getLast() + 1);
last +1 does not make sense, yes.

> components also seem to be already +1 so not index but component name

where? 1 is subtracted in the constructor

2024-03-08 17:48 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/ScoresProvider.java
> +            : Map.of();
the column is null if it does not exist due to the metadatagroupingcomponent. In the next PR it automaticall changes the property to MEtadatadaColumn instead of string. so wont hcange here.

2024-03-08 17:50 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/ScoresProvider.java
> +            : Map.of();
adapted to return Map.of on null

2024-03-08 17:51 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/ScoresProvider.java
> +    return groupNames[category] != null ? groupNames[category] : "unnamed group";
just a safety measure.

2024-03-08 17:52 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/ScoresProvider.java
> +    return groupNames[category] != null ? groupNames[category] : "unnamed group";
i guess only if object.tostring returns null.

2024-03-08 17:52 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowBarDataset.java
> +public class RowBarDataset extends DefaultBoxAndWhiskerCategoryDataset {
next pr

2024-03-08 17:58 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowsBoxplotViewBuilder.java
> +public class RowsBoxplotViewBuilder extends FxViewBuilder<RowsBoxplotModel> {
yes could do. but just a boxplot is al ittle few info, so i dont know if we will do that

2024-03-08 17:59 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/significance/StatisticUtils.java
> +//      }
Will write a test for the methods in the future, so i want to test against this at some point

2024-03-08 18:02 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/significance/StatisticUtils.java
> +        }
can a double be null? i dont think so. this is indeed a problem. the matrix cannot contain null, so we need to be able to know if a feature is missing. Double.NaN can do that. I propose to use Double.Nan also in line 156 if the type is missing.

2024-03-08 19:44 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/FxControllerBinding.java
> +  public static void bindExposedProperties(FxControllerBinding master, FxControllerBinding child) {
done in dashboard pr

2024-03-09 09:12 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/LoadingsProvider.java
> +    return zCategories[index];
The use here is fine. It was more about the naming of the ZCategoryProvider.
Just felt like the class just provides a category for an item. Like the ItemProvider provides an item like a row. 

I mean I could have an XYZ dataset and then still add the ZCategoryProvider as the 4th dimension or just additional info. So renaming would make that clearer that it does not need to be coupled to Z

2024-03-09 09:16 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/ZCategoryProvider.java
> +public interface ZCategoryProvider extends XYZValueProvider {
So maybe the Z could be dropped from the name to make clear that it just provides a Category?
Also dropping the extends XYZValueProvider

2024-03-09 09:21 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/framework/fx/FxControllerBinding.java
> +  public static void bindExposedProperties(FxControllerBinding master, FxControllerBinding child) {
Was just thinking because you are not using any specific method in here and the instanceof checks are kind of needed anyway

2024-03-09 09:21 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/ScoresProvider.java
> +            : Map.of();
Nice

2024-03-09 09:23 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/rowsboxplot/RowsBoxplotViewBuilder.java
> +public class RowsBoxplotViewBuilder extends FxViewBuilder<RowsBoxplotModel> {
Lets see when the need arises

2024-03-09 09:24 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/significance/StatisticUtils.java
> +//      }
ok thought it was duplicated

2024-03-09 09:27 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/significance/StatisticUtils.java
> +        }
oh sorry. Double abundance of course. but if it needs notnull then I would prefer adding a getOrElse method to the AbundanceMeasure.
Could even simplify and add another method: getOrElseNaN(feature)

I guess this will be used in many places and always catching the different cases would be annoying?

2024-03-09 11:36 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/significance/StatisticUtils.java
> +        }
I already added a get or nan method

2024-03-10 13:06 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAController.java
> +    model.flistsProperty().addListener(_ -> update());
I think repeating those calls like this invite copy paste error and are redundant. Thats why it would be nice to use a binding and just one line of code. 
Could also be a utils method that takes a Runnable and Observable... to run on changes. All better than repeating the whole listener.

2024-03-10 13:15 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/significance/StatisticUtils.java
> +        }
ok nice. It did not show but updated again.
You could still simplify the whole call to `double abundance = measure.get(ModularDataModel) feature);`
instead of if null else.

2024-03-10 14:05 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCATab.java
> +    return controller.featureListsProperty().get();
all the calls to featureListProperty need to be changed to selectedFeatureListsProperty

2024-03-10 14:13 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataanalysis/pca_new/PCAUpdateTask.java
> +      model.setRangePc(components.getLast() + 1);
Ok makes sense.
The other part of the question was just if both should be set to getLast then or rather to PC1 and PC2? both are good though

2024-03-10 14:15 UTC, robinschmid commented
Looks great. Can be merged once the compile conflict is resolved and you took final decision on the last comments. Feel free to decide.

2024-03-11 12:49 UTC, merged