Landing page
mzmine/mzmine3 pull request #1749
Opened 2024-04-03 21:41 UTC by SteffenHeu

Reworked the landing page, removed standard themes

2024-04-04 07:40 UTC, robinschmid commented
- [ ] For smaller icons replace text as tooltip - people will learn what the icons mean
- [ ] documentation to small icons
- [ ] preferences to small icons


## bigger icons top

- [ ] Overview video showing key features
- [ ] Getting started video introducing the wizard
- [ ] mzwizard Workflows: Later we can add an animation there where the different instruments slide together: LC-Orbitrap, GC-TOF

2024-04-08 09:29 UTC, robinschmid commented on javafx-framework/src/main/java/io/github/mzmine/javafx/components/factories/FxLabels.java
> +  public static Label styled(String name, String styleClass) {
I like the styled!
For most factories I like the use of static import so FxLabels.styled would then be just styled. So maybe we could use styledLabel or styledLbl or something like that?

2024-04-08 09:34 UTC, robinschmid commented on javafx-framework/src/main/java/io/github/mzmine/javafx/util/FxIconUtil.java
> +    box.setMaxHeight(maxHeight);
is the HBox needed to force the width? So setting maxWidth and maxHeight on imageView does not work?
Just asking because returing the image view might be nice in other places where the image might change.

2024-04-08 09:36 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/NewVersionCheck.java
> +  private final ObjectProperty<VersionCheckResult> result = new SimpleObjectProperty<>(null);
real nice with the property now

2024-04-08 09:42 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +        .bind(MZmineCore.getConfiguration().getPreferences().darkModeProperty());
you can use ConfigService and for the most used features you can pull up the method into the ConfigService. Like I already did for the number formats. 
So maybe ConfigService.darkModeProperty()

2024-04-08 10:11 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +    title.setAlignment(Pos.TOP_CENTER);
I also needed that use case and added new methods in my PR that let you do
newHBox(Pos.TOP_CENTER, nodes...)
At least something for later :)

2024-04-08 10:17 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +        model.isIsDarkMode() ? wizardImageDarkMode : wizardImageLightMode);
might be nice to have a custom class that handles this. 
DarkLightImageView could take a single String as resource and like logo.png as light and then automatically derive the logo_dark.png from it?
And we could then bind the imageProperty in the ImageView by the isDarkMode property

2024-04-08 10:25 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +        FxLabels.italic("Nat Biotechnol "), FxLabels.bold("41"), new Label(", 447-449 (2023)."));
Just had the same issue and looked it up there is a thing called TextFlow and its best used with Text and Hyperlink components. Somehow it does not work well with labels as it disregards breaks then. 
I made a factory for that still in my PR

2024-04-08 10:26 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +  private ColumnConstraints createColumnConstraints() {
unused

2024-04-08 10:27 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +    final Label lblWizard = FxLabels.styled("Easy workflow setup", "bold-title-label");
use boldTitle instead of styled?
also in the other places where styled is used

2024-04-08 10:30 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +      "icons/introductiontab/logos_mzio_mzmine_light.png", 350, 200);
Sadly we cannot put things into the builder as the build method will create a new view each time it is called and this would mean that those components are placed in multiple parents at the same time. 
Image should work at this level - but could also be static final then. 

Best could be to move this into a sub class like DarkLightImageView that then just takes one string for the image and loads both light and dark mode images bound to a isDarkMode property. What do you think?

2024-04-08 10:33 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/preferences/Themes.java
> +  JABREF_DARK_CUSTOM("Dark 2 (JabRef)",
I was always using the dark custom - is there still going to be two dark themes? maybe we make it one?

2024-04-08 10:35 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/parameters/parametertypes/ComboParameter.java
> +    this(name, description, choices, choices.getFirst());
potential out of range exception here. 
Maybe leave it at as null and then the other constructor will initialize with first value.

We should check where this constructor is called without default value because some modules were designed to force the user to choose instead of having something preselected

2024-04-08 10:37 UTC, robinschmid requested changes
Almost done. Great progress

2024-04-08 15:20 UTC, SteffenHeu commented on javafx-framework/src/main/java/io/github/mzmine/javafx/util/FxIconUtil.java
> +    box.setMaxHeight(maxHeight);
no, it was a test to make the image auto scale. but it did not work

2024-04-09 09:27 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +  void unsubsribe() {
public / private?

2024-04-09 09:39 UTC, robinschmid approved these changes
All Done

2024-04-09 09:39 UTC, merged