Workshopfixes
mzmine/mzmine3 pull request #1798
Opened 2024-04-16 08:50 UTC by SteffenHeu

- fix dowloand link referring to v3.9 (#1796)
- fix error message display box
- reorganise main menu (raw data import) (slack)
- update error messages for import tasks #1795 (when running the batch)
- update hilic wizard presets

2024-04-20 12:48 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +        <MenuItem text="Mass detection" onAction="#runModule"
Why put spectral processing and filtering in Spectral libraries menu

2024-04-20 12:49 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/introductiontab/IntroductionTabBuilder.java
> +            .openWebPage("https://github.com/mzmine/mzmine3/releases"));
releases/latest to point to the latest stable release

2024-04-20 12:51 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/FeatureResolverSetupDialog.java
> +    delayedParameterUpdateListener.setOnFinished(event -> updateWithCurrentParameters());
should both delayed listeners call the same method? That seems odd
both call: updateWithCurrentParameters

2024-04-20 12:56 UTC, robinschmid requested changes
Few comments rest looks good.

2024-04-21 09:21 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/FeatureResolverSetupDialog.java
> +    delayedParameterUpdateListener.setOnFinished(event -> updateWithCurrentParameters());
changing a feature and changing the parameters both update the preview, i think thats correct :D 
but this is changed in the next pr anyway

2024-04-24 07:11 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/FeatureResolverSetupDialog.java
> +    delayedParameterUpdateListener.setOnFinished(event -> updateWithCurrentParameters());
Ok was just wondering because there were 2 separate pause transitions doing the same thing with different offsets.

2024-04-25 10:32 UTC, robinschmid approved these changes
Thanks for addressing the comments.

2024-04-25 10:32 UTC, merged