Ion identity networking
mzmine/mzmine3 pull request #235
Opened 2021-03-16 15:24 UTC by robinschmid

Progress to integrate ion identity networking in MZmine 3

2021-06-07 13:10 UTC, robinschmid commented
@tomas-pluskal @SteffenHeu

2021-06-07 17:29 UTC, robinschmid commented
The exported MS2 spectral similarity edges from any R2RMap 
![image](https://user-images.githubusercontent.com/10366914/121063488-aa53c200-c7c6-11eb-8e70-f417a201f3ed.png)

2021-06-08 13:02 UTC, SteffenHeu requested changes

2021-06-09 15:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/data_access/PreloadedFeatureDataAccess.java
> +public class PreloadedFeatureDataAccess {
Maybe I could add the preload mz / intensity as boolean arguments to the constructor and depending on that we use HashMap or ConcurrentHashMap?

2021-06-09 15:53 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/CorrelationRowGroup.java
> +  public static final Paint[] colors = ChartColor.createDefaultPaintArray();
I removed it. 
Was used in another module that I did not include in this PR

2021-06-09 15:58 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/CombinedScoreType.java
> +public class CombinedScoreType extends ScoreType {
/**
 * A {@link ScoreType} that combines multiple other scores. This type is typically used right after
 * other score types to signal which scores were combined. In the case of {@link
 * FormulaAnnotationType}, CombinedScore combines {@link IsotopePatternScoreType} and {@link
 * MsMsScoreType}, and the relative mass differnce into one score.
 */

2021-06-09 16:01 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/FormulaMassType.java
> +public class FormulaMassType extends DoubleType {
PrecursorMZType is the measured m/z
NeutralMassType is the neutral mass for the precursor m/z (calculated based on a specific IonIdenttiy)
FormulaMassType is the calculated mass for the given formula

2021-06-09 16:42 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/data_access/PreloadedFeatureDataAccess.java
> +public class PreloadedFeatureDataAccess {
I think since this is mainly used to increase performance, it might be be good to just preload it anyway.

2021-06-09 18:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/MsMsScoreType.java
> +public class MsMsScoreType extends ScoreType {
done

2021-06-09 18:19 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/MzPpmDifferenceType.java
> +    return "\u0394 ppm";
This is the header... not the unit.
Or should I change it to 
Delta m/z [ppm] 
+ the header string should be a final field and not dynamically evaluated. If we export to csv and other tools use this header we cannot include this variance

2021-06-09 18:25 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/AnnotationType.java
> +public class AnnotationType extends ListDataType<FeatureIdentity> {
I moved this to an issue.
https://github.com/mzmine/mzmine3/issues/285

2021-06-09 18:29 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/MzPpmDifferenceType.java
> +    return "\u0394 ppm";
Yeah, it makes sense with regard to the export, just stick to one naming scheme then.

2021-06-09 18:31 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/types/AnnotationType.java
> +public class AnnotationType extends ListDataType<FeatureIdentity> {
Renaming and moving your new annotations should be done before merging, though, in my opinion.

2021-06-09 18:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/FormulaAnnotationType.java
> +public class FormulaAnnotationType extends ModularType implements AnnotationType {
This type has the full annotation - all the scores etc that lead to the prediction of a formula.
FormulaType only describes the formula

2021-06-09 18:37 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/FormulaConsensusSummaryType.java
> +public class FormulaConsensusSummaryType extends ListDataType<ResultFormula>
Added jdoc
This is its intended use.
Currently the only module using it is Ion identity networking to predict consensus formulas for IonNetworks

2021-06-09 18:43 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/IonIdentityListType.java
> +    return "Ion adduct";
IonAdduct is only the adduct [M+H]+
IonIdenttiyListType is a list of ion identities
IonIdentityModularType shows all sub data types of the selected ion identity in the list

Added jdoc

2021-06-09 18:44 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/FeatureListRow.java
> +  public void setID(int id);
This is a good question. But we had this in MZmine 2 and some other tools rely on it. 
They renumber after filtering the list

2021-06-09 18:45 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +    this.name = name;
Should not be a problem right?
It is not a property

2021-06-09 18:47 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +
/**
   * create copy of all feature list rows and features. Use a different list of raw data files. The
   * new list of raw data files might be used by alignment modules to create a copy of a base
   * feature list and then add all the other feature lists to it.
   *
   * @param title     the new title
   * @param dataFiles the new list of raw data files
   * @return
   */

2021-06-09 19:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/identities/iontype/networks/IonNetRelationFeatureIdentity.java
> +public class IonNetRelationFeatureIdentity extends SimpleFeatureIdentity {
Removed it. It is represented now only by the IonNetworkRelation

2021-06-09 20:01 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/identities/iontype/networks/IonNetRelationFeatureIdentity.java
> +public class IonNetRelationFeatureIdentity extends SimpleFeatureIdentity {
Also cleaned up the related classes

2021-06-09 20:05 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/identities/iontype/IonIdentity.java
> +public class IonIdentity implements Comparable<IonIdentity> {
/**
 * IonIdentities are connected to {@link IonNetwork}s and represent different ion species fo the
 * same molecule. Typically {@link CorrelateGroupingTask} is performed before identifying ion
 * identities. They can be used to predict molecular formulas in {@link
 * FormulaPredictionIonNetworkModule} and they are part of the Ion Idententity Molecular Networking
 * workflow on https://gnps.ucsd.edu/, which is accessible through {@link
 * GnpsFbmnExportAndSubmitModule}.
 */

2021-06-09 20:08 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/group_metacorrelate/correlation/FeatureCorrelationUtil.java
> +      }
added this:
throw new UnsupportedOperationException(
          "We currently do not support feature shape correlation in two different raw data files");

2021-06-09 20:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/ObjectGenerator.java
> +public interface ObjectGenerator<T> {
Replaced

2021-06-09 20:16 UTC, robinschmid commented
I incorporated all changes from @SteffenHeu or added responses to the comments. 
Also added plenty of javadoc

2021-06-10 06:32 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/FormulaMassType.java
> +public class FormulaMassType extends DoubleType {
So PrecursorMz is just the m/z of the feature?
Why does it need to be a new type then?

2021-06-10 10:17 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/data_access/PreloadedFeatureDataAccess.java
> +public class PreloadedFeatureDataAccess {
Depends on your choice. I guess in most cases you want to preload the data.
But if you only need a fraction of all features and you compare them against each other (multiple accessions per feature data) then you would only load on demand

2021-06-10 10:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/data_access/PreloadedFeatureDataAccess.java
> +public class PreloadedFeatureDataAccess {
- I changed the name to CachedFeatureDataAccess.
- now we enforce a decision: Cache on-demand or preload with ConcurrentHashMap or HashMap, respectively.

2021-06-10 11:23 UTC, tomas-pluskal commented on src/main/java/io/github/mzmine/datamodel/data_access/CachedFeatureDataAccess.java
> +  public CachedFeatureDataAccess(FeatureListRow[] rows, boolean preloadMz,
All the preloading is done in the constructor. Preloading can take a lot of time because it loads data from the disk, and also IOExceptions can occur.. I think it is not a good practice to perform such intensive operations in the constructor. Perhaps preloading should be moved to a separate thread?

2021-06-10 11:26 UTC, tomas-pluskal commented on src/main/java/io/github/mzmine/datamodel/features/FeatureListRow.java
> +  public void setID(int id);
I agree with Steffen, set setID() is dangerous. Renumbering should only be done when new feature list is created (each new row can have a new ID), so there should be no need for setID().

2021-06-10 11:34 UTC, tomas-pluskal commented on src/main/java/io/github/mzmine/datamodel/features/GroupedFeatureListRow.java
> +public abstract class GroupedFeatureListRow implements FeatureListRow {
What is the practical difference between GroupedFeatureListRow and RowGroup? Wouldn't it be sufficient to use just one of them?

2021-06-10 11:36 UTC, tomas-pluskal commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +    this.name = name;
Can we make it a property?

2021-06-10 11:41 UTC, tomas-pluskal commented on src/main/java/io/github/mzmine/datamodel/features/RowGroup.java
> +  public int getLastViewedRowI() {
What is the I in getLastViewedRowI?

2021-06-10 11:43 UTC, tomas-pluskal commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2GroupCorrelationData.java
> +  public double getMinIProfileR() {
The names of the methods are becoming quite cryptic. I think one of the good things about Java is that the common practice is to name things in a human-readable way.. Could you spell out the **I** and **R**?

2021-06-10 12:41 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/types/AnnotationType.java
> +public class AnnotationType extends ListDataType<FeatureIdentity> {
I would say it makes more sense to do it in a later stage.
Plenty of annotations are used in library matching, lipid ID, etc. 
Easier to do then

2021-06-10 13:40 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/FeatureListRow.java
> +  public void setID(int id);
I removed the setID.

2021-06-10 14:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/data_access/CachedFeatureDataAccess.java
> +  public CachedFeatureDataAccess(FeatureListRow[] rows, boolean preloadMz,
I added javadoc to outline the usecase.
This data structure will be used inside tasks in a way that you filter your rows, initialize everything and preload data. Then you apply your methods to it.
I think its perfectly suited to run in the task - blocking the thread as long as it needs.
Then I used a parallel stream to compare feature shapes

2021-06-10 14:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/GroupedFeatureListRow.java
> +public abstract class GroupedFeatureListRow implements FeatureListRow {
GroupedFeatureListRow is currently still a left over. I was trying to also visualize this in the tree - but then stopped as it got more complex.
Its currently not used.

2021-06-10 14:29 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/correlation/R2GroupCorrelationData.java
> +  public double getMinIProfileR() {
Better method names and refactored

2021-06-10 15:06 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/features/RowGroup.java
> +  public int getLastViewedRowI() {
Clarified the method names and javadoc.
This is the internal index for visualization purposes that are not yet ported

2021-06-11 12:03 UTC, merged