image to csv export
mzmine/mzmine3 pull request #262
Opened 2021-04-24 15:22 UTC by SteffenHeu

2021-04-26 13:49 UTC, tomas-pluskal commented
Hey Steffen, the `clustering-20130919.jar` file should not be needed anymore, the dependenci is updated in build.gradle

2021-04-26 14:26 UTC, SteffenHeu commented
Oops, my bad. I thought it was the other way round. I'll remove it.

2021-04-30 10:13 UTC, robinschmid requested changes

2021-04-30 10:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +public class ImageToCsvExportTask extends AbstractTask {
some small java doc to explain that this exports imaging data for features to CSV

2021-04-30 10:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +        (List<ImagingRawDataFile>) (List<? extends RawDataFile>) features
double cast?

2021-04-30 10:17 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +            .filter(file -> file instanceof ImagingRawDataFile).toList();
Maybe add .map(f -> (ImagingRawDataFile) f) this shoudl make the cast obsolete

2021-04-30 10:21 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/featuredata/FeatureDataUtils.java
> +        .span(Range.singleton((float) series.getMobility(series.getNumberOfValues() - 1)));
This way we don't have too loop trhough all values

2021-04-30 10:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +    final double[][] dataMatrix = new double[absMaxY][];
new double[absMaxY][absMaxX]  this should be fine - no need for a loop creating arrays with the same length

2021-04-30 10:25 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +        dataMatrix[scan.getCoordinates().getY()][scan.getCoordinates().getX()] = data
is scan.getCoordinates always 0 based? Otherwise you would have to subtract the minimumX minmumY coordinate

2021-04-30 10:30 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +          b.append(", ");
only separate by "," and rather use your String sep - that is defined in the parameters.

2021-04-30 10:33 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +        writer.append(b.substring(0, b.length() - 2));
the -2 was from the trailing ", " (with a space) now you would need to use sep.length.
However, I would just check if x<dataMatrix[y].length-1 before appending the separation string.

2021-04-30 10:44 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/files/FileAndPathUtil.java
> +        i = r.nextInt();
thats weird.
nextint might return some negative value and then you begin to loop until i>50.
You could make sure that you get a random int >50 here

2021-04-30 10:49 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/SpectraMerging.java
> +    final List<MobilityScan> scans = series.getMobilograms().stream()
wait this works? You can access pattern matched variable series outside of the if statement? 
I mean you do if( .... series) { return }  and then you access it

2021-04-30 10:59 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/featuredata/FeatureDataUtils.java
> +        .span(Range.singleton((float) series.getMobility(series.getNumberOfValues() - 1)));
Yes but why use span on two singletons if you could also use Range.closed(series.getMobility(0), series.getMobility(series.getNumberOfValues() - 1))

You could check 
if(size == 1) then Range.singleton
else Range.closed()

2021-04-30 11:43 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/featuredata/FeatureDataUtils.java
> +        .span(Range.singleton((float) series.getMobility(series.getNumberOfValues() - 1)));
Only SummedIntensitySeries are guaranteed to be sorted in ascending order. IonMobilitySeries might be sorted in descending order due to the nature of TIMS.
Math.min/Math.max might be more performant tht generating two temporary objects, though, so I'll adjust it to that.

2021-04-30 11:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +        (List<ImagingRawDataFile>) (List<? extends RawDataFile>) features
yes :D

2021-04-30 11:56 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +            .filter(file -> file instanceof ImagingRawDataFile).toList();
smart

2021-04-30 12:05 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +        dataMatrix[scan.getCoordinates().getY()][scan.getCoordinates().getX()] = data
yes, see javadoc for Coordinates.

2021-04-30 12:06 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +      ArrayUtils.fill2D(dataMatrix, 0d);
We don't quantify in images and 0d values are not saved.

2021-04-30 12:14 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/scans/SpectraMerging.java
> +    final List<MobilityScan> scans = series.getMobilograms().stream()
Java 16 feature for mapMulti i think

2021-04-30 13:56 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +        dataMatrix[scan.getCoordinates().getY()][scan.getCoordinates().getX()] = data
ok

2021-04-30 14:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
> +          if(x < dataMatrix[y].length) {
this should be length -1 to not add the last separation

2021-04-30 14:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_image_to_csv/ImageToCsvExportTask.java
>          writer.newLine();
You could do b.newLine() and then only one writer.append(b.toString());
But not really important I think

2021-04-30 14:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/files/FileAndPathUtil.java
> +        i = r.ints().filter(number -> number > 50).findFirst().orElse(0);
Still not sure. Feels unsafe.
Why not just loop through all ints until you find the next free file name?
If Random gives you Integer.MAX_VALUE and you add i++ in the next while loop you will throw an exception.

rand.nextInt(Integer.MAX_VALUE-52)+51 should do the trick. But then again - why?

2021-05-03 10:17 UTC, robinschmid commented
Thanks Steffen

2021-05-03 10:17 UTC, merged