Plot updates, scatter pie charts
mzmine/mzmine3 pull request #263
Opened 2021-04-26 20:00 UTC by SteffenHeu

- Remove MultiDatasetXYZScatterPlot
  - functionality integrated into SimpleXYZScatterPlot
- Mobility-m/z heatmap uses pie chart, can now plot aligned feature lists
  - added pie dataset, renderer, and provider to draw scatter-pie-charts
  - rows are rendered as pie, overall size = summed row intensity, individual slices are data file dependant
![grafik](https://user-images.githubusercontent.com/37407705/116142185-e2e98180-a6d9-11eb-9a9d-7f623643ffa8.png)
- the pie dataset, chart and renderer can be used in SimpleXYZScatterPlot
- added method to merge frames (but not feasibly to plot for now, too much data points)

- SimpleXYZScatterPlot:
  - if dataset(s) with a paint scale are used, the paintscale of the first dataset will be used as a legend by default (still need to add this as javadoc)
  - a custom legend paint scale can be set
  - if the dataset is not a PaintScaleProvider, the default methods of the renderers are used. (as in pie datasets)

2021-05-06 15:00 UTC, robinschmid requested changes

2021-05-06 15:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/datasets/ColoredXYZPieDataset.java
> +    zRange = Range.closed(minZ, maxZ);
Same here. Range 0-1 if computedItemCount == 0

2021-05-06 16:19 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/impl/features/RowToMobilityMzHeatmapProvider.java
> +    return Objects.requireNonNullElse(rows.get(index).getAverageMobility(), 0f).doubleValue();
getAverageMobility is currently float - so null check does not work.
Why is the range method different to the domain method?

2021-05-06 17:26 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/RegionSelectionWrapper.java
> +          .add(new ExtensionFilter("MZmine regions file", "*.mzmineregion"));
maybe change format name to something xml - makes it obvious that this is in xml format
mzmineregionxml

2021-05-06 17:29 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYChart.java
> +//    notifyDatasetChangeListeners();
Maybe there should be an notify option as a method argument

2021-05-06 17:33 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYZScatterPlot.java
> +  private final ObjectProperty<PaintScale> legendPaintScale = new SimpleObjectProperty<>(null);
this property cannot be null - the annotations works on the property object and not on its value right?
Does it need to be a property (for JavaFX binding) or could it also be an Optional?

2021-05-06 17:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYZScatterPlot.java
>  //    assert Platform.isFxApplicationThread();
remove this comment? 
and it should not be asserted at this point

2021-05-06 17:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYZScatterPlot.java
>      plot.setDataset(dataset);
synchronized is not needed if you then assert its on the FX Thread.
So you already force it to be on one thread - there is no way for concurrent modification ;)
However, do we really need to run it on the fx thread?

As far as I remember you change the dataset and then you still need to notify jfreechart to repaint the chart with the fire change event method. It should be fine to set the dataset outside of JavaFX and then call the change event

2021-05-06 17:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYZScatterPlot.java
>      assert Platform.isFxApplicationThread();
copied from above:
synchronized is not needed if you then assert its on the FX Thread. So you already force it to be on one thread - there is no way for concurrent modification ;) However, do we really need to run it on the fx thread?
As far as I remember you change the dataset and then you still need to notify jfreechart to repaint the chart with the fire change event method. It should be fine to set the dataset outside of JavaFX and then call the change event

2021-05-06 17:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYZScatterPlot.java
> +      chart.fireChartChanged();
ok sounds about right. So this way you do not need to force the addDataset / setDataset methods on the fx thread. This part should handle it

2021-05-07 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYZScatterPlot.java
>      plot.setDataset(dataset);
JFreechart automatically notifies. However, when rendering the chart to an image, we don't want it to be on the jfx thread. So it's kinda hacky right now and i don't know what the best solution is.

2021-05-07 08:02 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/impl/features/RowToMobilityMzHeatmapProvider.java
> +    return Objects.requireNonNullElse(rows.get(index).getAverageMobility(), 0f).doubleValue();
Since we want to change to Float in the future, i wanted to make it future safe.

2021-05-10 10:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/impl/SimpleMergedMassSpectrum.java
> +      logger.info("blub");
remove logging

2021-05-10 10:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/SpectraMerging.java
> +//      mergedMsMsSpectrum.addMassList(new ScanPointerMassList(mergedMsMsSpectrum));
remove this line if you do not need it

2021-05-10 12:15 UTC, robinschmid commented
Thanks Steffen

2021-05-10 12:15 UTC, merged