Project remove properties
mzmine/mzmine3 pull request #451
Opened 2021-12-14 02:58 UTC by robinschmid

The properties in the project are annoying. Currently, it is not safe how we add new elements etc. due to the bindings to JavaFX components. 

I changed the structure back to simple ObservableLists and change listeners, where needed. Other components just use the copies of the current lists.

2021-12-14 07:19 UTC, SteffenHeu requested changes

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
> +      synchronized (project.getCurrentFeatureLists()) {
no point in synchronizing on an object created on method call, or?

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/MZmineGUI.java
> +        final var fxLibs = FXCollections.observableArrayList(new ArrayList<>(libs));
why are you wrapping an observable list?

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/FeatureResolverSetupDialog.java
> +        .getCurrentProject().getCurrentFeatureLists();
1. you are casting a normal array list to observable here. 
2. Why not use the observable directly?

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_masscalibration/MassCalibrationSetupDialog.java
> +        MZmineCore.getProjectManager().getCurrentProject().getCurrentRawDataFiles()));
why not use the observable lists?

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_mobilogram_summing/MobilogramBinningSetupDialog.java
> +        .getCurrentProject().getCurrentFeatureLists();
again, casting normal lsit to observable

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_smoothing/SmoothingSetupDialog.java
> +        .getCurrentProject().getCurrentFeatureLists();
again

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/projectsave/ProjectSavingTask.java
> +    for (FeatureList featureList : savedProject.getCurrentFeatureLists()) {
will this create a new list on every iteration?

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/spectra/simplespectra/SpectraBottomPanel.java
> +        MZmineCore.getProjectManager().getCurrentProject().getCurrentFeatureLists()));
why not use the observable list?

2021-12-14 07:19 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/project/impl/RawDataFileImpl.java
> +      synchronized (project.getCurrentRawDataFiles()) {
same as with feature list

2021-12-14 20:19 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/projectsave/ProjectSavingTask.java
> +    for (FeatureList featureList : savedProject.getCurrentFeatureLists()) {
I think it wont. it should be the same like getCurrentFeatureLists().forEach

2021-12-22 21:56 UTC, merged

2021-12-22 21:57 UTC, robinschmid commented
Together with @SteffenHeu