Fix chart speed
mzmine/mzmine3 pull request #510
Opened 2022-01-12 08:36 UTC by robinschmid

Fix chart speed, notify false, fix multiple tasks per chrom spec
### ChromatogramAndSpectraVisualizer
- every click in any chart was starting 2 tasks to update each plot - 4 in total
- added a small delay to simlify it
- set notify to false to only update the charts once everything is done

2022-01-12 08:48 UTC, SteffenHeu commented
I noticed it before, do you know why the click event is even triggered twice in the first place?

2022-01-12 08:56 UTC, SteffenHeu requested changes
Will also have to manually test it, but the changes look good so far, only one change needed.

2022-01-12 08:56 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/spectra/simplespectra/SpectraVisualizerTab.java
>      if (selectedPeakList == null) {
if you set the notify to false and exit here, we will not get updates later on.

2022-01-12 19:03 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/spectra/simplespectra/SpectraVisualizerTab.java
>      if (selectedPeakList == null) {
Done. Changed all to a try - finally

2022-01-13 09:04 UTC, SteffenHeu commented
is it ready for final review?

2022-01-13 17:39 UTC, robinschmid commented
Yes.

2022-01-13 19:21 UTC, SteffenHeu reviewed
will do some testing now

2022-01-13 19:29 UTC, SteffenHeu commented
looks good

2022-01-13 19:59 UTC, merged