MASST quickstart
mzmine/mzmine3 pull request #537
Opened 2022-02-15 12:08 UTC by robinschmid

Directly submit MASST search from the feature table

2022-02-15 12:12 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/GNPSUtils.java
> +  public static String submitMASSTJob(DataPoint[] data, double precursorMZ, MasstDatabase database,
does it have to be datapoint[]? can it be two double[]?

2022-02-16 17:10 UTC, robinschmid commented
Ready from my side

2022-02-17 09:38 UTC, SteffenHeu requested changes

2022-02-17 09:38 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> +public class GnpsMasstSubmitModule implements MZmineProcessingModule {
Is it supposed to be executed in batch mode? as i understand it works on single spectra right? how would they be selected in batch?

2022-02-17 09:38 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> + * MS2 mgf, additional edges (ion identity networks)
update

2022-02-17 09:38 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> +}
shouldnt the formatter put a new line on the end of a file?

2022-02-18 12:33 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> + * MS2 mgf, additional edges (ion identity networks)
done  -i thought I updated it everywhere

2022-02-18 12:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> +}
Have to switch to the new formatter but there are a few things weird have to chekc with you

2022-02-18 12:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> +public class GnpsMasstSubmitModule implements MZmineProcessingModule {
Did not think about that. Changed it to runnable

2022-05-30 11:47 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> +  public static ExitCode submitSingleMASSTJob(double precursorMZ, DataPoint[] dataPoints) {
Are the results only presented on the webpage and not imported to mzmine?

2022-05-30 12:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_features_gnps/masst/GnpsMasstSubmitModule.java
> +  public static ExitCode submitSingleMASSTJob(double precursorMZ, DataPoint[] dataPoints) {
This is the first step - this is to run a MASST job on GNPS. this takes a while - I could add a column with the MASST job link to the table and we can download the results later. MASST job is nice because its reproducible and you can share the link. 

However,  there is fastMASST now that has an API and is really fast. So next implementation step will be to use fastMASST to directly get the results and add them to the table

2022-05-30 20:54 UTC, merged