Neutral loss mirror chart
mzmine/mzmine3 pull request #546
Opened 2022-02-21 15:30 UTC by robinschmid

Changed the Mirror chart that we get from selecting two rows in the table. Top is now the direct MS2 mirror with cosine similarity and modified cosine similarity. The bottom chart is the neutral loss chart.

![image](https://user-images.githubusercontent.com/10366914/154984917-46e30292-99fb-4103-9cc3-4ccee6d31af7.png)

2022-05-30 11:03 UTC, robinschmid commented
Added support to grab spectrum from the GNPS library and USI web APIs. (Made this a tool so that it is accessible).

![image](https://user-images.githubusercontent.com/10366914/170979095-87ecc670-a24b-44c7-a4da-98112e474e1d.png)

2022-05-30 11:04 UTC, robinschmid commented
Added parameters to control matching and filtering
![image](https://user-images.githubusercontent.com/10366914/170979339-6354afaa-2871-4cf1-8065-6f2c4df06247.png)

2022-05-30 11:08 UTC, robinschmid commented
Signal contributions and type of match (direct or modified match).

![image](https://user-images.githubusercontent.com/10366914/170979387-77bdc8f7-6919-41a3-bd0d-be35dd6155b8.png)

2022-05-30 11:41 UTC, SteffenHeu requested changes
some comments

2022-05-30 11:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_library_analysis_csv/LibraryAnalysisCSVExportTask.java
> +      LibraryAnalysisSubTask task = new LibraryAnalysisSubTask(getModuleCallDate(), this, sub,
i dont see the the applied methods being added anywhere. that should be done, and this constructor has to know about it

2022-05-30 11:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_library_analysis_csv/LibraryAnalysisCSVExportModule.java
> +  private static final String MODULE_DESCRIPTION = "Cosine similarity of library to csv";
what exactly is exported? spectral mathces of a whole feature list?

2022-05-30 11:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_library_analysis_csv/FilteredSpec.java
> +record FilteredSpec(SpectralDBEntry entry, DataPoint[] dps, DataPoint[] neutralLosses,
please specify what this class isdoing. how is it different from a spectraldbmatchresult?

2022-05-30 11:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/spectra/simplespectra/mirrorspectra/MirrorScanParameters.java
> +          10, 20));
10 m/z but 20 ppm?

2022-05-30 11:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/spectra/simplespectra/mirrorspectra/TableData.java
> +record TableData(Double mzA, Double intensityA, Double mzB, Double intensityB,
chose a more descriptive name please

2022-05-30 11:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/dialogs/ParameterSetupPane.java
> +public class ParameterSetupPane extends BorderPane {
this looks like a comple code duplication. can we use the pane inside the dialog to avoid taht?

2022-05-30 13:39 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/spectra/simplespectra/mirrorspectra/MirrorScanParameters.java
> +          10, 20));
Yeah I will change it to mz 5. ppm is not important here I can also set it to 0.
Its just a filter to get rid of the residual precursor signals + maybe isotope signals

2022-05-30 13:40 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/dialogs/ParameterSetupPane.java
> +public class ParameterSetupPane extends BorderPane {
I was thinking about that. Let me see if we can do this. Because the dialog does a few more things that I needed to strip

2022-05-30 13:40 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/dialogs/ParameterSetupPane.java
> +public class ParameterSetupPane extends BorderPane {
In general good though to have a pane instead of dialog

2022-05-30 13:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/spectra/simplespectra/mirrorspectra/TableData.java
> +record TableData(Double mzA, Double intensityA, Double mzB, Double intensityB,
Its package-private and there is only one table in the view - that should be fine no?

2022-05-30 15:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/dialogs/ParameterSetupPane.java
> +public class ParameterSetupPane extends BorderPane {
created a new PR which is based on this to generify pane and dialog #702 
seems to work also for specialized dialogs...

2022-05-30 15:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_library_analysis_csv/LibraryAnalysisCSVExportTask.java
> +      LibraryAnalysisSubTask task = new LibraryAnalysisSubTask(getModuleCallDate(), this, sub,
This method is applied to a spectral library and only to extract information from the library to a csv file

2022-05-30 15:30 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_library_analysis_csv/LibraryAnalysisCSVExportTask.java
> +      LibraryAnalysisSubTask task = new LibraryAnalysisSubTask(getModuleCallDate(), this, sub,
So no applied method.

2022-05-30 15:31 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_library_analysis_csv/LibraryAnalysisCSVExportModule.java
> +  private static final String MODULE_DESCRIPTION = "Cosine similarity of library to csv";
I added javadoc. Its a simple module to do pairwise comparison with modified cosine and neutral loss similarity.

2022-05-30 15:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_library_analysis_csv/FilteredSpec.java
> +record FilteredSpec(SpectralDBEntry entry, DataPoint[] dps, DataPoint[] neutralLosses,
its package-private as its only used here.
added javadoc. 
its holds filtered preprocessed data points from the spectral lib entry and its neutral losses.

2022-05-30 20:59 UTC, SteffenHeu commented
conflict now since we merged masst

2022-05-31 11:55 UTC, robinschmid commented
Resolved

2022-06-03 12:37 UTC, merged