Single update task for resolver preview
mzmine/mzmine3 pull request #580
Opened 2022-03-08 17:03 UTC by robinschmid

This improves the updating of the preview - but it also bugs out somehow. 
It runs on a different thread and should update the chart on jfx

2022-03-08 18:21 UTC, SteffenHeu requested changes
i think youre doing the chart changes outside of the java fx thread

2022-03-08 19:05 UTC, robinschmid commented
So the idea is to update everything outside javafx and then fire the chart change event on javafx - thats done by the 
`chart.applyWithNotifyChanges`

2022-03-08 19:09 UTC, SteffenHeu commented
But you're doing changes to an java fx object outside the java fx thread. that will only lead to problems.

2022-03-08 19:10 UTC, SteffenHeu commented
why not calculate the datasets in one thread and do all the changes when youre finished?

2022-03-08 19:14 UTC, robinschmid commented
That might work. I mean we are not changing the ChartView only the chart. but thats the same in the end I guess... 
So I double-checked chart.setNotify(false) actually cancels all updates. And plot updates are just passed up to the chart but not to the chartview.

2022-03-08 19:28 UTC, robinschmid commented
Found it. All changes to the renderer need to use notify=false
Also need different renderers for each feature

2022-03-08 19:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/FeatureResolverSetupDialog.java
> +          chart.removeAllDatasets();
is actually fine. THe problem was in changing the renderer and reusing the renderer for all features

2022-03-08 19:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/chartbasics/simplechart/SimpleXYChart.java
>      }
Reusing the same renderer for all was the problem and we need to set notify to false while changing them.

2022-03-09 09:11 UTC, SteffenHeu commented
looks goodto me

2022-03-09 09:11 UTC, merged