Changes are done in the file IsotopeFinderTask.java value of CCS is calculated and 4 variables are created named as mobility,mobilityType, chargeCCS,File;
mzmine/mzmine3 pull request #604
Opened 2022-03-17 05:31 UTC by Tarush-Singh35

Changes are done in the file IsotopeFinderTask.java value of CCS is calculated and 4 variables are created named as mobility ,mobilitytype, chargeCCS, File;

2022-03-17 07:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
What software are you using. 
In case its intelliJ or eclipse, make sure to add the code formatter that is located in the main directory. And then apply "Refactor/Organize imports" and apply the style

2022-03-17 07:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
Those should all be local variables rather than global

2022-03-17 07:31 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
I am using intelliJ I will surely do that

2022-03-17 07:35 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        setStatus(TaskStatus.ERROR);
In this case we do not want to error out.
The idea: If all information is available, we offer this analysis for free without user interaction. If anything is missing we just skip the ccs calibration and perform the task as always.

This task calculates isotopes and charge state of the detected ions. The charge state is needed for ccs calc

2022-03-17 08:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
Thats the easiest so you can add the style and press 
CTRL + ALT + L on windows to apply, similar on mac

2022-03-17 08:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +          this.chargeCCS=bestCharge;
No need to set it to another variable. Directly pass bestCharge to the calcCCS method

2022-03-17 08:53 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
will change it to local

2022-03-17 08:55 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        }
This is perfect.
The only things you have to add is the checks if all information is available:
File should be renamed to a local var imsFile

if(imsFile != null && charge > 0)

The only remaining problem will then be that we only support this calibration for some mobility types. You can check the CCSUtils.calcCCS method. Maybe we could add a function to CCSUtils to check if the mobility type is supported, check it once outside the loop and then just use a boolean here:
if(useCalibration && charge > 0)

2022-03-17 08:57 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +      this.mobilityType = feature.getMobilityUnit();
No need for this here. 
the charge will be calculated by this module
you can get the mobility closer where you calculate the CCS. (and only if you do)

2022-03-17 10:39 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        setStatus(TaskStatus.ERROR);
so by charge state, I just need to check if the charge is positive or negative?

2022-03-17 15:49 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        setStatus(TaskStatus.ERROR);
So we will only check the charge after the isotope finder has detected and sets the charge.
We set the charge always as an absolute value so its always a positive number.

2022-03-17 15:49 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        setStatus(TaskStatus.ERROR);
charge >0 is enough for the check

2022-03-21 09:29 UTC, SteffenHeu requested changes

2022-03-21 09:29 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_ccscalc/CCSUtils.java
> +  public static boolean MobilityCheckForCCS(@NotNull IMSRawDataFile file) {
please rename to hasValidMobilityType

2022-03-21 09:29 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +    }
This assumes that there is a single file present in the feature list. You can move the check down to the other checks and use feature.getRawDataFile() instead.

2022-03-21 09:33 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_ccscalc/CCSUtils.java
> +  public static boolean MobilityCheckForCCS(@NotNull IMSRawDataFile file) {
okay will rename the Function

2022-03-21 11:37 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +    }
okay moving the check

2022-03-21 11:37 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_ccscalc/CCSUtils.java
> +  public static boolean MobilityCheckForCCS(@NotNull IMSRawDataFile file) {
okay thanks will remember that

2022-03-22 13:04 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        if (data instanceof IMSRawDataFile File) {
variable names and methods always lower camelCase. Otherwise you could mistake them for a class.

2022-03-22 13:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        if (validMobility && mobility != null && bestCharge > 0) {
You could reduce all this a little bit to simplify it:
put all of it in the first if(data instanceof IMSRawDataFile imsFile) {}
this will eliminate the use of File and imsFile. Plus instanceof is also a null check - so the imsFile !=null is unecessary then.

then you can directly put the CCSUtils.hasValidMobilityType(imsFile) into the last check together with mobility!=null && charge>0.

2022-03-22 13:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +            logger.info(() -> "Raw data file " + File.getName() + " does have a CCS calibration.");
better remove this logging - it will spam the log with one line for each feature.

2022-03-22 13:17 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +    }
Added some last comments. This looks great already

2022-03-22 13:41 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        if (validMobility && mobility != null && bestCharge > 0) {
okay will make the changes

2022-03-22 13:46 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +            logger.info(() -> "Raw data file " + File.getName() + " does have a CCS calibration.");
yes I noticed I kept this because use this as well as a debugger to understand the code and check values of different variables I was going to remove this

2022-03-22 13:47 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        if (data instanceof IMSRawDataFile File) {
yeah I will make sure to use the right Notations for the Variable and method Thank you for your help

2022-03-23 07:51 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +    }
i have made the changes please review the code

2022-03-25 04:21 UTC, Tarush-Singh35 commented
hey @SteffenHeu can you please review the code

2022-03-25 07:43 UTC, SteffenHeu reviewed
One minor comment, then we are good to go

2022-03-25 07:43 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +              MobilityType mobilityType = feature.getMobilityUnit();
move the mobility unit check into the if statement. Objects.requireNonNull will still stop the execution if it's null. (although this should basically not be the case under any circumstance)

Or you can use Objects.requireNonNullElse(mobilityType, imsfile.getMobilityType())

2022-03-25 07:52 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +              MobilityType mobilityType = feature.getMobilityUnit();
okay I will make the changes

2022-03-25 08:10 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +              MobilityType mobilityType = feature.getMobilityUnit();
Objects.requireNonNull will still stop the execution yes I know it will throw unhandled exception it was done initially just to check 
I have made the changes @SteffenHeu please check

2022-03-25 11:07 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +        if (data instanceof IMSRawDataFile File) {
Thanks for adjusting.

2022-03-25 15:58 UTC, Tarush-Singh35 commented
@robinschmid is everything okay With CCS calculation?

2022-03-26 15:01 UTC, Tarush-Singh35 commented
hey @robinschmid @SteffenHeu I have made changes accordingly please Review the code for #608 as well as CCS Calculation

2022-03-28 05:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +        System.getProperty("user.dir") + File.separator + "Export" + File.separator + "Export.csv";
Should be a file chooser

2022-03-28 05:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +            ButtonType.YES, ButtonType.NO);
Replace by file chooser

2022-03-28 05:58 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +        System.getProperty("user.dir") + File.separator + "Export" + File.separator + "Export.csv";
okay will do that

2022-03-28 06:01 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +            ButtonType.YES, ButtonType.NO);
okay will do that what about CCS ?

2022-03-28 08:56 UTC, robinschmid commented
@Tarush-Singh35  Thanks for also working on #608 
When working with git, try to isolate the issues and features that you are working on. Create one branch (always from the latest master), open separate pull requests and link to the issue. 
This makes it much easier to review and get merged. I think the CCS was ready - but now we should try to finalize the other part and get it all merged in one.

2022-03-28 09:13 UTC, robinschmid commented on src/main/resources/mzmineversion.properties
> +version.semver=3.0.13
Merge the current mzmine master to resolve the conflict.

2022-03-28 09:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
Can you apply the google style again (which is in the project root directory for IntelliJ or Eclipse)
This should be individual imports not *

2022-03-28 09:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +      PrintWriter pw = new PrintWriter(writer);
Best way is to use try-with-resources patter. The BufferedWriter is autocloseable - this way you do not need a finally - close block, which is deprecated for removal in the jdk.
```
try (BufferedWriter writer = Files.newBufferedWriter(file.toPath(), StandardCharsets.UTF_8)) {
   // export all
} catch (IOException e) {
}
```

2022-03-28 09:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +        System.getProperty("user.dir") + File.separator + "Export" + File.separator + "Export.csv";
+1 for the filechooser.
The best would be if you could use a FileChooser and add + select only one .tsv ExtensionFilter
`new ExtensionFilter("comma-separated values", "*.csv")`

2022-03-28 09:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummary.fxml
> +            <Button fx:id="exportfeature" alignment="TOP_CENTER" mnemonicParsing="false" onAction="#exportRecord" text="Export" GridPane.columnIndex="1" GridPane.halignment="RIGHT" GridPane.rowIndex=
I have no clue why it actually works. Both the "Open in batch" and "Eport" buttons are in the same column and row of the gridpane-maybe they get automatically wrapped.
Maybe you could wrap them into a ButtonPane or just a HBox with 5 pt spacing

2022-03-28 09:28 UTC, robinschmid commented
Looks good so far.

- [ ]

2022-03-28 09:35 UTC, robinschmid commented
CCS looks good to me.
Only the export needs a few more items:

- [ ] Merge master to resolve conflicts
- [ ] wrap the two buttons into an HBox with 5 pt spacing or ButtonBar. 
- [ ] use a file chooser and add `new ExtensionFilter("comma-separated values", "*.csv")` (should be selected as default)
- [ ] check for array and concatenate to string (like in SimpleParameterSet.toString() (see below)

### Array to string
```
if (value.getClass().isArray()) {
  s.append(Arrays.toString((Object[]) value));
} else {
  s.append(value.toString());
}
```

2022-03-29 04:39 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummary.fxml
> +            <Button fx:id="exportfeature" alignment="TOP_CENTER" mnemonicParsing="false" onAction="#exportRecord" text="Export" GridPane.columnIndex="1" GridPane.halignment="RIGHT" GridPane.rowIndex=
i will do that

2022-03-29 04:40 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
i had applied it idk why its not working i will apply it again

2022-03-29 04:47 UTC, Tarush-Singh35 commented on src/main/resources/mzmineversion.properties
> +version.semver=3.0.13
i will merge the current mzmine master

2022-03-29 07:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +            logger.info(() -> "Raw data file " + File.getName() + " does have a CCS calibration.");
No worries at all. Thanks for you commitment. We made great progress.

2022-03-29 07:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +            ButtonType.YES, ButtonType.NO);
The CCS is great. We could have merged it now. But with the other changes we should first finish this completely.

2022-03-29 07:13 UTC, robinschmid commented on src/main/resources/mzmineversion.properties
> +version.semver=3.0.13
thanks

2022-03-29 07:14 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
Did it fix this?

2022-03-30 09:02 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
![googleStyle](https://user-images.githubusercontent.com/86368099/160794106-23bcdc2f-3283-497a-af6a-9a1e8b838bda.png)

2022-03-30 09:11 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +      PrintWriter pw = new PrintWriter(writer);
done. Thanks for the Help

2022-03-30 18:48 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +        System.getProperty("user.dir") + File.separator + "Export" + File.separator + "Export.csv";
done with file chooser, also i have given the extension filter for all file as well as CSV. Any other extension filter that i should provide? @robinschmid 
![FLS](https://user-images.githubusercontent.com/86368099/160908979-154cb28e-e6a3-49df-9a7e-4d7fe10cc808.png)

2022-03-30 18:49 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummaryController.java
> +            ButtonType.YES, ButtonType.NO);
i will try to complete it by today

2022-03-30 19:11 UTC, Tarush-Singh35 commented
> CCS looks good to me. Only the export needs a few more items:
> 
> * [ ]  Merge master to resolve conflicts
> * [ ]  wrap the two buttons into an HBox with 5 pt spacing or ButtonBar.
> * [ ]  use a file chooser and add `new ExtensionFilter("comma-separated values", "*.csv")` (should be selected as default)
> * [ ]  check for array and concatenate to string (like in SimpleParameterSet.toString() (see below)
> 
> ### Array to string
> ```
> if (value.getClass().isArray()) {
>   s.append(Arrays.toString((Object[]) value));
> } else {
>   s.append(value.toString());
> }
> ```

Thanks for The Array to String code I realized that value of File and Spectral Library has Array reference @robinschmid i have made the changes

2022-04-01 12:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/FeatureListSummary.fxml
> +            <Button fx:id="exportfeature" alignment="TOP_CENTER" mnemonicParsing="false" onAction="#exportRecord" text="Export" GridPane.columnIndex="1" GridPane.halignment="RIGHT" GridPane.rowIndex=
Looks way better

2022-04-01 13:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
> +import io.github.mzmine.datamodel.*;
okay weird I thought its not in the style

2022-04-01 13:50 UTC, robinschmid commented
Changes look good. Just merge the master to clear the conflicts.

2022-04-02 15:07 UTC, Tarush-Singh35 commented
> @Tarush-Singh35 Thanks for also working on #608 When working with git, try to isolate the issues and features that you are working on. Create one branch (always from the latest master), open separate pull requests and link to the issue. This makes it much easier to review and get merged. I think the CCS was ready - but now we should try to finalize the other part and get it all merged in one.

@robinschmid

2022-04-02 15:07 UTC, closed without merging