Massvoltammogramme
mzmine/mzmine3 pull request #701
Opened 2022-05-30 12:16 UTC by WesMark

Added module for visualization of massvoltammograms and functionality to calculate EC/MS potentials
![mvWorkingSpace](https://user-images.githubusercontent.com/103106910/170990274-5786f6fe-e9a6-4793-9fbe-7f24738c6b29.png)
.

2022-05-30 12:58 UTC, tomas-pluskal commented
This looks great, thank you for the contribution.
Pardon my ignorance, but what is a massvoltammogram? :)

2022-05-30 13:37 UTC, robinschmid commented
Thanks for your first contribution. 
The outcome is really nice.

2022-05-31 09:51 UTC, WesMark commented
> This looks great, thank you for the contribution. Pardon my ignorance, but what is a massvoltammogram? :)

Thank you! A massvoltammogram is a 3d plot used in the simulation of metabolic pathways by the hyphenation of electrochemistry and mass spectrometry (EC/MS).

2022-06-01 07:55 UTC, SteffenHeu reviewed
They for the PR, i have added some comments.

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/ims_featurevisualizer/infovisualizer/InfoVisualizerModule.java
> +package io.github.mzmine.modules.visualization.ims_featurevisualizer.infovisualizer;
i think you moved a package by accident

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/ims_featurevisualizer/infovisualizer/InfoVisualizerParameters.java
> +package io.github.mzmine.modules.visualization.ims_featurevisualizer.infovisualizer;
i think you moved a package by accident

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/ims_featurevisualizer/infovisualizer/InfoVisualizerWindow.java
> +package io.github.mzmine.modules.visualization.ims_featurevisualizer.infovisualizer;
i think you moved a package by accident

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/ExtendedPlot3DPanel.java
> +  //Methods to add the data to the plot for later export.
use javadoc for this
/**
 */

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/ExtendedPlot3DPanel.java
> +public class ExtendedPlot3DPanel extends Plot3DPanel {
Add javadoc to describe the use of this class

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/ExtendedPlotToolBar.java
> +final JToggleButton moveButton = buttonCenter;
format + javadoc

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltammogramExport.java
> +    final FileChooser.ExtensionFilter extensionFilterCSV = new ExtensionFilter("XY-File", ".xy");
call it .csv, we never use .xy in MZmine

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltammogramExport.java
> +          folderPath + "\\" + fileName + "_" + scan[0][2] + "_mV.xy")) {
use File.separator instead of "\\", this will lead to issues with linux/unix systems.

or: new File(folderPath, fileName + "_" + scan[0][2] + "_mV.xy") should create a new file with the correct path.

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/ExtendedPlot3DPanel.java
> +  private List<double[][]> rawScans;
detail the data layout for rawScans

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltammogramTab.java
> +    return null;
this is annotated as `@NotNull` but returns null. Return an empty list via List.of() instead

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltammogramTab.java
> +    if(mzRangeParameter.showSetupDialog(true) != ExitCode.OK){return;}
format

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltammogramTask.java
> +  private final double tubingLength = MassvoltammogramParameters.tubingLengthMM.getValue();
i'm surprised this works. Pass the parameterset given to the MassVolatamogramModule to this task and get the parameters from there.

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltamogramUtils.java
> +public class MassvoltamogramUtils {
VoltaMMogram, or?

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltamogramUtils.java
> +   * @return Returns a list of all scans with the given step size inside the potential range.
detail the data layout of the return value

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltamogramUtils.java
> +   * @return Returns list of multidimensional arrays, with each of them containing m/z, intensity
how are the values accessed in the array?

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltamogramUtils.java
> +  public static double getDivisor(double maxIntensity) {
this is a funny implementation, i'd have used log10 instead :D

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/massvoltammogram/MassvoltamogramUtils.java
> +   * Removes datapoints with low intensity values.
explain that 0.1% of max intensity is classified as "noise"

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +  public static double[][] removeExtraZeros(double[][] scan) {
This functions also exists in the MassvoltammogramUtils, or? Are they equivalent? Then one should be removed.

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +  public static double getMaxIntensity(List<double[][]> scans){
This is unnecessary, you can use Scan.getBasePeakIntensity instead.

2022-06-01 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +  public static double getMinMZ(List<double[][]> scans){
also unnecessary, Scan.getMzRange().lowerEndpoint

2022-08-05 14:59 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/features/types/numbers/PotentialType.java
> +package io.github.mzmine.datamodel.features.types.numbers;
add license

2022-08-05 15:22 UTC, SteffenHeu requested changes

2022-08-05 15:22 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/parameters/parametertypes/selectors/ScanSelection.java
> +  public Scan getScanAtRt(RawDataFile file, float retentionTime) {
Javadoc: returns the closest scan to the given retention time matching this scan selection.

2022-09-20 14:52 UTC, SteffenHeu approved these changes

2022-09-20 14:52 UTC, merged

2022-09-27 11:53 UTC, omokshyna commented
@WesMark Hi, thanks again for your contribution! Could you also consider adding a description to MZmine documentation (https://mzmine.github.io/mzmine_documentation/contribute.html) or sharing the references that would be useful for the documentation?