Waterdev
mzmine/mzmine3 pull request #735
Opened 2022-06-13 15:48 UTC by Tarush-Singh35

Waters.raw Structure for GSOC 2022 1st commit(includes WatersImportTask, WatersImportParameters, WatersImportModule,Main menu,Masslynx & jna jar )
ignore TDFimportTask

2022-06-13 16:14 UTC, Tarush-Singh35 commented
> Please be careful about including unnecessary changes in your pull requests - it seems you included a change to TDFImportTask.java, which is only adding whitespace.

Yeah I'll be careful I did not see that coming

2022-06-13 16:18 UTC, Tarush-Singh35 commented
> Great that we can track the progress here. If the checks fail - try to fetch and merge the latest master branch and push

will do that thanks

2022-06-14 14:41 UTC, SteffenHeu reviewed
Looks good so far. I added a few comments. 
And i have some general things:
- prefer local variables over fields if possible
- apply the proper formatting
- be more descriptive with variable/object names

TODO:
- find out if the file has the ion mobility dimension. 
  - maybe via GetDriftScanCount or GetDriftTime and see what they return.

2022-06-14 14:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +                obj.GetFunctionType(i)==MassLynxFunctionType.TOFM?MassLynxFunctionType.TOFM.getValue():0;
this is not readable. refactor to a method and expand it to actual if or switch statements.

2022-06-14 15:13 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +  private Scan scan;
Global variable to store scan of masslynx and simplescan

2022-06-14 15:13 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +  private MassLynxRawInfoReader obj;
done

2022-06-14 15:16 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +      this.funcval = obj.GetFunctionCount();// Gets the number of function in Raw file
done

2022-06-14 15:17 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        this.scanvalue = obj.GetScansInFunction(i);
done

2022-06-14 16:06 UTC, Tarush-Singh35 commented
> Looks good so far. I added a few comments. And i have some general things:
> 
> * prefer local variables over fields if possible
> * apply the proper formatting
> * be more descriptive with variable/object names
> 
> TODO:
> 
> * find out if the file has the ion mobility dimension.
>   
>   * maybe via GetDriftScanCount or GetDriftTime and see what they return.

checked the value of driftscancount we have some int values that are coming from raw file also need to know what is the scan number we are providing in simplescan constructor is it the total scan value or individual scan value

2022-06-15 14:43 UTC, SteffenHeu commented
Todo:
- Create intermediate Scan object that just contains the meta data (continuum, ms level, ion mode, mz range, function number, number in function, retention time
- sort all objects by retention time (ascending)
- create SimpleScan from the intermediate object by a method that takes a scanNumber and the rawScanReader

2022-06-16 13:08 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        int scanvalue = massLynxRawInfoReader.GetScansInFunction(i);
numScans

2022-06-16 13:10 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +    //Sorting of intermediatescanarray by retention time
implement the sorting
List.sort

2022-06-16 13:12 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +  private ArrayList<SimpleScan> getSimpleScan(ArrayList<IntermediateScan> intermediatescanarray,
move this method to the IntermediateScan class, pass the rawScanReader and the scanNumber as a parameter

2022-06-16 15:28 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +    //Sorting of intermediatescanarray by retention time
looking for a better sorting algorithm over inbuilt sort

2022-06-17 16:00 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        simpleScanArrayList.add(simpleScan);
pass k here as what you call "numscan" in the Intermediate scan. Currently numscan is not unique, because it will be passed from the loop with j. 
So you don't need to save the numscan in the IntermediateScan, you only need it here when you create the simple scan.

2022-06-17 16:00 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +      e.printStackTrace();
use logger.log(Level.WARNING, e.getMessage(), e); here

2022-06-17 16:01 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +  private boolean isIonMobilityFile(MassLynxRawInfoReader massLynxRawInfoReader)
does it work as eppected?

2022-06-17 16:44 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +  private boolean isIonMobilityFile(MassLynxRawInfoReader massLynxRawInfoReader)
yes it was giving error so i am passing false value in catch.

2022-06-17 16:48 UTC, Tarush-Singh35 commented
any todo's for the week @SteffenHeu ? also can you tell me about MS or MS2 implementation so that i can look into TOFM

2022-06-17 17:01 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        simpleScanArrayList.add(simpleScan);
okay i am not saving numscan in intermediate scan but if i am not using intermediatescanarray to get the sorted value of intermediate scan then what is the point of sorting the intermediate scan.

2022-06-17 17:03 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        simpleScanArrayList.add(simpleScan);
> pass k here as what you call "numscan" in the Intermediate scan. Currently numscan is not unique, because it will be passed from the loop with j. So you don't need to save the numscan in the IntermediateScan, you only need it here when you create the simple scan.

also(pass k here as what you call "numscan" in the Intermediate scan) you are talking about getscan function right? also objects that will be used will be from intermediatescanarray

2022-06-17 19:16 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        simpleScanArrayList.add(simpleScan);
> okay i am not saving numscan in intermediate scan but if i am not using intermediatescanarray to get the sorted value of intermediate scan then what is the point of sorting the intermediate scan.

We want to sort all scans from all functions by retention time, not by their index in the "raw function". This is to maintain the accordance with mzmines data model

2022-06-17 19:17 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        simpleScanArrayList.add(simpleScan);
> also(pass k here as what you call "numscan" in the Intermediate scan) you are talking about getscan function right? also objects that will be used will be from intermediatescanarray

Yes exactly

2022-06-18 04:06 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        simpleScanArrayList.add(simpleScan);
getting error "invalid scan number" in IntermediateScan from rawscanreader

2022-06-20 07:22 UTC, SteffenHeu commented
If everything works so far, you can start with the ion mobility loading.

Background: 
- In ion mobility, there is more than one scan per retention time. 
- These scans are called drift scans in the waters API.
- All the drift scans acquired at the same time belong to a "frame", so every frame contains a specific number of mobility scans.
- There should be methods such as GetDriftScanCount taking the scan index and the function number as 

TODO:
- fix the build issue
- Create IntermediateFrame, which extends IntermediateScan and has an additional int to store the number of drift scans (dont actually query the drift scans)
- check if the number of drift scans and the drift values are the same for every function in the ion mobility files
- create a method "toFrame" for the IntermediateFrame, which returns a SimpleFrame

2022-06-21 16:01 UTC, Tarush-Singh35 commented
> If everything works so far, you can start with the ion mobility loading.
> 
> Background:
> 
> * In ion mobility, there is more than one scan per retention time.
> * These scans are called drift scans in the waters API.
> * All the drift scans acquired at the same time belong to a "frame", so every frame contains a specific number of mobility scans.
> * There should be methods such as GetDriftScanCount taking the scan index and the function number as
> 
> TODO:
> 
> * fix the build issue
> * Create IntermediateFrame, which extends IntermediateScan and has an additional int to store the number of drift scans (dont actually query the drift scans)
> * check if the number of drift scans and the drift values are the same for every function in the ion mobility files
> * create a method "toFrame" for the IntermediateFrame, which returns a SimpleFrame

We have only one GetDriftScanCount taking the function number as a parameter and DriftTime taking scancount and function number as a parameter and what do you mean by drift values, are you asking about drift time ?

2022-06-25 08:41 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +    //Sorting of intermediatescanarray by retention time
done

2022-07-04 08:49 UTC, SteffenHeu requested changes

2022-07-04 08:49 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +    setStatus(TaskStatus.FINISHED);
there should be a branch here, depending on if the file is an IMS file or not

2022-07-04 08:49 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        numscan_array.add(total_scanvalue_in_each_function);
what's the use of this list?

2022-07-04 08:49 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        for (int numscan = 0; numscan < numscan_array.get(functioncount); ++numscan) {
Ok, so: don't loop over both (totalfunctioncount and scansinfunction) here. you only need to loop over the intermediatescanarray list. the index+1 of the intermediatescan will be the scan number of the simple scan.

2022-07-04 08:49 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateScan.java
> +  public static Comparator<IntermediateScan> obj1 = new Comparator<IntermediateScan>() {
make intermediatescan implement comparable and remove this nested anonymous class.

2022-07-04 08:49 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateScan.java
> +  public SimpleScan getScan(int numscan, MassLynxRawScanReader rawscanreader)
having numscan as a parameter and as a field is hard to read. the variable passed as a parameter should be the mzmine scan number while the field numscan should be the value passed to the rawscanreader.

2022-07-04 08:49 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateFrame.java
> +  public SimpleFrame toframe()
this function probably needs similar parameters to the toScan function....

2022-07-04 08:49 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateFrame.java
> +  public IntermediateFrame(RawDataFile newMZmineFile, boolean iscontinuum, int mslevel,
the Frame needs to know the number of drift scans in a frame. see my previous explanation

2022-07-04 16:47 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +        for (int numscan = 0; numscan < numscan_array.get(functioncount); ++numscan) {
done

2022-07-04 16:53 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateScan.java
> +  public static Comparator<IntermediateScan> obj1 = new Comparator<IntermediateScan>() {
done

2022-07-04 16:53 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateScan.java
> +        }
done

2022-07-04 17:03 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateScan.java
> +  public SimpleScan getScan(int numscan, MassLynxRawScanReader rawscanreader)
passed mzmine scan number in simple scan and field numscan in rawscanreader.

2022-07-04 17:41 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +    setStatus(TaskStatus.FINISHED);
so if anyone function has a driftscancount then that raw file is IonMobilityFile also the error still persist for some of the raw files that only 2 function has driftscancount while the 3rd throws an exception of "file cannot open"

2022-07-05 07:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +    setStatus(TaskStatus.FINISHED);
Ok. If two functions work for the drift scan count, then we should assume it is an IMS file. That can be judged from the first one. 
I found out that waters does some reference measurement in some of their functions. We don't need that reference function in MZmine. We can add a `boolean isReferenceMeasurement(int functionNumber)` method. If that method returns true, we can skip loading the scans of that function.
For now, the method can always return true if the number is 3 (or 2, does it start at 1 or 0?).

2022-07-05 07:55 UTC, SteffenHeu commented
push the changes please

2022-07-05 14:16 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +    setStatus(TaskStatus.FINISHED);
you need to check one function if it has drift scans, to determine if it is an ims or regular file. when loading the individual functions you need to check the function number and ignore the reference function.

2022-07-05 14:18 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateScan.java
> +/*  public static Comparator<IntermediateScan> obj1 = new Comparator<IntermediateScan>() {
remove

2022-07-05 14:18 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/import_waters/WatersImportTask.java
> +      //ArrayList<SimpleScan> simpleScanArrayList = new ArrayList<>();
remove all the commented code that is not needed anymore, makes it harder to read.

2022-07-05 15:42 UTC, SteffenHeu commented
Next step: Implement the getFrame method. During this, every drift scan belonging to the actual frame shall be loaded. Using a for loop over getDriftScanCount load the individual drift scans. You can use the `io.github.mzmine.datamodel.impl.BuildingMobilityScan` for that. As scan number (see the constructor) use a counter variable starting from 1. The counter shall be restarted for every frame.

2022-07-05 16:48 UTC, Tarush-Singh35 commented on src/main/java/io/github/mzmine/modules/io/import_waters/IntermediateFrame.java
> +  public SimpleFrame toframe()
done

2022-07-05 17:07 UTC, Tarush-Singh35 commented
> Next step: Implement the getFrame method. During this, every drift scan belonging to the actual frame shall be loaded. Using a for loop over getDriftScanCount load the individual drift scans. You can use the `io.github.mzmine.datamodel.impl.BuildingMobilityScan` for that. As scan number (see the constructor) use a counter variable starting from 1. The counter shall be restarted for every frame. To the simple frame, set the mobility scans via the SimpleFrame.setMobilityScans method.

2022-07-05 17:07 UTC, closed without merging