Test visualizer
mzmine/mzmine3 pull request #753
Opened 2022-06-28 11:51 UTC by sanbit876

I have created a test_visualizer using a synthetic dataset available at the GraphStream Library website in order to check the performance of the (GRAPH_IN_ANOTHER_THREAD) threading model.

2022-07-01 09:01 UTC, robinschmid requested changes

2022-07-01 09:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/test_visualizer/NetworkTestVisualizer.java
> +    if (Values[1].equals("Random generator")) {
as mentioned before - better not use strings as return types. This should be [0]  but better use parameters class

2022-07-01 09:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/test_visualizer/NetworkTestVisualizer.java
> +      gen.end();
This code segment is redundant. IntelliJ should tell you that you can extract this from the if else. You only set the generator here so rather use a switch. This can be done with strings (below) but then you need a default. With enum you can control that all cases are covered:
```java 
Generator generator = switch (Values[0]) {
    case "Random generator" -> new RandomGenerator(2);
    case "Barabasi-Albert generator" -> ...
    default -> throw new IllegalStateException("Unexpected value: " + Values[0]);
};
```

2022-07-01 09:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/test_visualizer/NetworkTestVisualizer.java
> +      viewer.enableAutoLayout();
next step try to apply the force directed layout. without using the auto layout

2022-07-01 17:13 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/test_visualizer/NetworkTestVisualizer.java
> +  static int NodeValue=0;
ok

2022-07-01 17:14 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/test_visualizer/NetworkTestVisualizer.java
> +    graph=new SingleGraph(Values[0]);
changed the graph type to multi graph

2022-07-01 17:14 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/test_visualizer/NetworkTestVisualizer.java
> +    return GenaratingAlgo + "#" + NodeValue;
Created a separate class named openSetupDialog for this

2022-07-01 17:17 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/test_visualizer/NetworkTestVisualizer.java
> +      viewer.enableAutoLayout();
Rightnow  i have used "disableAutoLayout" option.... can u tell me how i can use a force directed layout like are their any function available or i have to create one??

2022-07-04 09:02 UTC, sanbit876 commented on build.gradle
> +    implementation 'org.postgresql:postgresql:42.3.6'
I have never made any changes to library..I only pushed the changes i made into visualizer files, i don't know why these files are included with my changes, I have reset the build file

2022-07-04 09:27 UTC, sanbit876 commented
I have updated the build file and now everything is fine

2022-07-04 09:30 UTC, sanbit876 commented
Whenever i try the "fetch upstream" option i get an error saying that i have merge conflicts which i generally resolve by manually editing the mzmine.properties file...Is it the the right way??

2023-12-19 08:00 UTC, closed without merging