Start dia msms impl
mzmine/mzmine3 pull request #768
Opened 2022-07-07 11:09 UTC by SteffenHeu

still have this lying around, creating pr so it is build and people can test it

2022-09-23 19:43 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/featuredata/FeatureDataUtils.java
> +  public static double calculateMz(@NotNull final IonSeries series,
calculateCenterMz would be more meaningful

2022-09-23 21:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    final MenuItem showDiaMirror = new ConditionalMenuItem("Mirror uncleaned DIA spectrum",
What is an uncleaned spectrum?

2022-09-23 21:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/ArrayUtils.java
> +  public static double back(double[] array) {
this method does not provide any benefit. Also the name is not telling what it does. lastElement would be more precise.
I dont mind having it with that name but you could also just use the code directly

2022-09-23 21:15 UTC, robinschmid commented on src/test/java/tdfimportest/RangeMapTest.java
> +    ranges.forEach((k, v) -> logger.info(k + " - " + v));
maybe remove. Its not testing anything

2022-09-23 21:15 UTC, robinschmid commented on src/test/java/tdfimportest/RangeMapTest.java
> +  }
remove

2022-09-26 08:36 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrParameters.java
> +      MZmineCore.getConfiguration().getIntensityFormat(), 1E3);
It's basically the minimum highest intensity in the ADAP chromatogram builder

2022-09-26 08:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +                SpectraMerging.createNewNonOverlappingRange(ms2Eics, feature.getRawDataPointsMZRange()),
yeah it does, but i want highly intense ms2 eics to have their full range, lower intense ones may be cut off

2022-09-26 08:56 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +          feature.getRepresentativeScan());
that's a good point. 
However, im not sure how that will behave with prominent fragment ions. Imagine an intensive PC elutes from the column with some tailing. 184 is detected at the time in the MS2. Due to the tailing the MS1 peak is quite long and fades out. during that process it might be that another PC elutes, causing a rise in the 184 again, destroying the correlation

2022-09-26 08:56 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +            && Math.pow(correlationData.getPearsonR(), 2) > minPearson) {
good to know :D

2022-09-26 08:57 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +            && Math.pow(correlationData.getPearsonR(), 2) > minPearson) {
so IIN also looks at R and not R^2?

2022-09-30 15:49 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +            && Math.pow(correlationData.getPearsonR(), 2) > minPearson) {
Yes. Its nice because anti correlated patterns are a direct exclusion reason

2022-09-30 16:30 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +          feature.getRepresentativeScan());
I mean we try to split those features... and then I would just take the overlap, where both features were detected.
Maybe you could setup a relative intensity threshold that is applied to both peaks. so if any of them fall under 5% you stop

2022-09-30 16:42 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +          feature.getRepresentativeScan());
But only the MS1 peak is resolved and not the MS2

2022-09-30 17:26 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +          feature.getRepresentativeScan());
Thats true but you could take the 5% or something as a correlation cutoff. Then it is sort of resolved.

2022-10-18 00:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrParameters.java
> +      MZmineCore.getConfiguration().getIntensityFormat(), 1E3);
okay

2022-10-18 00:32 UTC, robinschmid commented
FeatureCorrelationUtils.DIA could get some javadoc on the class and methods: general usage and info

2022-10-18 00:42 UTC, robinschmid requested changes
Only a few things. We can merge it after that and maybe incorporate some of the ideas later

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/featuredata/FeatureDataUtils.java
> +  public static double calculateCenterMz(@NotNull final IonSeries series,
General question for this. When we create the series we sometimes add 0 intensities to have better peak shapes. I think we should exclude those data points here for the center calc

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/impl/SimplePseudoSpectrum.java
> +public class SimplePseudoSpectrum extends SimpleScan implements PseudoSpectrum {
Is it good to inherit from SimpleScan here and not from AbstractStorableSpectrum. SimpleScan carries so many other fields and is mostly used for real MS scans

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/PseudoSpectrumType.java
> +  LC_DIA, GC_EI;
What will be the difference?
Processing will be different but the datastructure itself?

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrModule.java
> +    return "DIA MS2 pseudo MS2 builder (experimental)";
DIA pseudo MS2 builder (experimental)
MS2 is doubled

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +                SpectraMerging.createNewNonOverlappingRange(ms2Eics, feature.getRawDataPointsMZRange()),
okay

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    showDiaIons.setOnAction(e -> showDiaMsMsIons());
Maybe more Show DIA pseudo MS2
This should also work if no feature is selected. Then you do row.getBestFragmentation

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    showDiaIons.setOnAction(e -> showDiaMsMsIons());
Oh okay. This method actually shows the feature shapes. So maybe call it Show DIA ion shapes

2022-10-18 00:42 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    showDiaMirror.setOnAction(e -> showDiaMirror());
Why is this only available for IMS?

2022-10-18 08:50 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/impl/SimplePseudoSpectrum.java
> +public class SimplePseudoSpectrum extends SimpleScan implements PseudoSpectrum {
since pseudospectrum extends scan, i thought it was the logical solution. There is still some older stuff that requires a scan for visualisation in the spectra plots, which i do not want to break

2022-10-18 08:51 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/datamodel/PseudoSpectrumType.java
> +  LC_DIA, GC_EI;
I think there might be different applications in the future, so i want to introduce the datamodel for it right away to keep current projects compatible with those new modules.

2022-10-18 08:54 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    showDiaMirror.setOnAction(e -> showDiaMirror());
because it takes the peaks from the mobility fwhm and correlates them using the ms1 shape

2022-10-18 20:19 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/impl/SimplePseudoSpectrum.java
> +public class SimplePseudoSpectrum extends SimpleScan implements PseudoSpectrum {
Might still break though... not all functions and data types are supported once pseudo spectrum is generated.

2022-10-18 20:19 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/PseudoSpectrumType.java
> +  LC_DIA, GC_EI;
okay

2022-10-18 21:33 UTC, robinschmid commented
Great thanks for all the changes.

2022-10-18 21:34 UTC, merged