[GSOC'22 Project] Latest version of FeatureList Networking Visualization Module
mzmine/mzmine3 pull request #825
Opened 2022-08-01 18:46 UTC by sanbit876

2022-08-03 10:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +          }
we should make the switch exhaustive so handle all cases and then get rid of the default. This way we will se that we need to handle new cases here

2022-08-03 10:29 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +  protected Node selectedNode;
selected node should be an array or a list. 
array might be nice considering that we could have a method 
`setSelectedNodes(@Nullable Node... selectedNodes)`

this way we can set one or multiple nodes

2022-08-03 10:31 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +    graph.setAttribute("Layout.frozen"); //Block the layout algorithm
Can we just do this here without checking if the layout is already finished?
The layout runs multiple iterations to stabilize. So will this always work or does it work sometimes?

2022-08-03 10:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +    view.setStyle("-fx-effect: innershadow(three-pass-box, gray, 12 , 0.5, 1, 1);");
why the inner shadow? is it to plain otherwise?

2022-08-03 10:36 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +      selectedNode = (Node) view.findGraphicElementAt(EnumSet.of(InteractiveElement.NODE), e.getX(),
create method like discussed above `setSelectedNode` maybe with a flag `boolean notifyListeners`
its gonna be called from here and from the listener itself.
If the listener sets the selected nodes we of course do not call the listener again

2022-08-03 10:38 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +  public Node getSelectedNode() {
array or list

2022-08-03 10:39 UTC, robinschmid commented on src/test/java/modules/TestNodeNeighbourMethod.java
> +  public Graph CreateGraph()
lower case createGraph

2022-08-03 10:39 UTC, robinschmid commented on src/test/java/modules/TestNodeNeighbourMethod.java
> +  {
apply default style format

2022-08-03 10:40 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +          }
ok

2022-08-03 10:41 UTC, robinschmid commented on src/test/java/modules/TestNodeNeighbourMethod.java
> +    Graph graph = new MultiGraph("Test-Graph");
Where is the graph that you manually entered?

2022-08-03 10:42 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +    graph.setAttribute("Layout.frozen"); //Block the layout algorithm
As per my observations, the "layout.frozen" attribute sets after the graph is stabilized

2022-08-03 10:43 UTC, robinschmid commented on src/test/java/modules/TestNodeNeighbourMethod.java
> +  public Stream<Node> streamNodeNeighborsBreadthFirst(Node node, int edgeDistance) {
You should push this code into the main code base and only have tests here that actually check some numbers.
Maybe `NetworkUtils` or `GraphStreamUtils`

2022-08-03 10:47 UTC, robinschmid commented on src/test/java/modules/TestNodeNeighbourMethod.java
> +    streamNodeNeighborsBreadthFirst(CreateGraph().getNode("1"),3).forEach(s -> System.out.println(s.getId()));
this should be the actual test code so do something like counting the number of unique nodes returned
Assertions.assertEquals(expected, actual);

with `graph.nodes().distinct().count()`

2022-08-03 11:58 UTC, robinschmid commented on src/test/java/modules/TestNodeNeighbourMethod.java
> +            neighbor -> streamNodeNeighborsBreadthFirst(neighbor, edgeDistance - 1).distinct());
the distinct here actually does not work as intended because we still end up with duplicates.

I think the best way would actually be to have two methods and use a map to track visited nodes with their remaining edge distance
Both methods should go into the NetworkUtils or something similar

```java

/**
 * Unique list of node neighbors within edge distance
 *
 * @param node         node to visit and all its neighbors
 * @param edgeDistance number of consecutive edges connecting neighbors
 * @return list of all neighbors + the initial node
 */
public List<Node> getNodeNeighbors(Node node, int edgeDistance) {
    Object2IntOpenHashMap<Node> visited = new Object2IntOpenHashMap<>();
    visited.put(node, edgeDistance);
    addNodeNeighbors(visited, node, edgeDistance);
    return new ArrayList<>(visited.keySet());
    }

/**
 * Add all neighbors to the visited list and check for higher edgeDistance to really capture all
 * neighbors
 *
 * @param visited map that tracks visited nodes and their edgeDistance
 * @param node
 * @param edgeDistance
 */
private void addNodeNeighbors(Object2IntOpenHashMap<Node> visited, Node node, int edgeDistance) {
final int nextDistance = edgeDistance-1;
    node.neighborNodes().forEach(neighbor -> {
    if (visited.getOrDefault(neighbor, -1) < edgeDistance) {
    // was never visited or was visited with lower edgeDistance - visit this time 
    visited.put(neighbor, nextDistance);
    if (edgeDistance > 1) {
    addNodeNeighbors(visited, neighbor, nextDistance);
    }
    }
    });
    }
```

2022-08-04 08:38 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +    graph.setAttribute("Layout.frozen"); //Block the layout algorithm
Okay so lets try it this way

2022-08-04 08:38 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +    view.setStyle("-fx-effect: innershadow(three-pass-box, gray, 12 , 0.5, 1, 1);");
Oh we can keep it for now. I will look at it once we are further with the implemented methods

2022-08-05 11:57 UTC, robinschmid commented on src/test/java/modules/GraphStreamUtils.java
> +  {
set the mzmine code formatter in IntelliJ and you can have it automatically run before commiting changes

2022-08-05 12:06 UTC, robinschmid commented on src/test/java/modules/GraphStreamUtils.java
> +  public void testmethod()
Your approach to testing was correct before. See this as a reference, they have more info on unit testing.
https://www.baeldung.com/junit-before-beforeclass-beforeeach-beforeall#before
1. The class name should be something like GraphStreamTests or GraphStreamUtilsTests (ending with Tests) and located in the test directory. 
2. only code that is necessary for the testing. So initializing stuff like the createGraph should be done in a method annotated with @Before or @BeforeClass (see link)
3. the actual logic should go in to the main code base, maybe in main/java/....mzmine/util/GraphStreamUtils
4. Make all methods in the utils static - as they do not have a state. So you should access them by GraphStreamUtils.getNodeNeighbors

2022-08-05 12:08 UTC, robinschmid commented on src/test/java/modules/GraphStreamUtils.java
> +    Assertions.assertEquals("FABJCED",traversingSequence);
Make sure the output actually matches. I think list.toString will not join the strings like this. You could use String.join("", myList)

2022-08-05 12:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +    neighbours = Integer.parseInt(nodeNeighbours.getValue().toString());
you can make an Intger spinner. Also minimum should be 1, maximum should be huge. can also be Integer.MAX_VALUE or similar
```java
    Spinner<Integer> spinner = new Spinner<>(1, 10000000,3,1);
    int neighbors = spinner.getValue();
```

2022-08-05 12:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +    updateGraphButton.setMaxWidth(Double.MAX_VALUE);
add an action to update the graph

2022-08-05 12:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +      if(!(mouseSelectedNodes.contains(node))) {
this variable is not declared. 
do 
Node[] selectedNodes
and use all selected Nodes and their neighbors here

2022-08-05 12:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +  {
apply style. and call them just selected nodes.

2022-08-05 12:18 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +  public List<Node> getmouseSelectedNode() {
you can auto generate those methods in intellij and then it is written the correct way. 
getSelectedNodes

you got two typos in there get**m**ouseSelectedNod**e(**)  (should be M and Node**s**)

2022-08-10 09:50 UTC, robinschmid commented on src/test/java/modules/GraphStreamUtilsTest.java
> +    return graph;
This needs to be a global variable. 
The idea is that @Before lets this run before the tests so you initialize all variables.
Then in the test yuo can just use graph

2022-08-10 10:43 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkGenerator.java
> +        graph.removeNode(i);
you cannot loop over some collection and remove at the same time. for this use an iterator. 
Or collect all elements that you want to delete and then delete them in a second loop.

2022-08-10 10:45 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +
You have to update the neighbors value somewhere...
Best to just use an IntegerProperty for everythin JavaFX and bind the valueProperty of the spinner to your neighbors value

2022-08-10 10:46 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +      generator.createGraphwithNeighboringNodes(graph,
adhere to standards. createGraph**W**ith

2022-08-10 10:47 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +          getNodeNeighbors(getMouseClickedNode(), neighbours));
we have to be kind of careful here. the clicked node will be a GraphicsNode and the graph object contains some other class from AbstractNodes

2022-08-10 10:48 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +    view.setStyle("-fx-effect: innershadow(three-pass-box, gray, 12 , 0.5, 1, 1);");
i do not like the shadow. it looks way different then all teh rest of mzmine

2022-08-10 10:56 UTC, robinschmid commented
Look at this
https://github.com/sanbit876/mzmine3/pull/4

2022-08-13 13:57 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FilteredGraph.java
> +  private MultiGraph filteredGraph;
FilteredGraph class is already a MultiGraph. 
So the main field that you have here should be the full graph. You can have a set method or you can pass the full graph in the constructor.

2022-08-13 14:01 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +  private Graph fullGraph;
FeatureNetworkPane should only contain things that are specific to the feature network.
the graph is a general field that should be in NetworkPane.
We only have one the FilteredGraph graph
Inside the filtered graph is a field fullGraphj

2022-08-13 14:03 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +      generator.createGraphWithNeighboringNodes(graph, GraphStreamUtils.getNodeNeighbors(getMouseClickedNode(),bNeighbors.get()));
here you need to call something like graph.setNodeFilter(n -> //check if node is in neighbor set)
this method should be inside FilteredGraph to set a filter onto the nodes

2022-08-13 14:06 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +   FilteredGraphUtils fgu = new FilteredGraphUtils();
Utils usually contain static methods but no state - so no non static fields.
so you never do new ...

2022-08-13 14:07 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +   fgu.addContentsOfFullGraph(fullGraph,graph);
just do something like graph (which is a FilteredGraph) graph.setFullGraph(fullGraph)

2022-08-13 14:09 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> +    graph = fg.getFilteredGraph();
dont understand what you do here.
You create a FilteredGraph and extract a filteredgraph from it... that does not make sense.
FilteredGraph is a graph

2022-08-13 14:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/NetworkPane.java
> -        e.consume();
why did you remove all of this. this is supposed to give mouse control

2022-08-13 14:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/FilteredGraphUtils.java
> +    originalGraph.nodes().forEach(aNode -> {
add a filteredGraph clear before that to be sure that it was empty

2022-08-13 14:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/FilteredGraphUtils.java
> +  public void addContentsOfFullGraph(Graph originalGraph, Graph filteredGraph) {
this can be logic inside the filteredgraph

2022-08-14 16:22 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +    });
I tell you to put this part of code into the FilteredGraph class and you push it from the FilteredGraphUtils to the FeatureNetworkPane which is obviously the wrong location because its supposed to be a specialized Pane. Whereas this code performs something that can be done with any Graph

2022-08-16 10:47 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +    graph.setInitialGraph(graph,graph.getFullGraph());
this does not make sense. passing graph and a field of graph to graph

2022-08-16 10:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FilteredGraph.java
> +  public void setInitialGraph(MultiGraph graph1,MultiGraph graph2) {
this does not make any sense. 
First there should be a way to set the fullGraph in the constructor or via a setter.
Then add all the methods for filtering to this class.
The update methode should use a filter and use the fullGraph, filter it and add all nodes and eged to MutiGraph fg = this;

2022-08-19 07:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    final MenuItem showInNetworkVisualizerItem = new MenuItem("Show in Network Visualizer");
Please conform to the other menu item titles.
just use "Feature network"

2022-08-19 07:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkGenerator.java
> +  public void createGraphWithNeighboringNodes(Graph graph, Set<Node> neighboringNodes) {
this is still in the wrong class. This should happen in the filtered graph

2022-08-19 07:14 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +  private final FilteredGraph fg = new FilteredGraph("Filtered-Graph");
Please read our conversations again. We are cycling through the same mistakes.
NetworkPane has a FilteredGraph graph that should be protected or accessible by getter

Why should there be two graphs in FeatureNetworkPane?

2022-08-19 07:19 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +  private final FilteredGraph fg = new FilteredGraph("Filtered-Graph");
I have created object of the FilteredGraph Class here for calling the setFullGraph function (inside the createnewgraph function) of the filteredgraph class in order to set the intial state of the graph (with all edges and nodes) to the full graph

2022-08-19 07:20 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkGenerator.java
> +  public void createGraphWithNeighboringNodes(Graph graph, Set<Node> neighboringNodes) {
okay... i will move it into the filteredgraph class

2022-08-19 07:20 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    final MenuItem showInNetworkVisualizerItem = new MenuItem("Show in Network Visualizer");
okay

2022-08-22 11:59 UTC, robinschmid requested changes

2022-08-22 12:24 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +      generator.createGraphWithNeighboringNodes(graph,
okay

2022-08-22 13:18 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkPane.java
> +    fg.setFullGraph(graph); //setting the full-graph generated to the filtered-graph
I have update the code:
graph.setFullGraph(graph)

2022-08-22 14:50 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    final MenuItem showInNetworkVisualizerItem = new MenuItem("Show in Network Visualizer");
you seem to not read my comments.
Please change it to "Feature network" to the letter.  All other items are also called this way without Show in because the menu is named Show

2022-08-22 14:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FilteredGraph.java
> +  MultiGraph fullGraph;
always private if possible. Limit the visibility as much as possible and only write getter and setters where needed

2022-08-22 14:54 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FilteredGraph.java
> +  MultiGraph fullGraph;
okay....i will make it private

2022-08-22 14:54 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FeatureNetworkGenerator.java
> +  public void createGraphWithNeighboringNodes(Graph graph, Set<Node> neighboringNodes) {
why is it still here

2022-08-22 14:58 UTC, sanbit876 commented on src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +    final MenuItem showInNetworkVisualizerItem = new MenuItem("Show in Network Visualizer");
okay i will change it..... i thought u were telling to change only the network-visualizer part

2022-08-22 15:05 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/visualization/networking/visual/FilteredGraph.java
> +  public void setNodeFilter(Set<Node> neighboringNodes) {
This is okay for the start but is not what I asked for. 
You should be able to write a real filter something like
setNodeFilter(Predicate<Node> filter)

2023-07-17 13:44 UTC, merged