Empty scans handling
mzmine/mzmine3 pull request #927
Opened 2022-10-03 09:39 UTC by omokshyna

Enabled handling of empty scans (having no available m/z range) in Raw Data Overview (previously table stopped loading at the empty scan), Filters (Crop filter & Scan by scan resample filter), and in ADAP feature detection. 
Added an option to filter out the empty scans in Crop filter.

![image](https://user-images.githubusercontent.com/2729783/193546716-69a77594-bf6e-4316-b70b-2659c9d0577e.png)

Added warning in "MS data files" tab for the uploaded files with empty scans.

![image](https://user-images.githubusercontent.com/2729783/193546804-a346defe-c036-4b96-9662-6cfb13b16534.png)

2022-10-04 07:06 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/mainwindow/MainWindowController.java
> +              Scans were detected as centroid but contain zero intensity values. This might indicate incorrect conversion by msconvert.
zero-intensity to make it clearer

2022-10-04 07:08 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/project/impl/RawDataFileImpl.java
> +      logger.warning("""
no need for a text block here

2022-10-04 08:02 UTC, omokshyna commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +        logger.info("Scan number " + s.getScanNumber() + "was found to be empty.");
"was empty"?

2022-10-04 08:02 UTC, omokshyna commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_cropfilter/CropFilterParameters.java
> +  public static final BooleanParameter emptyScans =
I understand your hesitation, but maybe it would be still nice to leave this option for users. It has a pretty scary warning that it will disrupt the numbering. But if you are absolutely against it, I can remove it

2022-10-04 08:04 UTC, omokshyna commented on src/main/java/io/github/mzmine/project/impl/RawDataFileImpl.java
> +      logger.warning("""
Is there anything that can be added to this warning, such as the possible reason for the empty scans? Or leave it as it is?

2022-10-04 08:05 UTC, omokshyna commented on src/main/java/io/github/mzmine/gui/mainwindow/MainWindowController.java
> +              Scans were detected as centroid but contain zero intensity values. This might indicate incorrect conversion by msconvert.
You mean rename the isContainsZeroIntensity method? Or change the tooltip text?

2022-10-04 08:22 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/mainwindow/MainWindowController.java
> +              Scans were detected as centroid but contain zero intensity values. This might indicate incorrect conversion by msconvert.
in the tooltip text, change "zero intensity" to "zero-intensity", so it's clear that it contains m/z values with 0 intensity instead of "no intensity" values.

2022-10-04 08:22 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +        logger.info("Scan number " + s.getScanNumber() + "was found to be empty.");
there's a space missing

2022-10-04 08:23 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/project/impl/RawDataFileImpl.java
> +      logger.warning("""
It could be due to too high noise levels during mzml conversion

2022-10-04 08:23 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_cropfilter/CropFilterParameters.java
> +  public static final BooleanParameter emptyScans =
@robinschmid

2022-10-07 04:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_cropfilter/CropFilterParameters.java
> +  public static final BooleanParameter emptyScans =
I think it should be okay to have it but really discourage this

2022-10-07 05:02 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/data_access/ScanDataAccess.java
> +    return (scan == null | scan.isEmptyScanMZRange()) ? Range.singleton(0d) : scan.getScanningMZRange();
can this be | at this point or needs to be || ?

2022-10-07 05:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/data_access/ScanDataAccess.java
> +    return (scan == null | scan.isEmptyScanMZRange()) ? null : scan.getInjectionTime();
same here

2022-10-07 05:12 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/data_access/ScanDataAccess.java
> +    return (scan == null | scan.isEmptyScanMZRange()) ? Range.singleton(0d) : scan.getScanningMZRange();
okay it should be ||
https://stackoverflow.com/questions/7101992/why-do-we-usually-use-over-what-is-the-difference

2022-10-07 05:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/datamodel/Scan.java
> +    return this.getDataPointMZRange() == null ? true : false;
no need to ?
object == null already evaluates to a boolean

2022-10-07 05:23 UTC, robinschmid requested changes

2022-10-07 05:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/MainWindowController.java
> +          rawDataFile.getSpectraType())) | rawDataFile.isContainsEmptyScans()) {
should be ||

2022-10-07 05:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/MainWindowController.java
> +              Some scans were recognized as empty (ano detected peaks).
ano --> no typo

2022-10-07 05:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/featdet_adapchromatogrambuilder/ModularADAPChromatogramBuilderTask.java
> +      }
Maybe we could rather count the empty scans and log a warning at the end of the task

2022-10-07 05:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_cropfilter/CropFilterTask.java
> +          logger.info("Scan " + scan.getScanNumber() + " has empty m/z range");
this logging might be superfluous. remove.
(or change to logger.finest)

2022-10-07 05:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_cropfilter/CropFilterTask.java
> +        if (scan.isEmptyScanMZRange()) {
Why do you check the ScanMZRange to check for an empty scan. Not sure if this range is sometiems read from a metadata field in mzML or other data files.
You could just check the number of data points

2022-10-07 06:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/projectload/CachedIMSRawDataFile.java
> +    return false;
Maybe throw unsupportedOperationException?

2022-10-07 06:21 UTC, robinschmid commented on src/main/java/io/github/mzmine/parameters/parametertypes/selectors/RawDataFilePlaceholder.java
> +    return false;
Maybe throw unsupported operation exception

2022-10-07 06:23 UTC, robinschmid commented on src/main/java/io/github/mzmine/project/impl/RawDataFileImpl.java
> +    }
only trigger the log once. So !containsEmptyScans && newScan.isEmpty...

2022-10-07 06:23 UTC, robinschmid requested changes
Looks good to me just a few changes

2022-10-10 08:52 UTC, omokshyna commented on src/main/java/io/github/mzmine/datamodel/data_access/ScanDataAccess.java
> +    return (scan == null | scan.isEmptyScanMZRange()) ? Range.singleton(0d) : scan.getScanningMZRange();
Yes, you are totally right, no need for bitwise OR here

2022-10-10 08:53 UTC, omokshyna commented on src/main/java/io/github/mzmine/datamodel/Scan.java
> +    return this.getDataPointMZRange() == null ? true : false;
Yes, fixed

2022-10-10 11:55 UTC, omokshyna commented on src/main/java/io/github/mzmine/modules/dataprocessing/filter_cropfilter/CropFilterTask.java
> +        if (scan.isEmptyScanMZRange()) {
Fixed to check the number of data points. An initial problem was linked to the absent m/z ranges in the mzml files, so I followed with that, but using a number of data points is definitely a more universal solution :)

2022-10-12 00:46 UTC, robinschmid approved these changes
Looks good to me. thanks for all the changes

2022-10-12 00:46 UTC, merged