Fix some issues in Spectral Deconvolution / Hierarchical Clusters #925
mzmine/mzmine3 pull request #933
Opened 2022-10-05 20:39 UTC by asmirn1

- Fix the plot update when the parameters are changed
- Fix the IndexOutOfBoundsException in EICPlot

2022-10-06 06:46 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/EICPlot.java
> +          colorDataset.add(color);
why does this have to be run in a try-catch environment?

2022-10-06 13:22 UTC, asmirn1 commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/EICPlot.java
> +          colorDataset.add(color);
@SteffenHeu It doesn't. it just needs to be called before `xyDataset.addSeries(series)`. I'll move it out the try-catch.

2022-10-06 14:25 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/EICPlot.java
> +          colorDataset.add(color);
but why is the try catch there in the first place? what can cause an exception here?

2022-10-06 14:35 UTC, asmirn1 commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/EICPlot.java
> +          colorDataset.add(color);
xyDataset.addSeries() fires an event to redraw the plot. So if the plot draw fails, we'll catch it. I don't remember exactly why we had this try-catch here. I assume, it couldn't redraw the plot for some reason.

2022-10-07 17:37 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/EICPlot.java
> +          colorDataset.add(color);
That's weird. From where is the dataset added? Changes to the gui need to be run on the java FX thread, otherwise they fire an exception. maybe it was that?

 We have the MZmineCore.runLater() method for that. If that's not the issue, we can keep the try-catch.

2022-10-07 18:27 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/ADAP3DecompositionV1_5Task.java
> +      row.setAverageRT(originalPeakRow.getAverageRT());
All the row types you actually do not have to set. The average values are computed automatically once a new feature is added or the values are changed.

2022-10-07 18:28 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/ADAP3DecompositionV1_5Task.java
> +      row.setAverageRT(originalPeakRow.getAverageRT());
this means that you just set the values in the samples.
Also for example for fragmentation spectra, the list is set in the feature and then reflected to the row

2022-10-07 18:31 UTC, robinschmid requested changes
Looks good. Thanks for the changes. Only the one comment remaining about the average row values

2022-10-11 20:51 UTC, asmirn1 commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/ADAP3DecompositionV1_5Task.java
> +      row.setAverageRT(originalPeakRow.getAverageRT());
@robinschmid So you mean that I don't need to call `row.setAverageMZ()` and `row.setAverageRT()` here. Correct?

2022-10-12 00:43 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/ADAP3DecompositionV1_5Task.java
> +      row.setAverageRT(originalPeakRow.getAverageRT());
Yes. All the average row values are calculated based on bindings

2022-10-12 00:44 UTC, robinschmid approved these changes
Great thanks for the fix

2022-10-12 00:44 UTC, merged