resolved alignment issue
mzmine/mzmine3 pull request #944
Opened 2022-10-12 17:13 UTC by tnguy271

We had worked to resolve adap alignment issue when doing heirachical clustering

2022-10-12 18:39 UTC, SteffenHeu requested changes
Hey, thanks for the changes! I left some small comments.

Most of the feature characteristics such as representative scan, height, area, fwhm, asymmetry are calculated in the ModularFeature constructor usign the FeatureDataUtils class. This makes the integrations more uniform acrooss whole MZmine.

if you experience problems with this utils class, please let us know, so we can adapt it.

2022-10-12 18:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
>      return new ModularFeature(featureList, file, peak.getMZ(), (float) peak.getRetTime(),
please don't use the deprecated constructor, use 
```
public ModularFeature(ModularFeatureList flist, RawDataFile dataFile,
      IonTimeSeries<? extends Scan> featureData, FeatureStatus featureStatus)
```
the featureData can be a SimpleIonTimeSeries constructed from scans, m/zs + intensities in those scans

2022-10-12 18:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +            Range.closed(0.f, (float) peak.getIntensity()));
all this is set in the new constructor automatically.

2022-10-12 18:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      dataPoints[i] = new SimpleDataPoint(retTime, intensity);
why do you use retention time here and not the m/zs?

2022-10-12 18:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    double maxIntensity = 0.0;
maximum intensity is determined in the new ModularFeature constructor

2022-10-12 18:39 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +        representativeScan = scan;
representative scan is also determined in the constructor

2022-10-12 20:51 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      dataPoints[i] = new SimpleDataPoint(retTime, intensity);
the retention time is usually taken from the scans

2022-10-13 00:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      dataPoints[i] = new SimpleDataPoint(retTime, intensity);
so no need to save it in another datastructure. 
Here we need the mz and intensity of each data point in the chromatogram

2022-10-21 08:01 UTC, SteffenHeu requested changes
Another comment.

Also, please use the code intellij code formatter supplied with mzmine.

2022-10-21 17:40 UTC, asmirn1 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    SimpleIonTimeSeries simpleIonTimeSeries = new SimpleIonTimeSeries(null, newMzs, newIntensities, scanNumbers);
@SteffenHeu what values are expected in `SimpleIonTimeSeries`? 

For example if we have peak with the shape:
Scan1, m/z=73, intensity=0
Scan2, m/z=73, intensity=100
Scan3, m/z=73, intensity=200
Scan4, m/z=73, intensity=100
Scan5, m/z=73, intensity=0

Then, the SimpleIonTimeSeries would have m/z array [73, 73, 73, 73, 73] and intensities [0, 100, 200, 100, 0]?

2022-10-24 07:53 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    SimpleIonTimeSeries simpleIonTimeSeries = new SimpleIonTimeSeries(null, newMzs, newIntensities, scanNumbers);
yes, exactly. 

Prior to resolving we put zeros on peak edges if there are no data points between to features so we dont have weird shapes. Inbetween those zeros, you don't need anything. 
After the resolving we dont put zeros again.

If you put zeros on the edges you also need to put the scans accordingly, of course.

2022-10-24 07:55 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    }
you can combine the loops, so you dont loop over the same array twice

2022-10-24 21:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      if (retTime < startRetTime || retTime > endRetTime) continue;
rt>endTime should do break;  because the scans are sorted by retention time

2022-10-25 14:43 UTC, asmirn1 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@robinschmid I don't think it makes sense to add ScanSelectionParameter to the alignment algorithm because the alignment doesn't work with scans directly.

The reason, why we are getting scans is that we need them to create `ModularFeature` with `SimpleIonTimeSeries`.

I understand your comment about MS/MS scans though. To avoid MS/MS scans, we can replace `file.getScans()` with `row.getBestFeature().getScanNumbers()` where `row` is the FeatureListRow from a feature list before the alignment.

Would that work?

2022-10-25 16:05 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
`feature.getScanNumbers()` will only return those scans where it was detected

2022-10-25 17:56 UTC, tnguy271 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@robinschmid @asmirn1  I tried to get the selected Scans from alignedPeakList but there's no scans in there. I guess in the modularFeatureList constructor the scans weren't saved

2022-10-25 18:07 UTC, asmirn1 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@tnguy271 Does `ow.getBestFeature().getScanNumbers()` return any scans, or it's empty also?

2022-10-25 18:12 UTC, tnguy271 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
Yes it does, should I use this one then?

2022-10-25 18:43 UTC, asmirn1 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
I think it's okay to use `row.getBestFeature().getScanNumbers()`. We only need the scan numbers between feature's `startRetTime` and `endRetTime` anyway.

2022-10-25 19:08 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
If there are no scans in the feature list, there is another issue in the previous steps. Which module created the feature list? It should be set there.

2022-10-25 21:03 UTC, asmirn1 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@SteffenHeu @tnguy271 used a wrong feature list, `alignedPeakList`, which is the feature list created during the Alignment step. It makes sense that that feature list has no scans since we didn't add any features to it.

2022-10-25 21:26 UTC, tnguy271 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
Right I used the right featureList variable now and the selectedScans is still null.

2022-10-26 16:00 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
Then we need to make sure that this is set in the steps before. 
Can you list the modules that were run before?

2022-10-26 16:34 UTC, tnguy271 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@robinschmid just referenceComponent I think

2022-10-26 20:08 UTC, tnguy271 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@robinschmid @SteffenHeu I see that the chromatogram resolved_HCdeconv file doesn't have selected scans in it, while chromatogram and chromatogram  resolved do.  I believe it is an issue in decomposePeaks method in ADAP3DecompositionV1_5Task.java, when we create new feature list?

2022-10-27 07:46 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
That could be the case. If the ADAP3DecompositionV1_5Task.java takes "chromatogram resolved" as an input it should transfer all selected files from there to the new feature list.
`resolvedFeatureList.setSelectedScans(dataFile, originalFeatureList.getSeletedScans(dataFile));`

if it's not done already, the applied methods should be copied as well like this:
`originalFeatureList.getAppliedMethods().forEach(m -> resolvedFeatureList.getAppliedMethods().add(m));`

2022-10-27 18:47 UTC, tnguyen3216 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@SteffenHeu I have made the changes.

2022-10-27 18:48 UTC, tnguy271 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +    for (Scan scan : file.getScans()) {
@SteffenHeu we have made the changes.

2022-11-02 09:40 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/ADAP3DecompositionV1_5Task.java
> +    peakList.getAppliedMethods().forEach(m -> resolvedPeakList.getAppliedMethods().add(m));
this is the same thing, remove one of the two

2022-11-02 09:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_hierarchicalclustering/ADAP3DecompositionV1_5Task.java
>      for (final FeatureList.FeatureListAppliedMethod method : peakList.getAppliedMethods()) {
this is the same thing, remove one of the two

2022-11-02 09:41 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/adap_mcr/ADAP3DecompositionV2Task.java
> +    lists.chromatograms.getAppliedMethods().forEach(m -> resolvedPeakList.getAppliedMethods().add(m));
also doubled with the code in the next lines

2022-11-02 09:43 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      System.out.println("**** " + e.getMessage());
please use a logger instead of sysout

logger.log(Level.WARNING, e.getMessage(), e);

2022-11-02 09:44 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      System.out.println("**** " + e.getMessage());
why is this in a try catch anyway?

2022-11-02 15:36 UTC, tnguyen3216 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      System.out.println("**** " + e.getMessage());
@SteffenHeu I have made the changes. Please let me know if you have other comments.

2022-11-02 15:43 UTC, tnguy271 commented on src/main/java/io/github/mzmine/util/adap/ADAPInterface.java
> +      System.out.println("**** " + e.getMessage());
@SteffenHeu I have made the changes. Please let me know if you have other comments.

2022-11-03 11:56 UTC, SteffenHeu approved these changes

2022-11-03 11:56 UTC, SteffenHeu commented
Thanks!

2022-11-03 11:56 UTC, merged