New GNPS json parser
mzmine/mzmine3 pull request #954
Opened 2022-10-19 03:19 UTC by robinschmid

This is only started. 

Idea is to change the SpectraLibraryEntry to a StorableMassSpectrum.

2022-11-02 09:35 UTC, SteffenHeu requested changes
Did you test it for the different libraries?

Can you fix the tests?

2022-11-02 09:35 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_nist/NistMsSearchTask.java
> +              // TODO empty spectrum for now. see if that works
this makes me really confident :D

2022-11-04 18:36 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_nist/NistMsSearchTask.java
> +              // TODO empty spectrum for now. see if that works
I think that was @Kevin-Murray 
But it works for now...

2022-11-04 18:37 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/spectraldb/entry/DBEntryField.java
> +      // TODO change to real data types
Yeah they are old i think :D 
I like them there

2022-11-04 18:53 UTC, Kevin-Murray commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_nist/NistMsSearchTask.java
> +              // TODO empty spectrum for now. see if that works
Yeah, that was me. It was my work around because NIST doesn’t provide you the reference spectrum.

2022-11-04 18:59 UTC, Kevin-Murray commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_nist/NistMsSearchTask.java
> +              // TODO empty spectrum for now. see if that works
Or do you mean the entire module? I could address any issues that you have. It was my first additions to the code base, so likely pretty rough.

2022-11-05 18:52 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/dataprocessing/id_nist/NistMsSearchTask.java
> +              // TODO empty spectrum for now. see if that works
I think its fine. It works.

2022-11-07 09:56 UTC, SteffenHeu commented on src/test/java/datamodel/RegularScanTypesTest.java
> +            new SpectralDBAnnotation(entry, similarity, query, 0.043f)));
Why this change?

2022-11-07 16:30 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/spectraldb/entry/DBEntryField.java
> +      // TODO change to real data types
I added a better description here and removed the other TODO

2022-11-07 16:30 UTC, robinschmid commented on src/test/java/datamodel/RegularScanTypesTest.java
> +            new SpectralDBAnnotation(entry, similarity, query, 0.043f)));
I guess it's not needed. I checked why the equals did not work, and the list types differed. That was not the issue though.
I reverted it to the initial test

2022-11-07 16:30 UTC, robinschmid commented
All done

2022-11-08 19:56 UTC, robinschmid commented
All done and cleaned up

2022-11-08 22:36 UTC, SteffenHeu approved these changes

2022-11-08 22:36 UTC, merged