Msms quality
mzmine/mzmine3 pull request #956
Opened 2022-10-19 15:18 UTC by SteffenHeu

start adding some tools to assess the quality of msms spectra

2022-10-22 05:00 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/mainwindow/MainMenu.fxml
> +    <MenuItem onAction="#runModule" text="Rate MS2 Spectra"
This is an export module so maybe name it: Export MS2 spectra quality

2022-10-22 05:03 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportParameters.java
> +      "Formula score tolerance", "Tolerance for scoring MS/MS peaks with sub-sum formulas.", 0.003,
Sub formula m/z tolerance,     sub molecular formulas

2022-10-22 05:03 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportParameters.java
> +      "Formula score tolerance", "Tolerance for scoring MS/MS peaks with sub-sum formulas.", 0.003,
sum formula is german

2022-10-22 05:05 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportTask.java
> +    return processedRows / (double) numRows;
numRows>0

2022-10-22 05:09 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportTask.java
> +                + "normalized_weighted_entropy" + separator + "collision_energy");
`String.join(separator, "Test", "Join", "All");`
or
`String.join(separator, List.of("Test", "Join", "All"));`

2022-10-22 05:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportTask.java
> +              CompoundDatabaseMatchesType.class);
This will usually be attached to the row rather than the feautre

2022-10-22 05:10 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportTask.java
> +              CompoundDatabaseMatchesType.class);
Maybe also get the formula from spectral matches?

2022-10-22 05:13 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportTask.java
> +              && feature.getFeatureData() instanceof IonMobilogramTimeSeries) {
So this is only for IMS?
This should be clearer in the menu and name of the module.
Or we need to MsMsQuality also for just the best MSMS from the row or similar

2022-10-22 05:15 UTC, robinschmid commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/SpectrumMsMsQuality.java
> +        + explainedPeaksScore.getScore() + separator //
Same here. 
1. String.join(separator, ...)
2. the last separator is too much
3. maybe add getHeader fuction to directly create the header in this record. so its closer to the data concatenation

2022-10-22 05:28 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    if (tic == null || spectrum.getNumberOfDataPoints() == 0) {
|| tic <= 0
if all data points are 0 you would take the ln(0) and break it

2022-10-22 05:28 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    return getSpectralEntropy(spectrum) / Math.log(spectrum.getNumberOfDataPoints());
have to check for the number of data points > 0 here

2022-10-22 05:32 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    return getSpectralEntropy(spectrum) / Math.log(spectrum.getNumberOfDataPoints());
Create function 
getSpectralEntropy(double[] intensities)

2022-10-22 05:33 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    return -spectralEntropy;
use function 
getSpectralEntropy(double[] intensities)

2022-10-22 05:34 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    return -spectralEntropy;
if number of datapoints > 0

2022-10-22 05:40 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +  public static Double getLowestIntensity(@NotNull final MassSpectrum msms) {
Should this be lowest or lowest non-zero

2022-10-22 05:41 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/FeatureUtils.java
> +    return true;
reduce to
return f.getRawDataFile() instanceof IMSRawDataFile && f.getFeatureData() instanceof IonMobilogramTimeSeries

2022-10-22 05:42 UTC, robinschmid reviewed
Some comments but overall interesting

2022-10-22 12:04 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    return getSpectralEntropy(spectrum) / Math.log(spectrum.getNumberOfDataPoints());
then we have to extract it to an array all the time and cant use the scan data access

2022-10-22 12:04 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +  public static Double getLowestIntensity(@NotNull final MassSpectrum msms) {
good point

2022-10-24 08:34 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportTask.java
> +              CompoundDatabaseMatchesType.class);
silly me

2022-10-24 09:23 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/modules/io/export_msmsquality/MsMsQualityExportTask.java
> +              && feature.getFeatureData() instanceof IonMobilogramTimeSeries) {
for now, to be implemented for LC MS as well

2022-10-24 09:28 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    return -spectralEntropy;
won't get here if that's the case

2022-10-24 21:11 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +    return getSpectralEntropy(spectrum) / Math.log(spectrum.getNumberOfDataPoints());
Thats true but in general we should also have an option to calculate for any double[] can still be a special method for spectra

2022-10-24 21:20 UTC, robinschmid commented on src/main/java/io/github/mzmine/util/scans/ScanUtils.java
> +      if (intensity < minIntensity && Double.compare(intensity, 0d) > 0) {
intensity>0

2022-10-24 21:24 UTC, robinschmid requested changes
Only a few open comments

2022-10-26 15:57 UTC, robinschmid approved these changes
Great. Thanks for the changes

2022-10-26 15:57 UTC, merged